### ISSUE TITLE
helm chart locations

### ISSUE THREAD

**Issue by kfox1111** [ceph/ceph-csi#564] opened 2019-08-20 22:26 UTC
We're currently uploading v1.1.0 to the hub. But there seems to be multiple helm chart versions located in trunk. Is there a reason for this?

**Comment by Madhu-1** [comment] 2019-10-01 09:18
@kfox1111 can you point me the link where the issue is seen and  what is wrong. do we need to remove older chart versions once we upload new helm charts?

any idea of how to fix this issue

**Comment by Madhu-1** [comment] 2020-04-02 08:20
this is fixed in helm charts now

**Closed by Madhu-1** 2020-04-02 08:20 UTC
