### ISSUE TITLE
Failed to create cephfs  PVC

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#486] opened 2019-07-22 08:28 UTC
# Describe the bug #

Failed to create cephfs PVC
# Environment details #

- Image/version of Ceph CSI driver: canary
- helm chart version
- Kubernetes cluster version: 1.15.0
- Logs
```
E0722 08:26:57.932549       1 volume.go:100] failed to create subvolume group csi, for the vol csi-vol-77ecd37e-ac5a-11e9-8a38-22008e3300de(an error occurred while running (597) ceph [fs subvolumegroup create myfs csi --mode 777 --pool_layout myfs-data0 -m 10.106.133.206:6789 -c /etc/ceph/ceph.conf -n client.admin --key=***stripped***]: exit status 22: 2019-07-22 08:26:57.543 7f97e93ba700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2019-07-22 08:26:57.543 7f97e93ba700 -1 AuthRegistry(0x7f97e4063b98) no keyring found at /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,, disabling cephx
2019-07-22 08:26:57.580 7f97e93ba700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2019-07-22 08:26:57.580 7f97e93ba700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2019-07-22 08:26:57.580 7f97e93ba700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2019-07-22 08:26:57.614 7f97e93ba700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2019-07-22 08:26:57.614 7f97e93ba700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2019-07-22 08:26:57.614 7f97e93ba700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2019-07-22 08:26:57.614 7f97e93ba700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
Error EINVAL: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/mgr_module.py", line 909, in _handle_command
    return self.handle_command(inbuf, cmd)
  File "/usr/share/ceph/mgr/volumes/module.py", line 182, in handle_command
    return handler(inbuf, cmd)
  File "/usr/share/ceph/mgr/volumes/module.py", line 208, in _cmd_fs_subvolumegroup_create
    return self.vc.create_subvolume_group(vol_name, group_name, mode=mode, pool=pool_layout)
  File "/usr/share/ceph/mgr/volumes/fs/volume.py", line 305, in create_subvolume_group
    sv.create_group(spec, pool=pool, mode=self.octal_str_to_decimal_int(mode))
  File "/usr/share/ceph/mgr/volumes/fs/subvolume.py", line 178, in create_group
    self._mkdir_p(path, mode)
  File "/usr/share/ceph/mgr/volumes/fs/subvolume.py", line 58, in _mkdir_p
    self.fs.mkdir(subpath, mode)
  File "cephfs.pyx", line 801, in cephfs.LibCephFS.mkdir (/home/jenkins-build/build/workspace/ceph-dev-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/14.2.1-636-g64f035c/rpm/el7/BUILD/ceph-14.2.1-636-g64f035c/build/src/pybind/cephfs/pyrex/cephfs.c:8613)
Error: (13, "error in mkdir 'volumes': error code 13")

```

# Steps to reproduce #
deploy cephfs plugin and create PVC

**Comment by Madhu-1** [comment] 2019-07-22 08:29
@humblec @poornimag PTAL

**Comment by humblec** [comment] 2019-07-22 08:38
@ajarr @batrick can you please take a look at this ?

**Comment by ajarr** [comment] 2019-07-22 12:27
As per the log, the failure is when ceph-mgr tries to create a `/volumes/csi` directory within the filesystem.

The Ceph cluster version is `ceph-14.2.1-636-g64f035c`. This implies that the ceph HEAD is at `64f035c`, which is the commit previous to the 14.2.2 tag commit. What's curious is that there were no code changes to ceph-mgr volumes module, and cephfs since the version of Ceph (HEAD at `51abe8f00e1a`) that should have been used by the travis CI that passed for the PR https://github.com/ceph/ceph-csi/pull/400

**Comment by ajarr** [comment] 2019-07-22 22:28
OK. I setup kubeadm single node k8s cluster in a test VM.
```
[vagrant@kube ~]$ rpm -qa | grep kube
kubectl-1.15.1-0.x86_64
kubelet-1.15.1-0.x86_64
kubernetes-cni-0.7.5-0.x86_64
kubeadm-1.15.1-0.x86_64
```
setup Ceph cluster (v14.2.2) with latest rook (HEAD at `36479fec1`). From inside the ceph-tool box pod ran the `subvolumegroup create` command and it executed successfully,
```
[root@kube /]# ceph fs subvolumegroup create a csi --mode 777 --pool_layout cephfs.a.data -m 10.107.28.1:6789 -c /etc/ceph/ceph.conf --name client.admin --key=AQBoMjZdgOBLABAAVBT5tOOSPKFTphCdhTjqDQ==
[root@kube /]# mount.ceph 10.107.28.1:6789:/ /mnt/cephfs/ -o name=admin,secret=AQBoMjZdgOBLABAAVBT5tOOSPKFTphCdhTjqDQ==
[root@kube /]# cd /mnt/cephfs/
[root@kube cephfs]# ls -lRh
.:
total 0
drwxr-xr-x 1 root root 1 Jul 22 22:11 volumes

./volumes:
total 0
drwxrwxrwx 1 root root 0 Jul 22 22:11 csi

./volumes/csi:
total 0
```
@poornimag were you able to recreate the environment as done by travis CI?

**Comment by ajarr** [comment] 2019-07-22 22:31
@Madhu-1 can you re-trigger the CI and check?

**Comment by invent-lwj** [comment] 2019-07-23 05:14
I encounter same error when create pvc. 
my ceph is 14.2.2, kubernetes is 1.13.5 
I run "ceph fs subvolumegroup create cephfs aaa" on ceph monitor, see the same error:
```
[root@nautilus1 ~]# ceph fs subvolumegroup create cephfs aaa
Error EINVAL: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/mgr_module.py", line 909, in _handle_command
    return self.handle_command(inbuf, cmd)
  File "/usr/share/ceph/mgr/volumes/module.py", line 182, in handle_command
    return handler(inbuf, cmd)
  File "/usr/share/ceph/mgr/volumes/module.py", line 208, in _cmd_fs_subvolumegroup_create
    return self.vc.create_subvolume_group(vol_name, group_name, mode=mode, pool=pool_layout)
  File "/usr/share/ceph/mgr/volumes/fs/volume.py", line 305, in create_subvolume_group
    sv.create_group(spec, pool=pool, mode=self.octal_str_to_decimal_int(mode))
  File "/usr/share/ceph/mgr/volumes/fs/subvolume.py", line 178, in create_group
    self._mkdir_p(path, mode)
  File "/usr/share/ceph/mgr/volumes/fs/subvolume.py", line 58, in _mkdir_p
    self.fs.mkdir(subpath, mode)
  File "cephfs.pyx", line 801, in cephfs.LibCephFS.mkdir (/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/14.2.2/rpm/el7/BUILD/ceph-14.2.2/build/src/pybind/cephfs/pyrex/cephfs.c:8613)
Error: (13, "error in mkdir 'volumes': error code 13")
```
This is the issue of ceph 14.2.2 ?

**Comment by poornimag** [comment] 2019-07-23 10:33
After debugging with @ajarr 
Possible RCA: The ceph mgr process now runs as ceph user and not root user, after commit 900abbc967e108ad622648b740a7c57f1268209f got merged in rook master.
Ceph user might not have permission to create volumes/<subvolgroupname> in the ceph fs filesystem, but root user can. All these while ceph-mgr was running as root and could create these directories.

**Comment by jasonbrooks** [comment] 2019-07-24 00:24
I'm getting this, too, with OCP 4.1.6 and rook: v1.0.0-284.g93716bc

**Comment by invent-lwj** [comment] 2019-07-24 01:05
How to fix it ?  @poornimag  could you provide some idea?

**Comment by humblec** [comment] 2019-07-24 05:30
> After debugging with @ajarr
> Possible RCA: The ceph mgr process now runs as ceph user and not root user, after commit 900abbc967e108ad622648b740a7c57f1268209f got merged in rook master.
> Ceph user might not have permission to create volumes/ in the ceph fs filesystem, but root user can. All these while ceph-mgr was running as root and could create these directories.
> 
> @Madhu-1 @humblec ^^

@travisn FYI, is the change in Rook Master expected ? if thats the case, we have to find a way to solve it .

**Comment by poornimag** [comment] 2019-07-24 06:35
To fix this we need to provide the user 'ceph', RW permission to the root of the cephfs filesystem, either  chmod or acl or ceph auth?, @ajarr will have more insight into fixing this.

**Comment by mykaul** [comment] 2019-07-24 09:38
@poornimag  - can you look if https://github.com/rook/rook/pull/3498 and/or https://github.com/rook/rook/pull/3487 help?

**Comment by eriklindahl** [comment] 2019-07-24 10:10
This hit us too when testing with our existing bare-metal ceph-14.2.2 cluster.

I can confirm that editing /lib/systemd/system/ceph-mgr@.service to remove the setuser/setgroup options to ceph-mgr and then restarting the process fixes it, but that hack will be overwritten any time we update ceph.

I have this far not been able to fix it by adjusting the ceph auth capabilities of the client.mgr certificates to give them all permissions like the admin, and giving the 'ceph' user full ACL permissions to the cephfs root directory did not help either.

**Comment by humblec** [comment] 2019-07-24 10:12
Thanks @eriklindahl for the insight. We are working on this and hopefully will get into a solution soon.

**Comment by ajarr** [comment] 2019-07-24 10:27
> > After debugging with @ajarr
> > Possible RCA: The ceph mgr process now runs as ceph user and not root user, after commit 900abbc967e108ad622648b740a7c57f1268209f got merged in rook master.
> > Ceph user might not have permission to create volumes/ in the ceph fs filesystem, but root user can. All these while ceph-mgr was running as root and could create these directories.
> > @Madhu-1 @humblec ^^
> 
> @travisn @poornimag @ajarr FYI, is the change in Rook Master expected ? if thats the case, we have to find a way to solve it .

After this  commit merged on Friday in rook master, https://github.com/rook/rook/commit/900abbc967e108ad622648b740a7
the ceph-csi started failing. @poornimag identified this

**Comment by ajarr** [comment] 2019-07-24 10:31
> This hit us too when testing with our existing bare-metal ceph-14.2.2 cluster.
> 
> I can confirm that editing /lib/systemd/system/ceph-mgr@.service to remove the setuser/setgroup options to ceph-mgr and then restarting the process fixes it, but that hack will be overwritten any time we update ceph.
> 
> I have this far not been able to fix it by adjusting the ceph auth capabilities of the client.mgr certificates to give them all permissions like the admin, and giving the 'ceph' user full ACL permissions to the cephfs root directory did not help either.

@eriklindahl , can you try adding the following options in the `global` section of ceph.conf in the ceph-mgr node and try again,
```
[global]
client mount uid = 0
client mount gid = 0
```

**Comment by eriklindahl** [comment] 2019-07-24 11:21
Thanks @ajarr - that seems to have solved the permissions for creating the subvolumes!

Mostly for the record: I still got some errors about the main "csi" volumegroup not having been created, but that might have been due to me fiddling around creating/removing it earlier - in any case it worked fine again when I first created the csi group manually.

This might not be related to the permissions here, but when I mount the created pvc in a pod (using the example files), I'm still having some problems related to permissions:

- If I try to create a file in the mounted volume in the pod, I get "write error: Operation not permitted"
- If I create a file in cephfs, I can see the file (including its size) in the pod, but if I try to look at it e.g. with 'less', I don't get any contents

This might be completely unrelated, although pointers to solutions are always appreciated ;-)

**Comment by ajarr** [comment] 2019-07-24 11:29
https://github.com/ceph/ceph-csi/pull/492 is a temporary fix to unblock the PRs in ceph-csi

The proper fix will be tracked in ceph/rook

**Comment by ajarr** [comment] 2019-07-24 12:06
> Thanks @ajarr - that seems to have solved the permissions for creating the subvolumes!
> 
> Mostly for the record: I still got some errors about the main "csi" volumegroup not having been created, but that might have been due to me fiddling around creating/removing it earlier - in any case it worked fine again when I first created the csi group manually.
> 
> This might not be related to the permissions here, but when I mount the created pvc in a pod (using the example files), I'm still having some problems related to permissions:
> 
> * If I try to create a file in the mounted volume in the pod, I get "write error: Operation not permitted"

Were you root or a regular user?

> * If I create a file in cephfs, I can see the file (including its size) in the pod, but if I try to look at it e.g. with 'less', I don't get any contents
> 

This is strange. @batrick any idea?

> This might be completely unrelated, although pointers to solutions are always appreciated ;-)

**Comment by ajarr** [comment] 2019-07-24 12:12
@invent-lwj , @jasonbrooks  were you able to try this https://github.com/ceph/ceph-csi/issues/486#issuecomment-514577205 ?

**Comment by eriklindahl** [comment] 2019-07-24 12:45
Hi,

> Were you root or a regular user?

I tried both with the same result. When testing as root on the node running the container, I noticed I got the same permission troubles even when accessing it under /var/lib/kubelet.

This made me look into the ceph auth permissions. When creating the PVC, according to the log files on the csi plugin, it creates a new client user specific to the volume. If I change the osd permissions from "allow rw pool=cephfs_data_fast namespace=fsvolumes_csi-vol-3a041c3e-ae0b-11e9-a9f1-167127741514"  to simply "allow rw", then it works fine after I restart (rebind) the mount.

Skipping merely the pool or the namespace limitation in the caps is not sufficient.

**Comment by eriklindahl** [comment] 2019-07-24 12:54
Sorry, I'm an idiot/PEBKAC. I made a typo when specifying the namespace, so it *is* sufficient to merely specify the namespace.

That also makes me suspect I found the actual issue. Our CephFS storage is setup with multiple pools, where the fast storage pool is not the same as the default pool - and I think I need the permissions to apply to both pools ;-) I'll see if I can get that working, but in any case that's unrelated to this issue, so I'll open a new one if it's still relevant.

Thanks a lot for the help!

**Comment by ajarr** [comment] 2019-07-24 13:09
> Hi,
> 
> > Were you root or a regular user?
> 
> I tried both with the same result. When testing as root on the node running the container, I noticed I got the same permission troubles even when accessing it under /var/lib/kubelet.
> 
> This made me look into the ceph auth permissions. When creating the PVC, according to the log files on the csi plugin, it creates a new client user specific to the volume. If I change the osd permissions from "allow rw pool=cephfs_data_fast namespace=fsvolumes_csi-vol-3a041c3e-ae0b-11e9-a9f1-167127741514" to simply "allow rw", then it works fine after I restart (rebind) the mount.
> 
> Skipping merely the pool or the namespace limitation in the caps is not sufficient.

@poornimag ,  ^^   I thought we took care of this?

@eriklindahl , ah! OK. We're getting rid of auth ID creation for every PVC create. The corresponding PR  https://github.com/ceph/ceph-csi/pull/437 is close to being merged. Out of curiousity, can you share the output of the following command when you run them from the root of the mount,
```
getfattr -n ceph.dir.layout.pool .
getfattr -n ceph.dir.layout.pool_namespace .
```

**Comment by ajarr** [comment] 2019-07-24 13:13
@ShyamsundarR , @poornimag ^^

**Comment by eriklindahl** [comment] 2019-07-24 14:46
Hi,

On Wed, Jul 24, 2019 at 3:09 PM Ramana Raja <notifications@github.com>
wrote:

> @eriklindahl <https://github.com/eriklindahl> , ah! OK. We're getting rid
> of auth ID creation for every PVC create. The corresponding PR #437
> <https://github.com/ceph/ceph-csi/pull/437> is close to being merged. Out
> of curiousity, can you share the output of the following command when you
> run them from the root of the mount,
>

Sure. First, just to follow up - the only reason for the pool discrepancy
seems to have been that I also need to use the same pool layout when I
(manually) created the csi subvolumegroup. After that everything works
beautifully, and it doesn't seem to matter that the default pool of cephfs
is actually a different one. After that, I get these results for the
commands, which agrees perfectly with what I wanted:

> getfattr -n ceph.dir.layout.pool .
>
> ceph.dir.layout.pool="cephfs_data_fast"

>
> getfattr -n ceph.dir.layout.pool_namespace .
>
>
ceph.dir.layout.pool_namespace="fsvolumens_csi-vol-bebe6f2b-ae20-11e9-a9f1-167127741514"

Thanks again!

Erik

-- 
Erik Lindahl <erik.lindahl@dbb.su.se>
Professor of Biophysics, Dept. Biochemistry & Biophysics, Stockholm
University
Science for Life Laboratory, Box 1031, 17121 Solna, Sweden

**Comment by ajarr** [comment] 2019-07-24 16:57
The temporary fix in rook for rook users is close to being merged,
https://github.com/rook/rook/pull/3513

The fix in Ceph is being tracked here,
http://tracker.ceph.com/issues/40927

**Comment by Madhu-1** [comment] 2019-07-24 17:02
@poornimag can you revert back  the PR  for e2e workaround once https://github.com/rook/rook/pull/3513 is merged

**Comment by jasonbrooks** [comment] 2019-07-24 19:54
I updated my operator to the version of the image w/ this 3513 PR and my cephfs pv is working as expected.

**Comment by ajarr** [comment] 2019-07-24 20:31
@jasonbrooks thanks!

**Comment by ShyamsundarR** [comment] 2019-07-24 23:03
@ajarr Thanks for tracking this and ensuring things are healthy. Can I know what we need to reflect in CSI documentation for non-rook setups?

**Comment by ajarr** [comment] 2019-07-25 09:23
@ShyamsundarR , ask folks to do this https://github.com/ceph/ceph-csi/issues/486#issuecomment-514577205 until the issue http://tracker.ceph.com/issues/40927 gets resolved in ceph nautlius stable release?

**Closed** 2019-07-26 11:36 UTC
Labels: Priority-0, bug, cephfs

**Comment by ajarr** [comment] 2019-07-26 13:39
[SOLVED] in rook based Ceph deployments since https://github.com/rook/rook/commit/e52efdb8d4ed98129708d49cbbbbbcb083b02d6c

and in non-rook Ceph deployments by,
https://github.com/ceph/ceph-csi/commit/7dc723ebbc0300
