### ISSUE TITLE
When the network fluctuates, the mount will report an error

### ISSUE THREAD

**Issue by peacocktrain** [ceph/ceph-csi#970] opened 2020-04-23 03:52 UTC
# Describe the bug #
When the network is suddenly disconnected and then restored, the file mount becomes unavailable. 
**Here is the error report**
> E0423 03:19:03.235751       1 utils.go:161] ID: 59294 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/pods/37124b57-9d0d-4aea-8e42-488db9ae2e3d/volumes/kubernetes.io~csi/pvc-minio-0-copy/mount: permission denied

**the file on a physical machine**
![image](https://user-images.githubusercontent.com/15363932/80057012-36ba0b80-8558-11ea-9a41-37337a8fd717.png)

# Environment details #

- Image/version of Ceph CSI driver
2.0.1
- Kubernetes cluster version
1.16
- Kernel
4.19.12-1.el7.elrepo.x86_64
# Steps to reproduce #

1. A file is mounted by csi, keeping read and write
2. Shut down the network
3. recover the network

# Expected behavior #

When the network is restored, the file is also restored
or
Manual recovery, but there is no need to restart the machine

**Comment by nixpanic** [comment] 2020-04-23 12:04
Hi @peacocktrain!

Is this a problem with CephFS or RBD? And what type of mounter do you use (kernel client or userspace)?

Assuming CephFS for now, and the FUSE mounter... @joscollin @kotreshhr what is the expected behaviour, and can is be made to auto-recover after the network is back up?

**Comment by Madhu-1** [comment] 2020-04-23 12:07
@nixpanic We have issues with cephfs fuse mounter. As its in userspace best suggestion will be to use kcephf

**Comment by joscollin** [comment] 2020-04-23 12:11
> When the network is suddenly disconnected and then restored, the file mount becomes unavailable.

This is a normal behaviour. I think it would hang when the MDS become unavailable.

**Comment by peacocktrain** [comment] 2020-04-24 01:59
> Hi @peacocktrain!
> 
> Is this a problem with CephFS or RBD? And what type of mounter do you use (kernel client or userspace)?
> 
> Assuming CephFS for now, and the FUSE mounter... @joscollin @kotreshhr what is the expected behaviour, and can is be made to auto-recover after the network is back up?

CephFS,Kernel client,  Can't recover

**Comment by peacocktrain** [comment] 2020-04-24 02:02
> > When the network is suddenly disconnected and then restored, the file mount becomes unavailable.
> 
> This is a normal behaviour. I think it would hang when the MDS become unavailable.

The file cannot be mounted after network recovery, and the file mount is damaged. Restart the physical node to recover.

**Comment by peacocktrain** [comment] 2020-04-24 02:22
Mounting the error file after network recovery is not accessible. I have tried many recovery methods including restarting csi to remove the damaged mount file. Finally, the machine had to be restarted

**Comment by peacocktrain** [comment] 2020-04-30 02:31
> This is a normal behaviour. I think it would hang when the MDS become unavailable.

How to repair？

**Comment by joscollin** [comment] 2020-04-30 03:23
@peacocktrain 

Your initial problem itself doesn't give enough idea what you are trying to achieve. 

> Shut down the network

Why did you do that? Is it a part of your workflow?

> How do I recover it if I don't restart node

At this stage, you have to define what do you want to recover on your cluster. There are different disaster recovery methods for CephFS defined under: https://docs.ceph.com/docs/master/cephfs/#troubleshooting-and-disaster-recovery. These are only for CephFS. What about the other nodes, PG Recovery, rebalancing etc?

> if I don't restart node

There shouldn't be such condition. Based on your initial cluster configuration, At some point in your recovery process you have to bring that node up too.

What is the current status of your cluster? Create a sosreport from your cluster which gather the current logs and decide what changes are required to bring your cluster back to a HEALTH_OK state.

**Comment by peacocktrain** [comment] 2020-04-30 04:13
@joscollin 
ceph cluster is HEALTH_OK .
I mean the mounted pv is not available，the mount file is damaged.
I want to recover mounted pv to the available state

**Comment by joscollin** [comment] 2020-04-30 06:12
What happens when you try to remount? 

@Madhu-1 Will it (PV) try to remount in this scenario?

**Comment by peacocktrain** [comment] 2020-04-30 06:27
> What happens when you try to remount?

csi report err

`E0423 03:19:03.235751 1 utils.go:161] ID: 59294 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/pods/37124b57-9d0d-4aea-8e42-488db9ae2e3d/volumes/kubernetes.io~csi/pvc-minio-0-copy/mount: permission denied`

damaged mount file
![image](https://user-images.githubusercontent.com/15363932/80679027-aac35900-8aee-11ea-994f-1a8882910664.png)

**Comment by joscollin** [comment] 2020-04-30 06:36
So this error is basically a Permission Denied from the CSI. We need to fix that issue first before thinking about the "recovery".

@Madhu-1 Why this gives a Permission Denied?

**Comment by Madhu-1** [comment] 2020-05-04 05:56
no idea why its permission denied @peacocktrain can you please check the cephfs subvolume is mounted on the cephfsplugin container? if yes can you try to write some data to it?

**Comment by Madhu-1** [comment] 2020-05-04 05:57
@peacocktrain can you please provide logs of cephfsplugin once the node is rebooted?

**Comment by peacocktrain** [comment] 2020-05-06 03:05
> can you please check the cephfs subvolume is mounted on the cephfsplugin container? if yes can you try to write some data to it? @Madhu-1 

It's mounted，but can‘t be writen.

> can you please provide logs of cephfsplugin once the node is rebooted?

The change after reboot is that the broken mount file is fixed. cephfsplugin recovery journey
So the point is why the mount file is broken when the network is disconnected.@Madhu-1

**Comment by peacocktrain** [comment] 2020-05-14 01:45
Is there any progress？

**Comment by Madhu-1** [comment] 2020-05-14 08:34
@peacocktrain is there any way i can reproduce this issue in a VM? if yes can you give me the exact commands or steps to reproduce this issue

**Comment by Madhu-1** [comment] 2020-05-14 08:36
Even am not sure who will restart the pods when the network system is back online? either its job of kubelet or others. when you disconnected the network cephfs-plugin pod will be in running the state?

**Closed** 2020-10-12 14:33 UTC
Labels: component/cephfs, wontfix

**Comment by ikogan** [comment] 2021-09-17 14:05
I experienced something like this today. I believe it may have to do with the VM hard rebooting at some point and leaving entries around. Unfortunately it's hard to reproduce. I was getting this error from the kubelet:

```
"E0917 13:55:39.769701    1999 nestedpendingoperations.go:301] Operation for \"{volumeName:kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com^offsite-backup podName: nodeName:}\" failed. No retries permitted until 2021-09-17 13:56:11.769623606 +0000 UTC m=+143274.346312629 (durationBeforeRetry 32s). Error: \"UnmountDevice failed for volume \\\"offsite-backup\\\" (UniqueName: \\\"kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com^offsite-backup\\\") on node \\\"worker1.private\\\" : kubernetes.io/csi: attacher.UnmountDevice failed: rpc error: code = Internal desc = stat /var/lib/kubelet/plugins/kubernetes.io/csi/pv/offsite-backup/globalmount: permission denied\"\n"
```

I went and saw the same behavior as above with a sort of broken mount. I was able to fix it by simply unmounting that directory but I couldn't do anything else to it. Is there a way the CSI driver can detect this condition and just unmount it despite not being able to `stat` it?

**Comment by klausenbusk** [comment] 2022-01-17 11:36
@Madhu-1 I experienced this on our cluster and it seems easy to reproduce:
```sh
$ ip link set dev enp1s0 down
# wait a few minues
$ ip link set dev enp1s0 up
$ ls '/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-6a4e126d-2bf0-4c27-bd46-c06defc57215/globalmount'
ls: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-6a4e126d-2bf0-4c27-bd46-c06defc57215/globalmount: Permission denied
```

It looks like the node can't recover from it (some pods stuck `Terminating` and this error):
```
Jan 17 11:15:43 master1 kubelet[1756]: E0117 11:15:43.650223    1756 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com^0001-0009-rook-ceph-0000000000000001-56b86749-56a2-11ec-8b76-16049ffefde7 podName:4f342d89-8135-4c70-b71e-1555a7491f80 nodeName:}" failed. No retries permitted until 2022-01-17 11:17:45.6501625 +0000 UTC m=+3619782.700231021 (durationBeforeRetry 2m2s). Error: "UnmountVolume.TearDown failed for volume \"data\" (UniqueName: \"kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com^0001-0009-rook-ceph-0000000000000001-56b86749-56a2-11ec-8b76-16049ffefde7\") pod \"4f342d89-8135-4c70-b71e-1555a7491f80\" (UID: \"4f342d89-8135-4c70-b71e-1555a7491f80\") : kubernetes.io/csi: mounter.TearDownAt failed: rpc error: code = Internal desc = stat /var/lib/kubelet/pods/4f342d89-8135-4c70-b71e-1555a7491f80/volumes/kubernetes.io~csi/pvc-2df0f664-62cf-4aba-900c-f672d4e3650f/mount: permission denied"
```

This is with a oldish release of k8s/Rook/ceph-csi (`v1.20.9`/`v1.7.2`/`v3.4.0`).
```sh
$ uname -a
Linux master1 5.10.63-yocto-standard #1 SMP Thu Sep 9 02:58:13 UTC 2021 x86_64 GNU/Linux
```

**Comment by Madhu-1** [comment] 2022-01-17 11:37
@klausenbusk are you using fuse mounter or the kernel mounter?

**Comment by klausenbusk** [comment] 2022-01-17 11:52
The kernel mounter (type would be `fuse.ceph` if FUSE right? and I see no `ceph-fuse` processes):
```sh
$ mount | grep pvc-6a4e126d-2bf0-4c27-bd46-c06defc57215
10.102.115.127:6789,10.111.164.119:6789,10.96.207.177:6789:/volumes/csi/csi-vol-56b87075-56a2-11ec-8b76-16049ffefde7/a563e7c1-8ccf-465f-a300-1bafdd1859eb on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-6a4e126d-2bf0-4c27-bd46-c06defc57215/globalmount type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=ceph-filesystem,_netdev)
10.102.115.127:6789,10.111.164.119:6789,10.96.207.177:6789:/volumes/csi/csi-vol-56b87075-56a2-11ec-8b76-16049ffefde7/a563e7c1-8ccf-465f-a300-1bafdd1859eb on /var/lib/kubelet/pods/4f4e436f-0911-45ae-8d8a-b0ea2e532bf2/volumes/kubernetes.io~csi/pvc-6a4e126d-2bf0-4c27-bd46-c06defc57215/mount type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=ceph-filesystem,_netdev)
```

**Comment by Madhu-1** [comment] 2022-01-17 11:54
@klausenbusk yes looks like it but can also provide CSI plugin logs and storageclass?

**Comment by klausenbusk** [comment] 2022-01-17 12:10
```sh
$ kubectl -n rook-ceph logs csi-cephfsplugin-htq76 -c csi-cephfsplugin > csi-cephfsplugin.txt
$ kubectl -n rook-ceph get storageclass
NAME                   PROVISIONER                     RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
ceph-block (default)   rook-ceph.rbd.csi.ceph.com      Delete          Immediate           true                   41d
ceph-bucket            rook-ceph.ceph.rook.io/bucket   Delete          Immediate           false                  41d
ceph-filesystem        rook-ceph.cephfs.csi.ceph.com   Delete          Immediate           false                  41d
$ kubectl -n rook-ceph get storageclass -o yaml > storageclasses.txt
```
[csi-cephfsplugin.txt](https://github.com/ceph/ceph-csi/files/7882562/csi-cephfsplugin.txt), [storageclasses.txt](https://github.com/ceph/ceph-csi/files/7881712/storageclasses.txt)

**Comment by klausenbusk** [comment] 2022-01-17 14:54
I guess one way of fixing this, is returning `NodeGetVolumeStatsResponse` without `VolumeUsage` but with `VolumeCondition { Abnormal: true }` if the `mount` is "broken".

**Comment by Madhu-1** [comment] 2022-01-17 15:40
Yes, it's possible to use VolumeCondition but someone should identify volume is abnormal and act upon fixing it (which is currently missing). @klausenbusk is it possible to reproduce it in minikube?

**Comment by klausenbusk** [comment] 2022-01-26 14:04
I tested with `minikube` and can't reproduce the issue. We will be updating our current cluster to k8s v1.22.3 or v1.23.3 (from v1.20.9) soon and I will test this scenario afterwards.

Test instructions for `minukube`:
```sh
$ minikube start --driver=kvm2 --container-runtime=cri-o --nodes=3 --extra-disks=1 --memory 5G
$ minikube version
minikube version: v1.24.0
commit: 76b94fb3c4e8ac5062daf70d60cf03ddcc0a741b-dirty
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"archive", BuildDate:"2022-01-14T09:18:54Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
$ helm repo add rook-release https://charts.rook.io/release
$ helm install --create-namespace --namespace rook-ceph rook-ceph rook-release/rook-ceph
$ helm install --namespace rook-ceph rook-ceph-cluster rook-release/rook-ceph-cluster
$ kubectl create -f pvc.yaml
$ kubectl create -f deploy.yaml
$ kubectl get pod -o wide
NAME                                READY   STATUS    RESTARTS   AGE   IP            NODE           NOMINATED NODE   READINESS GATES
nginx-deployment-54bcf8564d-hlstp   1/1     Running   0          38s   10.244.2.13   minikube-m03   <none>           <none>
$ minikube ssh --node minikube-m03 sudo ip link set dev eth0 down
$ # Wait some time
$ kubectl get pod -o wide
NAME                                READY   STATUS              RESTARTS   AGE   IP            NODE           NOMINATED NODE   READINESS GATES
nginx-deployment-54bcf8564d-kwdcw   1/1     Terminating         0          38m   10.244.2.17   minikube-m03   <none>           <none>
nginx-deployment-54bcf8564d-vbqm2   0/1     ContainerCreating   0          26m   <none>        minikube       <none>           <none>
$ virsh -c qemu:///system console minikube-m03 # login as root and run ip link set dev eth0 up
$ kubectl get pod -o wide
NAME                                READY   STATUS              RESTARTS   AGE   IP       NODE       NOMINATED NODE   READINESS GATES
nginx-deployment-54bcf8564d-vbqm2   0/1     ContainerCreating   0          28m   <none>   minikube   <none>           <none>
$ kubectl get pod
NAME                                READY   STATUS    RESTARTS   AGE
nginx-deployment-54bcf8564d-vbqm2   1/1     Running   0          34m
```
[deploy.yaml.txt](https://github.com/ceph/ceph-csi/files/7942228/deploy.yaml.txt), [pvc.yaml.txt](https://github.com/ceph/ceph-csi/files/7942232/pvc.yaml.txt)

**Comment by klausenbusk** [comment] 2022-01-31 22:17
@Madhu-1 it looks like I messed up in my `minikube` testing (I used `storageClassName: ceph-block`). Testing again with `storageClassName: ceph-filesystem` I can reproduce the issue in both `minkube` and our own cluster (`v1.22.1`).

Same procedure as in https://github.com/ceph/ceph-csi/issues/970#issuecomment-1022227639 but with `storageClassName: ceph-filesystem` in `pvc.yaml` and waiting `session_autoclose` (300 seconds) before reconnecting the internet on the node.

```
Jan 31 22:14:42 minikube-m02 kubelet[2327]: E0131 22:14:42.538415    2327 nestedpendingoperations.go:335] Operation for "{volumeName:kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com^0001-0009-rook-ceph-0000000000000001-d36341c9-82e0-11ec-9168-deb176bd5272 podName:aeb4c960-8acf-44fa-8e50-9e18c30308f9 nodeName:}" failed. No retries permitted until 2022-01-31 22:16:44.538377155 +0000 UTC m=+1945.196301190 (durationBeforeRetry 2m2s). Error: UnmountVolume.TearDown failed for volume "test" (UniqueName: "kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com^0001-0009-rook-ceph-0000000000000001-d36341c9-82e0-11ec-9168-deb176bd5272") pod "aeb4c960-8acf-44fa-8e50-9e18c30308f9" (UID: "aeb4c960-8acf-44fa-8e50-9e18c30308f9") : kubernetes.io/csi: Unmounter.TearDownAt failed: rpc error: code = Internal desc = stat /var/lib/kubelet/pods/aeb4c960-8acf-44fa-8e50-9e18c30308f9/volumes/kubernetes.io~csi/pvc-7855a614-169a-45de-bfc3-91d90d035ba8/mount: permission denied
```

**Comment by klausenbusk** [comment] 2022-02-01 08:51
https://github.com/ceph/ceph-csi/pull/2833 implements `VOLUME_CONDITION`. Still not sure why it fails with `stat /path/to/mount permission denied` as the [`NodeUnpublishVolume` function](https://github.com/ceph/ceph-csi/blob/28fef9b3797e41f277d11d9a3bde11e971994503/internal/rbd/nodeserver.go#L818-L860) doesn't use `stat`.

**Comment by Madhu-1** [comment] 2022-02-01 08:54
> #2833 implements `VOLUME_CONDITION`. Still not sure why it fails with `stat /path/to/mount permission denied` as the [`NodeUnpublishVolume` function](https://github.com/ceph/ceph-csi/blob/28fef9b3797e41f277d11d9a3bde11e971994503/internal/rbd/nodeserver.go#L818-L860) doesn't use `stat`.

NodeUnpublish internally uses the stat https://github.com/ceph/ceph-csi/blob/28fef9b3797e41f277d11d9a3bde11e971994503/vendor/k8s.io/mount-utils/mount_linux.go#L338. I still need to look into this one currently busy with other things.

**Comment by klausenbusk** [comment] 2022-02-01 10:27
> NodeUnpublish internally uses the stat 

Thanks for the pointer. I don't quite get how that error would bubble up. According to [the log](https://github.com/ceph/ceph-csi/issues/970#issuecomment-1026267869) it is a internal error (`code = Internal`), so it can only come from:

https://github.com/ceph/ceph-csi/blob/00f88e58a0b08be3d7ea009a0cfde8dca23021bf/internal/rbd/nodeserver.go#L849-L851 or https://github.com/ceph/ceph-csi/blob/00f88e58a0b08be3d7ea009a0cfde8dca23021bf/internal/rbd/nodeserver.go#L856-L862

Neither is using `stat` AFAIU.


I also found the relevant [kernel code](https://github.com/torvalds/linux/blob/26291c54e111ff6ba87a164d85d4a4e134b7315c/fs/ceph/mds_client.c#L2809-L2820).

Issue recap: The issue happens when the `file system client` is evicted, which can happen [automatically](https://docs.ceph.com/en/latest/cephfs/eviction/#automatic-client-eviction) and it isn't possible to recover without manual intervention (unmounting the mounts manually).

**Comment by klausenbusk** [comment] 2022-02-01 10:54
> I don't quite get how that error would bubble up.

My bad, looking at the wrong code :/ It must happen here:
https://github.com/ceph/ceph-csi/blob/00f88e58a0b08be3d7ea009a0cfde8dca23021bf/internal/cephfs/nodeserver.go#L294-L304

**Comment by klausenbusk** [comment] 2022-02-16 14:09
I tried changing `util.IsMountPoint(targetPath)` to use `IsNotMountPoint` instead of `IsLikelyNotMountPoint`, but then it fails with:

```
Unmounter.TearDownAt failed: rpc error: code = Internal desc = lstat /var/lib/kubelet/pods/3cc978d9-f609-4e66-84f2-fb05937e5509/volumes/kubernetes.io~csi/pvc-95c1a523-d8f3-4f89-8566-24d5e17e3a69/mount: permission denied 
```
Due to `filepath.EvalSymlinks(file)` in the `IsNotMountPoint` function (added in https://github.com/kubernetes/kubernetes/pull/68741):
https://github.com/ceph/ceph-csi/blob/4235178f7c53ee3e6eba8e37cb175623fc0a8cea/vendor/k8s.io/mount-utils/mount.go#L248-L252

Removing those lines it unmount the PV correctly, but they was added for a reason. I'm not sure how to fix this issue in a clean way, hmm🤔

Patch:
```diff
diff --git a/internal/util/util.go b/internal/util/util.go
index 6bf522713..ac5425f45 100644
--- a/internal/util/util.go
+++ b/internal/util/util.go
@@ -300,7 +300,7 @@ func checkDirExists(p string) bool {
 // IsMountPoint checks if the given path is mountpoint or not.
 func IsMountPoint(p string) (bool, error) {
        dummyMount := mount.New("")
-       notMnt, err := dummyMount.IsLikelyNotMountPoint(p)
+       notMnt, err := mount.IsNotMountPoint(dummyMount, p)
        if err != nil {
                return false, err
        }
diff --git a/vendor/k8s.io/mount-utils/mount.go b/vendor/k8s.io/mount-utils/mount.go
index a882fcc73..67d6880d7 100644
--- a/vendor/k8s.io/mount-utils/mount.go
+++ b/vendor/k8s.io/mount-utils/mount.go
@@ -245,12 +245,6 @@ func IsNotMountPoint(mounter Interface, file string) (bool, error) {
                return notMnt, nil
        }

-       // Resolve any symlinks in file, kernel would do the same and use the resolved path in /proc/mounts.
-       resolvedFile, err := filepath.EvalSymlinks(file)
-       if err != nil {
-               return true, err
-       }
-
        // check all mountpoints since IsLikelyNotMountPoint
        // is not reliable for some mountpoint types.
        mountPoints, mountPointsErr := mounter.List()
@@ -258,7 +252,7 @@ func IsNotMountPoint(mounter Interface, file string) (bool, error) {
                return notMnt, mountPointsErr
        }
        for _, mp := range mountPoints {
-               if isMountPointMatch(mp, resolvedFile) {
+               if isMountPointMatch(mp, file) {
                        notMnt = false
                        break
                }
```

**Comment by Madhu-1** [comment] 2022-02-16 14:11
@klausenbusk check error of `IsNotMountPoint` and see if its permission denied error if yes continue to unmount?

**Comment by Madhu-1** [comment] 2022-02-16 14:14
But we need to root cause why we are getting permission denied error?

**Comment by klausenbusk** [comment] 2022-02-16 14:16
> @klausenbusk check error of `IsNotMountPoint` and see if its permission denied error if yes continue to unmount?

I will try that.

> But we need to root cause why we are getting permission denied error?

It is due to the client getting evicted (as stated in https://github.com/ceph/ceph-csi/issues/970#issuecomment-1026690436). The relevant kernel code is [here](https://github.com/torvalds/linux/blob/26291c54e111ff6ba87a164d85d4a4e134b7315c/fs/ceph/mds_client.c#L2809-L2820).

**Comment by klausenbusk** [comment] 2022-02-16 16:07
PR opened: https://github.com/ceph/ceph-csi/pull/2884

**Comment by adux6991** [comment] 2023-07-27 07:49
Hi all, I encountered exactly the same issue recently. Noticed that PR https://github.com/ceph/ceph-csi/pull/2634 has fixed fuse-mount, what about kernel mount? Do we have plan to fix this? It seems that the only workaround I can do now is restarting the node. Thanks in advance!

**Comment by microyahoo** [comment] 2024-05-23 15:27
> Hi all, I encountered exactly the same issue recently. Noticed that PR #2634 has fixed fuse-mount, what about kernel mount? Do we have plan to fix this? It seems that the only workaround I can do now is restarting the node. Thanks in advance!

hi @Madhu-1, do we have any plan to fix this in kernel mount? Thanks

**Comment by Madhu-1** [comment] 2024-05-27 13:15
> > Hi all, I encountered exactly the same issue recently. Noticed that PR #2634 has fixed fuse-mount, what about kernel mount? Do we have plan to fix this? It seems that the only workaround I can do now is restarting the node. Thanks in advance!
> 
> hi @Madhu-1, do we have any plan to fix this in kernel mount? Thanks

@microyahoo this is not easy to fix in kernel mount. only way for now is to slace down all the affected pods or restart the node.
