### ISSUE TITLE
[csi-rbd] Mount volume fails when PVC is reused to second pod after first pod is deleted

### ISSUE THREAD

**Issue by mkimuram** [ceph/ceph-csi#67] opened 2018-08-10 16:37 UTC
When csi-rbd is used, e2e test for ```testDynamicProvisioning``` with setting ```skipWriteReadCheck``` to ```false``` fails with below messages:

- Console log for e2e test with ```--ginkgo.focus=".*csi rbd.*"```
```
<snip>
STEP: checking the claim
STEP: checking the PV
STEP: checking the created volume is writable and has the PV's mount options
Aug 10 16:23:04.740: INFO: Waiting up to 15m0s for pod "pvc-volume-tester-4rrg8" in namespace "e2e-tests-csi-moc
k-plugin-ktb77" to be "success or failure"
Aug 10 16:23:04.773: INFO: Pod "pvc-volume-tester-4rrg8": Phase="Pending", Reason="", readiness=false. Elapsed:
32.971738ms
<snip>
Aug 10 16:23:33.537: INFO: Pod "pvc-volume-tester-4rrg8": Phase="Succeeded", Reason="", readiness=false. Elapsed
: 28.797109596s
STEP: Saw pod success
Aug 10 16:23:33.537: INFO: Pod "pvc-volume-tester-4rrg8" satisfied condition "success or failure"
STEP: Deleting pod pvc-volume-tester-4rrg8 in namespace e2e-tests-csi-mock-plugin-ktb77
STEP: checking the created volume is readable and retains data
Aug 10 16:23:33.697: INFO: Waiting up to 15m0s for pod "pvc-volume-tester-ldg49" in namespace "e2e-tests-csi-moc
k-plugin-ktb77" to be "success or failure"
Aug 10 16:23:33.751: INFO: Pod "pvc-volume-tester-ldg49": Phase="Pending", Reason="", readiness=false. Elapsed:
53.56882ms
<snip>
Aug 10 16:26:32.882: INFO: Pod "pvc-volume-tester-ldg49": Phase="Pending", Reason="", readiness=false. Elapsed:
2m59.184190378s

```

- Events for the pod with error at that time
```
# kubectl describe pod pvc-volume-tester-ldg49 -n e2e-tests-csi-mock-plugin-ktb77
<snip>
Events:
  Type     Reason       Age               From                Message
  ----     ------       ----              ----                -------
  Warning  FailedMount  9s (x4 over 58s)  kubelet, 127.0.0.1  MountVolume.SetUp failed for volume "pvc-a7736d229cb911e8" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

It seems that second ```runInPodWithVolume``` run to read the volume contents fails to launch pod,
because it fails to mount the volume. Therefore the problem will be "Mount volume fails when PVC is reused to second pod after first pod is deleted."

**Comment by rootfs** [comment] 2018-08-10 16:48
@mkimuram thanks for testing, anything in kubelet that can help us diagnose what was going on with rbd mount?

**Comment by mkimuram** [comment] 2018-08-21 17:46
Attaching logs that is tested with https://github.com/kubernetes/kubernetes/pull/67088/commits/ca0888362c40a2da2039f6c3a5ecbdbbd6d8c2a2

[e2e_rbd_console.txt](https://github.com/ceph/ceph-csi/files/2307412/e2e_rbd_console.txt)
[e2e_rbd_all_log.txt](https://github.com/ceph/ceph-csi/files/2307413/e2e_rbd_all_log.txt)

**Comment by mkimuram** [comment] 2018-08-28 21:47
@gman0 @rootfs

Is my understanding right that csi rbd plugin also requires csiNodePublishSecretName and csiNodePublishSecretNamespace?

After I looked into the logs a bit more, I found that it fails to get nodePublishSecret from request, but the request doesn't have the one. I tried adding these parameters, then it seemed that the key error disappeared, although there was still another error.  

[Container event]
```
Events:
  Type     Reason                  Age                 From                     Message
  ----     ------                  ----                ----                     -------
  Normal   SuccessfulAttachVolume  109s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-8a5e0453aaf511e8"
  Warning  FailedMount             45s (x8 over 109s)  kubelet, 127.0.0.1       MountVolume.SetUp failed for volume "pvc-8a5e0453aaf511e8" : rpc error: code = Unknown desc = fail to check rbd image status with: (RBD key for ID: admin not found), rbd output: ()
```

[Plugin log]
```
I0828 19:07:02.749482       1 utils.go:96] GRPC call: /csi.v0.Node/NodePublishVolume
I0828 19:07:02.749538       1 utils.go:97] GRPC request: volume_id:"csi-rbd-8a960257-aaf5-11e8-9ec4-0242ac110004" target_path:"/var/lib/kubelet/pods/8b97ca22-
aaf5-11e8-9be2-525400b854f0/volumes/kubernetes.io~csi/pvc-8a5e0453aaf511e8/mount" volume_capability:<mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRI
TER > > volume_attributes:<key:"csiNodeStageSecretName" value:"rbd-secret" > volume_attributes:<key:"csiNodeStageSecretNamespace" value:"e2e-tests-csi-mock-pl
ugin-nmx9m" > volume_attributes:<key:"csiProvisionerSecretName" value:"rbd-secret" > volume_attributes:<key:"csiProvisionerSecretNamespace" value:"e2e-tests-c
si-mock-plugin-nmx9m" > volume_attributes:<key:"monitors" value:"172.17.0.3" > volume_attributes:<key:"pool" value:"rbd" > volume_attributes:<key:"storage.kubernetes.io/csiProvisionerIdentity" value:"1535483141843-8081-csi-rbdplugin" >
I0828 19:07:02.753897       1 mount_linux.go:209] Cannot run systemd-run, assuming non-systemd OS
I0828 19:07:02.753957       1 mount_linux.go:210] systemd-run failed with: exit status 1
I0828 19:07:02.753991       1 mount_linux.go:211] systemd-run output: Failed to create bus connection: No such file or directory
I0828 19:07:02.754142       1 keymutex.go:50] LockKey(...) called for id "rbdpvc-8a5e0453aaf511e8"
I0828 19:07:02.754185       1 keymutex.go:53] LockKey(...) for id "rbdpvc-8a5e0453aaf511e8" completed.
I0828 19:07:02.757401       1 keymutex.go:59] UnlockKey(...) called for id "rbdpvc-8a5e0453aaf511e8"
I0828 19:07:02.757467       1 keymutex.go:66] UnlockKey(...) for id. Mutex found, trying to unlock it. "rbdpvc-8a5e0453aaf511e8"
I0828 19:07:02.757482       1 keymutex.go:69] UnlockKey(...) for id "rbdpvc-8a5e0453aaf511e8" completed.
E0828 19:07:02.757504       1 utils.go:100] GRPC error: fail to check rbd image status with: (RBD key for ID: admin not found), rbd output: ()
```

[Code]
```
devicePath, err := attachRBDImage(volOptions, volOptions.UserId, req.GetNodePublishSecrets()) 
```

**Comment by mkimuram** [comment] 2018-08-28 23:08
Oh, I checked the document again and it is well described there. I was confused with cephfs configuration.

**Comment by mkimuram** [comment] 2018-08-29 15:05
@rootfs @gman0 

After I modified rbd driver to specify csiNodePublishSecretName and csiNodePublishSecretNamespace,
I got below error. Please see log files attached for details. Could you check it?

[e2e_rbd_console20180829.txt](https://github.com/kubernetes/kubernetes/files/2332624/e2e_rbd_console20180829.txt)
[e2e_rbd_all_log20180829.txt](https://github.com/kubernetes/kubernetes/files/2332626/e2e_rbd_all_log20180829.txt)

```
I0829 14:49:03.953716       1 utils.go:96] GRPC call: /csi.v0.Node/NodePublishVolume
I0829 14:49:03.953761       1 utils.go:97] GRPC request: volume_id:"csi-rbd-98877136-ab9a-11e8-8b92-0242ac110005" target_path:"/var/lib/kubelet/pods/999ca2ac-ab9a-11e8-bd21-525400b854f0/volumes/kubernetes.io~csi/pvc-985b9cd4ab9a11e8/mount" volume_capability:<mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > > node_publish_secrets:<key:"admin" value:"AQDRrKNVbEevChAAEmRC+pW/KBVHxa0w/POILA==" > volume_attributes:<key:"csiNodePublishSecretName" value:"rbd-secret" > volume_attributes:<key:"csiNodePublishSecretNamespace" value:"e2e-tests-csi-mock-plugin-4nrhp" > volume_attributes:<key:"csiProvisionerSecretName" value:"rbd-secret" > volume_attributes:<key:"csiProvisionerSecretNamespace" value:"e2e-tests-csi-mock-plugin-4nrhp" > volume_attributes:<key:"monitors" value:"172.17.0.4" > volume_attributes:<key:"pool" value:"rbd" > volume_attributes:<key:"storage.kubernetes.io/csiProvisionerIdentity" value:"1535554043926-8081-csi-rbdplugin" > 
I0829 14:49:03.955478       1 mount_linux.go:209] Cannot run systemd-run, assuming non-systemd OS
I0829 14:49:03.955502       1 mount_linux.go:210] systemd-run failed with: exit status 1
I0829 14:49:03.955511       1 mount_linux.go:211] systemd-run output: Failed to create bus connection: No such file or directory
I0829 14:49:03.955912       1 nodeserver.go:74] rbd image: csi-rbd-98877136-ab9a-11e8-8b92-0242ac110005/rbd was succesfully mapped at /dev/rbd0
I0829 14:49:03.955925       1 nodeserver.go:81] target /var/lib/kubelet/pods/999ca2ac-ab9a-11e8-bd21-525400b854f0/volumes/kubernetes.io~csi/pvc-985b9cd4ab9a11e8/mount
fstype ext4
device /dev/rbd0
readonly false
attributes map[storage.kubernetes.io/csiProvisionerIdentity:1535554043926-8081-csi-rbdplugin csiNodePublishSecretName:rbd-secret csiNodePublishSecretNamespace:e2e-tests-csi-mock-plugin-4nrhp csiProvisionerSecretName:rbd-secret csiProvisionerSecretNamespace:e2e-tests-csi-mock-plugin-4nrhp monitors:172.17.0.4 pool:rbd]
 mountflags []
I0829 14:49:03.957368       1 mount_linux.go:209] Cannot run systemd-run, assuming non-systemd OS
I0829 14:49:03.957380       1 mount_linux.go:210] systemd-run failed with: exit status 1
I0829 14:49:03.957388       1 mount_linux.go:211] systemd-run output: Failed to create bus connection: No such file or directory
I0829 14:49:03.957411       1 mount_linux.go:471] Checking for issues with fsck on disk: /dev/rbd0
I0829 14:49:03.980785       1 mount_linux.go:484] `fsck` error fsck from util-linux 2.23.2
fsck.ext2: Bad magic number in super-block while trying to open /dev/rbd0
/dev/rbd0: 
The superblock could not be read or does not describe a correct ext2
filesystem.  If the device is valid and it really contains an ext2
filesystem (and not swap or ufs or something else), then the superblock
is corrupt, and you might try running e2fsck with an alternate superblock:
    e2fsck -b 8193 <device>
I0829 14:49:03.980826       1 mount_linux.go:490] Attempting to mount disk: ext4 /dev/rbd0 /var/lib/kubelet/pods/999ca2ac-ab9a-11e8-bd21-525400b854f0/volumes/kubernetes.io~csi/pvc-985b9cd4ab9a11e8/mount
I0829 14:49:03.980858       1 mount_linux.go:146] Mounting cmd (mount) with arguments ([-t ext4 -o defaults /dev/rbd0 /var/lib/kubelet/pods/999ca2ac-ab9a-11e8-bd21-525400b854f0/volumes/kubernetes.io~csi/pvc-985b9cd4ab9a11e8/mount])
E0829 14:49:03.986317       1 mount_linux.go:151] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o defaults /dev/rbd0 /var/lib/kubelet/pods/999ca2ac-ab9a-11e8-bd21-525400b854f0/volumes/kubernetes.io~csi/pvc-985b9cd4ab9a11e8/mount
Output: mount: wrong fs type, bad option, bad superblock on /dev/rbd0,
       missing codepage or helper program, or other error
       In some cases useful info is found in syslog - try
       dmesg | tail or so.
I0829 14:49:03.986361       1 mount_linux.go:545] Attempting to determine if disk "/dev/rbd0" is formatted using blkid with args: ([-p -s TYPE -s PTTYPE -o export /dev/rbd0])
I0829 14:49:04.004953       1 mount_linux.go:548] Output: "", err: exit status 2
I0829 14:49:04.005000       1 mount_linux.go:519] Disk "/dev/rbd0" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/rbd0]
I0829 14:49:06.065191       1 mount_linux.go:523] Disk successfully formatted (mkfs): ext4 - /dev/rbd0 /var/lib/kubelet/pods/999ca2ac-ab9a-11e8-bd21-525400b854f0/volumes/kubernetes.io~csi/pvc-985b9cd4ab9a11e8/mount
I0829 14:49:06.065260       1 mount_linux.go:146] Mounting cmd (mount) with arguments ([-t ext4 -o defaults /dev/rbd0 /var/lib/kubelet/pods/999ca2ac-ab9a-11e8-bd21-525400b854f0/volumes/kubernetes.io~csi/pvc-985b9cd4ab9a11e8/mount])
I0829 14:49:06.646570       1 utils.go:102] GRPC response: 
I0829 14:49:06.857577       1 utils.go:96] GRPC call: /csi.v0.Node/NodeGetCapabilities
I0829 14:49:06.857621       1 utils.go:97] GRPC request: 
I0829 14:49:06.857665       1 nodeserver-default.go:56] Using default NodeGetCapabilities
I0829 14:49:06.857683       1 utils.go:102] GRPC response: capabilities:<rpc:<> > 
I0829 14:49:09.360212       1 utils.go:96] GRPC call: /csi.v0.Node/NodeUnpublishVolume
I0829 14:49:09.360259       1 utils.go:97] GRPC request: volume_id:"csi-rbd-98877136-ab9a-11e8-8b92-0242ac110005" target_path:"/var/lib/kubelet/pods/999ca2ac-ab9a-11e8-bd21-525400b854f0/volumes/kubernetes.io~csi/pvc-985b9cd4ab9a11e8/mount" 
I0829 14:49:09.362883       1 mount_linux.go:209] Cannot run systemd-run, assuming non-systemd OS
I0829 14:49:09.362927       1 mount_linux.go:210] systemd-run failed with: exit status 1
I0829 14:49:09.362956       1 mount_linux.go:211] systemd-run output: Failed to create bus connection: No such file or directory
I0829 14:49:09.363978       1 mount_linux.go:246] Unmounting /var/lib/kubelet/pods/999ca2ac-ab9a-11e8-bd21-525400b854f0/volumes/kubernetes.io~csi/pvc-985b9cd4ab9a11e8/mount
I0829 14:49:10.185022       1 rbd_util.go:328] rbd: unmap device /dev/rbd0
```

I'm not sure why but is it due to the second mount attempt was done before unmount for the first mount?

**Comment by gman0** [comment] 2018-08-29 17:29
@mkimuram Well just from looking at the output from the driver it looks like the `NodePublishVolume` succeeded. All those error messages are just k8s' `mount` being too verbose (the same applies for those `systemd-run` errors), see the code in here https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount_linux.go#L460 
1. try to mount
2. fails => tries to get filesystem
3. fails as well (it's an unformated block device) => try to format to format to ext4
4. succeeds => mount
5. `NodePublishVolume` returns with success
...
3 seconds later `NodeUnpublishVolume` is called - the Pod got deleted?

**Comment by mkimuram** [comment] 2018-08-29 20:39
@gman0 

Thank you for your comment. 

> 3 seconds later NodeUnpublishVolume is called - the Pod got deleted?

Yes, the first pod was deleted. Let me explain a little be more in detail.

As seen in the code, dynamic provisioning test for [```skipWriteReadCheck=false``` case](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/volume_provisioning.go#L138),
calls [```runInPodWithVolume```](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/volume_provisioning.go#L1130) twice. The first one is to echo 'hello world' to a file on the PV and the second one is to grep it from the file on the PV. Both commands are executed in a different pod with mounting the same PV and it is done sequentially. (1. Create first pod -> 2. echo -> 3. Delete first pod -> 4. Create second pod -> 5. grep -> 6. Delete second pod.  Although, 4 might be called before 3 completes.)

As seen in the log, the first one was succeeded and the second one wasn't succeeded. So, the first pod must have been deleted. And we would like to make the second one to be succeeded. 

```
[1mSTEP[0m: creating a claim
Aug 29 14:48:30.428: INFO: Waiting up to 5m0s for PersistentVolumeClaim pvc-6cjrg to have phase Bound
Aug 29 14:48:30.514: INFO: PersistentVolumeClaim pvc-6cjrg found but phase is Pending instead of Bound.
Aug 29 14:48:32.518: INFO: PersistentVolumeClaim pvc-6cjrg found and phase=Bound (2.090339541s)
[1mSTEP[0m: checking the claim
[1mSTEP[0m: checking the PV
[1mSTEP[0m: checking the created volume is writable and has the PV's mount options
Aug 29 14:48:32.532: INFO: Waiting up to 15m0s for pod "pvc-volume-tester-vwcq6" in namespace "e2e-tests-csi-mock-plugin-4nrhp" to be "success or failure"
Aug 29 14:48:32.623: INFO: Pod "pvc-volume-tester-vwcq6": Phase="Pending", Reason="", readiness=false. Elapsed: 90.542932ms

<snip>

Aug 29 14:49:08.848: INFO: Pod "pvc-volume-tester-vwcq6": Phase="Pending", Reason="", readiness=false. Elapsed: 36.3157729s
Aug 29 14:49:10.852: INFO: Pod "pvc-volume-tester-vwcq6": Phase="Succeeded", Reason="", readiness=false. Elapsed: 38.319999176s
[1mSTEP[0m: Saw pod success
Aug 29 14:49:10.852: INFO: Pod "pvc-volume-tester-vwcq6" satisfied condition "success or failure"
[1mSTEP[0m: Deleting pod pvc-volume-tester-vwcq6 in namespace e2e-tests-csi-mock-plugin-4nrhp
[1mSTEP[0m: checking the created volume is readable and retains data
Aug 29 14:49:11.044: INFO: Waiting up to 15m0s for pod "pvc-volume-tester-d6l7t" in namespace "e2e-tests-csi-mock-plugin-4nrhp" to be "success or failure"
Aug 29 14:49:11.201: INFO: Pod "pvc-volume-tester-d6l7t": Phase="Pending", Reason="", readiness=false. Elapsed: 157.105067ms
Aug 29 14:49:13.205: INFO: Pod "pvc-volume-tester-d6l7t": Phase="Pending", Reason="", readiness=false. Elapsed: 2.161499057s

<snip>

Aug 29 14:49:29.241: INFO: Pod "pvc-volume-tester-d6l7t": Phase="Pending", Reason="", readiness=false. Elapsed: 18.197169692s
```

**Comment by Madhu-1** [comment] 2019-07-16 14:01
tagging it with next release. let me check this
/assign @Madhu-1

**Comment by Madhu-1** [comment] 2019-07-22 04:12
not able to reproduce this one. closing

**Closed by Madhu-1** 2019-07-22 04:12 UTC
Labels: Priority-0, release-1.2.0
