### ISSUE TITLE
e2e failed with "read only FS issue"

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#2483] opened 2021-09-02 14:15 UTC
# Describe the bug #
```
Sep  2 14:15:57.403: INFO: >>> kubeConfig: /root/.kube/config
Sep  2 14:15:57.619: INFO: attach command running after restart, runningAttachCmd: rbd-nbd --id cephcsi-rbd-node -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789 --keyfile=/tmp/csi/keys/keyfile-098782073 --log-file /var/log/ceph/rbd-nbd-0001-0024-c5f1e139-8a51-4ef2-8407-eccf2f4f95db-0000000000000002-caac811d-0bef-11ec-9f9b-924fe3c02099.log attach replicapool/csi-vol-caac811d-0bef-11ec-9f9b-924fe3c02099 --device /dev/nbd0 --try-netlink --reattach-timeout=300 --debug-rbd=20 --io-timeout=330

Sep  2 14:15:57.628: INFO: ExecWithOptions {Command:[/bin/sh -c echo 'Hello World' > /var/lib/www/html/test] Namespace:rbd-1318 PodName:csi-rbd-demo-pod ContainerName:web-server Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
Sep  2 14:15:57.628: INFO: >>> kubeConfig: /root/.kube/config
Sep  2 14:21:03.725: INFO: stdErr occurred: /bin/sh: 1: cannot create /var/lib/www/html/test: Read-only file system

Sep  2 14:21:03.725: FAIL: failed to write IO, err: command terminated with exit code 2, stdErr: /bin/sh: 1: cannot create /var/lib/www/html/test: Read-only file system
```

The subjected run # https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/rest/organizations/jenkins/pipelines/mini-e2e_k8s-1.21/runs/1027/nodes/87/steps/90/log/?start=0

Cc @pkalever

**Comment by Rakshith-R** [comment] 2021-09-02 14:53
Duplicate of https://github.com/ceph/ceph-csi/issues/2204. 
It's still a open issue.

**Comment by Madhu-1** [comment] 2021-09-03 05:51
Closing as  duplicate

**Closed as completed by Madhu-1** 2021-09-03 05:51 UTC
