### ISSUE TITLE
Cannot detect error for not enough space

### ISSUE THREAD

**Issue by chenxuc** [ceph/ceph-csi#1072] opened 2020-05-16 03:25 UTC
# Describe the bug #

I use rook to create a ceph cluster with CSI in my single node k8s cluster. My backend total harddisk for the ceph cluster is only 10G size. But when I create a pod with 20G PVC/PV block device, there's no error or warning reported that the ceph cluster does not have enough space. And the pod still up and running.

I understand Ceph cluster images are sparse and it allows oversubscribe. But shouldn't CSI better detect and report the "not enough space" issue when creating PVC/PV? This is critical in production environments. Thanks.

# Environment details #

- Image/version of Ceph CSI driver : quay.io/cephcsi/cephcsi:v2.1.1
- Helm chart version :
- Kernel version :
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :
- Kubernetes cluster version : v1.16.9
- Ceph cluster version : 14.2.9

# Steps to reproduce #

Just following the example to setup a ceph cluster with rook: https://rook.github.io/docs/rook/master/ceph-examples.html

**Comment by Madhu-1** [comment] 2020-05-18 07:22
Thanks for opening the issue, closing as this is Duplicate of https://github.com/ceph/ceph-csi/issues/820

**Closed by Madhu-1** 2020-05-18 07:22 UTC
