### ISSUE TITLE
csi-attacher fails to register

### ISSUE THREAD

**Issue by sbskas** [ceph/ceph-csi#295] opened 2019-03-30 10:59 UTC
Using kubernetes 1.13.5 and ceph-csi branch csi-v1.0
Creation of ceph-csi works ok but for the attacher that tries to register through a csi-attacher.sock and fails miserably.
2 two problems are present
1- csi-attacher.sock is connected to nothing (should it be a rbdpluging ?)
2- after a couple of minutes of warning CONNECT/TRANSIENT failure, the attacher goes on and tries to call Identity/probe without success.
Using a csi.sock instead of csi-attacher.sock show no improvment.

**Comment by Madhu-1** [comment] 2019-04-01 06:24
duplicate of https://github.com/ceph/ceph-csi/issues/278

@sbskas please reopen if its not duplicate

**Closed by Madhu-1** 2019-04-01 06:24 UTC
