### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by husseinharake** [ceph/ceph-csi#2506] opened 2021-09-14 13:00 UTC
K8s v1.21.3
CSI version 3.4.0
CEPH octopus

I am trying to use subvolumes, the idea is to allow each k8s cluster to access a subvolume which should sort the multi-tenancy issue using a single cephfs infrastructure. A single username is created and used for each k8s cluster.

The steps are as follows: I create a subvolumegroup, create a subvolume as part of the subvolumegroup created in teh first step. Authorize a user to access the group created. Add the values: user name, key, secrets details, cephfs, data pool etc.. in the values.yaml file of the helm chart and deploy it.

create subvolumegroup
**- ceph fs subvolumegroup create cephfs manuel --pool_layout cephfs-data**

create subvolume
**- ceph fs subvolume create cephfs manuel --group_name manuel --pool_layout cephfs-data**

authorize the user 
ceph fs subvolume authorize cephfs manuel manuel --group_name=manuel --access_level=rw

client.manuel
	key: xxxxxxxxxxxxxxxxxxxxxxxxxxx==
	caps: [mds] allow rw path=/volumes/manuel/manuel/324847d6-7a3d-47d0-b685-05282b2acf7f
	caps: [mon] allow r
	caps: [osd] allow rw pool=cephfs-data

in the values.yaml file:
    cephFS:
      subvolumeGroup: "manuel"

In the volumeNamePrefix (honestly i am not sure what should be inserted here)
  volumeNamePrefix: "manuel"

If i use the username admin everything works fine, other users like Manuel in our case with the mentioned permissions earlier gives Operation not permitted

[root@node]# kubectl describe pvc test

failed to provision volume with StorageClass "csi": rpc error: code = Internal desc = rados: ret=-1, Operation not permitted

My storage class yaml file:

[root@node]# kubectl get storageclasses.storage.k8s.io csi -o yaml

allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: ceph-csi-cephfs
    meta.helm.sh/release-namespace: ceph-csi-cephfs
  creationTimestamp: "2021-09-14T12:34:24Z"
  labels:
    app: ceph-csi-cephfs
    app.kubernetes.io/managed-by: Helm
    chart: ceph-csi-cephfs-3.4.0
    heritage: Helm
    release: ceph-csi-cephfs
  name: csi
  resourceVersion: "15148050"
  uid: 96e4cf1e-583e-4b17-94c8-6402c0017c8b
parameters:
  clusterID: f635a9cc-f917-11eb-bb78-248a071e3a06
  csi.storage.k8s.io/controller-expand-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ceph-csi-cephfs
  csi.storage.k8s.io/node-stage-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/node-stage-secret-namespace: ceph-csi-cephfs
  csi.storage.k8s.io/provisioner-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ceph-csi-cephfs
  fsName: cephfs
  pool: cephfs-data
  volumeNamePrefix: manuel
provisioner: cephfs.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate

any help is appreciated.

Thanks and best regards

**Comment by Rakshith-R** [comment] 2021-09-15 05:10
@husseinharake Have you mentioned the subvolmeGroup in csi-config-map which contains the mon-ip ? 

For example https://github.com/ceph/ceph-csi/blob/3aab8dad008c8f9299296e9f63fc00ef533214d5/examples/csi-config-map-sample.yaml#L47

**Comment by husseinharake** [comment] 2021-09-15 06:17
Thanks @Rakshith-R, yes it is mentioned in the configmaps, my csi-configmap is below: 

[root@node ~]# kubectl get configmaps ceph-csi-config -n ceph-csi-cephfs -o yaml
apiVersion: v1
data:
  config.json: '[{"cephFS":{**"subvolumeGroup":"manuel"**},"clusterID":"f635a9cc-f917-11eb-bb78-248a071e3a06","monitors":["192.168.1.2:6789","192.168.1.19:6789","192.168.1.20:6789","192.168.1.21:6789","192.168.1.22:6789"]}]'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: ceph-csi-cephfs
    meta.helm.sh/release-namespace: ceph-csi-cephfs
  creationTimestamp: "2021-09-14T12:34:24Z"
  labels:
    app: ceph-csi-cephfs
    app.kubernetes.io/managed-by: Helm
    chart: ceph-csi-cephfs-3.4.0
    component: provisioner
    heritage: Helm
    release: ceph-csi-cephfs
  name: ceph-csi-config
  namespace: ceph-csi-cephfs
  resourceVersion: "15148048"
  uid: c7842d5f-b54f-4742-a4e6-7fe631ab2bd3

**Comment by Rakshith-R** [comment] 2021-09-15 06:26
@husseinharake ,Can you try with these caps https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md#cephfs 

And modify user auth accordingly https://docs.ceph.com/en/latest/cephfs/client-auth/

**Comment by husseinharake** [comment] 2021-09-15 08:04
@Rakshith-R  I changed the user manuel caps and gave him the same permissions of the admin users but i am still getting  the same error

 ceph auth caps client.manuel osd 'allow *' mgr 'allow *' mon 'allow *' mds 'allow *'

client.manuel
	key: AQCUDjphhG7vABAAf9ZWcwADizXgu43h5UQMRA==
	caps: [mds] allow *
	caps: [mgr] allow *
	caps: [mon] allow *
	caps: [osd] allow *

Events:
  Type     Reason                Age                 From                                                                                                 Message
  ----     ------                ----                ----                                                                                                 -------
  Normal   Provisioning          45s (x8 over 107s)  cephfs.csi.ceph.com_ceph-csi-cephfs-provisioner-fd6b8d7c-5qkc8_7be89cfe-3012-4604-a1b3-26f33bd8109e  External provisioner is provisioning volume for claim "default/manuel"
  Warning  ProvisioningFailed    45s (x8 over 107s)  cephfs.csi.ceph.com_ceph-csi-cephfs-provisioner-fd6b8d7c-5qkc8_7be89cfe-3012-4604-a1b3-26f33bd8109e  failed to provision volume with StorageClass "csi": rpc error: code = Internal desc = rados: ret=-1, Operation not permitted
  Normal   ExternalProvisioning  3s (x9 over 112s)   persistentvolume-controller                                                                          waiting for a volume to be created, either by external provisioner "cephfs.csi.ceph.com" or manually created by system administrator

**Comment by Rakshith-R** [comment] 2021-09-15 08:08
@husseinharake can you try creating cephfs subvolume/rados ls with the same client and key directly on ceph cluster ?

And add logs from csi-cephfsplugin-provisioner pod csi-cephfsplugin container.

**Comment by husseinharake** [comment] 2021-09-15 11:18
I think i figured the reason of the permissions issue. The first problem is the caps as you mentioned earlier, the document you shared showed that the OSD requires these permissions:
"osd", "allow rw tag cephfs *=*"

earlier i changed the permissions to * for OSD, MGR etc. but it did not work, the changes were applied but did not effect until i redeployed the helm chart of CSI. After every changes of of ceph permissions CSI helm need to be redeployed.

now I can successfully create a PVC  with these ceph permissions:

client.manuel
	key: AQD7w0Fha1tgBRAA4KdF/2fOpU802oami1n8Qg==
	caps: [mds] allow rw path=/volume/rados
	caps: [mgr] allow rw
	caps: [mon] allow r
	caps: [osd] allow rw tag cephfs *=*

but I can not mount it:

kubectl describe pod centos7 

  Warning  FailedMount             10m                  kubelet                  MountVolume.MountDevice failed for volume "pvc-21afa72f-8f74-48d6-9484-0003d3dabb28" : rpc error: code = Internal desc = an error (exit status 32) occurred while running mount args: [-t ceph 192.168.1.2:6789,192.168.1.19:6789,192.168.1.20:6789,192.168.1.21:6789,192.168.1.22:6789:/volumes/rados/csi-vol-aef7b3fa-1614-11ec-891c-0e96e4287b20/88220626-c915-43a7-b8c7-ebde235342cc /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-21afa72f-8f74-48d6-9484-0003d3dabb28/globalmount -o name=manuel,secretfile=/tmp/csi/keys/keyfile-362047780,mds_namespace=cephfs,_netdev] stderr: mount error 13 = Permission denied
  Warning  FailedMount             5m2s                 kubelet                  Unable to attach or mount volumes: unmounted volumes=[test1], unattached volumes=[kube-api-access-lv95h test1]: timed out waiting for the condition
  Warning  FailedMount             70s (x6 over 9m20s)  kubelet                  (combined from similar events): MountVolume.MountDevice failed for volume "pvc-21afa72f-8f74-48d6-9484-0003d3dabb28" : rpc error: code = Internal desc = an error (exit status 32) occurred while running mount args: [-t ceph 192.168.1.2:6789,192.168.1.19:6789,192.168.1.20:6789,192.168.1.21:6789,192.168.1.22:6789:/volumes/rados/csi-vol-aef7b3fa-1614-11ec-891c-0e96e4287b20/88220626-c915-43a7-b8c7-ebde235342cc /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-21afa72f-8f74-48d6-9484-0003d3dabb28/globalmount -o name=manuel,secretfile=/tmp/csi/keys/keyfile-495901098,mds_namespace=cephfs,_netdev] stderr: mount error 13 = Permission denied
  Warning  FailedMount             30s (x3 over 9m34s)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[test1], unattached volumes=[test1 kube-api-access-lv95h]: timed out waiting for the condition

**Comment by husseinharake** [comment] 2021-09-15 11:20
my goal is that the user should be able to access a subvolumegroup and not admin access to every volume in cephfs

**Comment by husseinharake** [comment] 2021-09-15 12:29
removing the path parameter sorted the mount issue.
caps: [mds] allow rw

**Comment by husseinharake** [comment] 2021-09-15 12:37
@Rakshith-R the final question would be is there anyway to limit the access to a user by subvolumegroup or subvolume?
a user should be able to access a single subvolume only.

Thanks

**Comment by Rakshith-R** [comment] 2021-09-15 13:22
> @Rakshith-R the final question would be is there anyway to limit the access to a user by subvolumegroup or subvolume?
> a user should be able to access a single subvolume only.
> 
> Thanks 

Mentioning subvolumegroup in csiconfigmap and creating storageclass with that clusterid already serves that purpose, if user is confined to that storageclass in k8s perspective since a regular user cannot modify/recreate storageclass or even view sc secrets. 



@husseinharake check this for limiting access to just a single subvolume https://www.github.com/ceph/ceph-csi/tree/devel/docs%2Fstatic-pvc.md

It has very limited features but may suit your needs.

**Comment by husseinharake** [comment] 2021-09-15 13:29
@Rakshith-R my problem is that i have a single cephfs and multiple k8s clusters. Users could fire their k8s cluster on the fly and have a complete access to their k8s (cluster admin access). RBD could help by giving a user access to a single pool but it does not support RWM. I will check the link that you shared and hopefully that helps limiting the access per subvolume.

Thanks for your help :)

**Comment by Rakshith-R** [comment] 2021-09-30 10:38
hey @husseinharake , please feel free to close the issue if your satisfied :)

**Comment by husseinharake** [comment] 2021-09-30 11:34
Hi @Rakshith-R , 

To be honest the situation is not yet sorted, and we are moving to the CSI-RBD solution (min. requirments with RWO access). The problem with the CSI-Cephfs is that the required caps "https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md#cephfs" allows a user to access all Subvolumegroups / subvolumes that breaks the multi tenancy. I believe CSI-Cephfs driver should offer the possibility to access a subvolume path in teh caps permissions instead of  "osd", "allow rw tag cephfs *=*".

does it make sense what we are trying to solve?

thanks and best regards

**Comment by Rakshith-R** [comment] 2021-09-30 11:37
> Hi @Rakshith-R , 
> 
> To be honest the situation is not yet sorted, and we are moving to the CSI-RBD solution (min. requirments with RWO access). The problem with the CSI-Cephfs is that the required caps "https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md#cephfs" allows a user to access all Subvolumegroups / subvolumes that breaks the multi tenancy. I believe CSI-Cephfs driver should offer the possibility to access a subvolume path in teh caps permissions instead of  "osd", "allow rw tag cephfs *=*".
> 
> does it make sense what we are trying to solve?
> 
> thanks and best regards
> 
> 
> 
>  

@Madhu-1 @nixpanic @humblec any opinions/suggestions on this ?

**Comment by nixpanic** [comment] 2021-11-01 08:39
@kotreshhr, maybe you can give advise on the required CephFS caps that are needed?

**Comment by kotreshhr** [comment] 2021-11-26 14:01
> @kotreshhr, maybe you can give advise on the required CephFS caps that are needed?

@husseinharake `ceph fs subvolume authorize` command[1] should work for you. It restricts the particular user to particular subvolume. 

[1] https://docs.ceph.com/en/latest/cephfs/fs-volumes/

**Comment by husseinharake** [comment] 2021-11-27 15:02
Thanks @kotreshhr that is true howeve I need CSI plugin where the limitation mentioned earlier allows users to access any sub-volumes. CSI-cephfs plugin should follow the cephfs permissions: I believe the caps permissions should be something like:

"osd", "allow rw tag cephfs =/path/subvolume1".
so the k8s cluster that has access to this subvolume could access subvolume1 only.

hope that clarify the requirements.

**Comment by kotreshhr** [comment] 2021-12-01 13:19
@husseinharake Yeah I get it. The caps required to restrict the user to a subvolume is not sufficient for k8/csi to work as intended. I think the user also does many other things and hence those caps. @nixpanic @Madhu-1 can confirm on that. So I don't think there is a simple fix here.

**Comment by kotreshhr** [comment] 2021-12-13 11:09
@husseinharake Could you try with the following caps for `client.manuel` (`node`) and let the `provisioner` caps match the default as in https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md#cephfs . I think this should serve your purpose.

```
"mon", "allow r",
"mgr", "allow rw",
"osd", "allow rw tag cephfs *=*",
"mds", "allow rw path=<subvolume-path>

```

**Comment by husseinharake** [comment] 2021-12-22 10:32
Thanks @kotreshhr does that mean users will always be able to create volumes in any sub-volume but will be able to mount (access) the ones in the mentioned path?

**Comment by kotreshhr** [comment] 2021-12-23 05:40
> Thanks @kotreshhr does that mean users will always be able to create volumes in any sub-volume but will be able to mount (access) the ones in the mentioned path?

Yes, that's right.

**Comment by husseinharake** [comment] 2022-01-03 13:34
Is it possible to block users from creating volumes outside the allowed sub-directory (mentioned path)?

**Comment by Madhu-1** [comment] 2022-01-04 08:12
The ceph auth isolation should be provided at the subvolumegroup level to achieve the multi-tenancy. if we do that we don't need to worry about the static provisioning etc. @kotreshhr what do you think?

the steps should be as follows
## step 1
* create a ceph fs filesystem

## step 2
* create a subvolume group inside the filesystem
* create a user to restrict access to the subvolume group
* create new secret/storageclass and use it

to have multi-tenancy follow step 2 and create more subvolumegroups and users and use it.

**Closed as completed** 2022-02-10 21:07 UTC
Labels: question, wontfix, component/cephfs

**Comment by AntoineNGUYEN31** [comment] 2022-08-09 07:03
you can reduce the scope of cephfs csi to only {{your filesystem}}

[client.kube]
        caps mon = "allow r"
        caps mgr = "allow rw"		
        caps mds = "allow rwp fsname={{your filesystem}}"
        caps osd = "allow rw tag cephfs *={{your filesystem}}"
