### ISSUE TITLE
Rbd map takes more than 3 minutes to map a volume on node

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#507] opened 2019-07-26 12:38 UTC
# Describe the bug #
during node staging for some requests rbd map takes more than 3 minutes to map the rbd volume on the node (note volume size was 1 Gb) this could be a bottleneck to support more parallel request from node plugin, this will affect the pod creation time.

sometimes the map fails without and we can see rbd volume mapped to the node, this will affect 
the volume mounting to other node and also volume deletion as this volume is marked as being used.

@dillaman can you  please let me  know what logs you need in this case

# Environment details #

- Image/version of Ceph CSI driver: canary
- helm chart version
- Kubernetes cluster version:1.15.0
- Logs

# Steps to reproduce #
* Create 50/100 parallel pod which uses `RWO` PVC

**Comment by Madhu-1** [comment] 2019-07-26 13:53
@rootfs @travisn how this is solved in rook and Kube rbd provisioner?

**Comment by dillaman** [comment] 2019-07-26 14:00
There is really no reason why "rbd map" should ever take 3 minutes. Has anyone attempted to 'strace' or gcore the 'rbd' process when this occurs? I still suspect it's related to udev but I haven't been provided w/ my requested data yet.

**Comment by Madhu-1** [comment] 2019-07-26 14:05
> There is really no reason why "rbd map" should ever take 3 minutes. Has anyone attempted to 'strace' or gcore the 'rbd' process when this occurs? 
 i havent tried it. let me get the strace for rbd process

I still suspect it's related to udev but I haven't been provided w/ my requested data yet.

@dillaman strace is enough or you need any other data?

**Comment by dillaman** [comment] 2019-07-26 14:18
@Madhu-1 It's it's udev I would suspect that strace would show it stuck in a `poll` syscall:

> [pid 19545] poll([{fd=7, events=POLLIN}], 1, 120000) = 1 ([{fd=7, revents=POLLIN}])
> [pid 19545] recvmsg(7, {msg_name={sa_family=AF_NETLINK, nl_pid=-864984219, nl_groups=0x000002}, msg_namelen=128->12, msg_iov=[{iov_base={{prefix="libudev", magic=htonl(0xfeedcafe), header_size=40, properties_off=40, properties_len=102, filter_subsystem_hash=htonl(0x2e58e81d), filter_devtype_hash=htonl(0x2e58e81d), filter_tag_bloom_hi=htonl(0), filter_tag_bloom_lo=htonl(0)}, "ACTION=add\0DEVPATH=/devices/rbd/"...}, iov_len=8192}], msg_iovlen=1, msg_control=[{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, cmsg_data={pid=19555, uid=0, gid=0}}], msg_controllen=32, msg_flags=0}, 0) = 142

**Comment by humblec** [comment] 2019-07-26 14:50
> @rootfs @travisn how this is solved in rook and Kube rbd provisioner?

@Madhu-1 have to analyse where is the bottleneck. Btw, this could be "CSI" specific too and not really applicable for intree drivers. Just a thought here. As @dillaman said, we have to start analysis from `rbd map`.

**Comment by dillaman** [comment] 2019-07-26 14:58
BTW -- hopefully it's fixed by this PR [1] in the 14.2.2 release, but the strace would still be helpful in the meantime to confirm.


[1] https://github.com/ceph/ceph/pull/28019

**Comment by Madhu-1** [comment] 2019-07-27 08:08
@dillaman here is the log of one such instance where rbd took 1.18m to map image 
[stace-vol-1-18m.log](https://github.com/ceph/ceph-csi/files/3437961/stace-vol-1-18m.log)

**Comment by dillaman** [comment] 2019-07-27 11:27
Definitely a lot of extra udev related things in the strace. Is this a container running 14.2.1 or had it been respun w/ the new 14.2.2 Ceph release? An "strace -tT" might be nice as well since it will include the times and durations of each syscall.

**Comment by Madhu-1** [comment] 2019-07-27 11:49
@dillaman looks like container base image is `14.2.1`

```
"Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "CEPH_VERSION=nautilus",
                "CEPH_POINT_RELEASE=-14.2.1",
                "CSIBIN=/usr/local/bin/cephcsi"
            ],

"CEPH_POINT_RELEASE": "-14.2.1",
                "GIT_BRANCH": "HEAD",
                "GIT_CLEAN": "True",
                "GIT_COMMIT": "a3c3540a84cadb51d235a7119bf5d3764c0d2607",
                "GIT_REPO": "https://github.com/ceph/ceph-container.git",
                "RELEASE": "HEAD",
                "description": "Ceph-CSI Plugin",
                "maintainer": "Erwan Velu <evelu@redhat.com>",
                "maintainers": "Ceph-CSI Authors",
                "org.label-schema.build-date": "20190305",
                "org.label-schema.license": "GPLv2",
                "org.label-schema.name": "CentOS Base Image",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vendor": "CentOS"
```

**Comment by Madhu-1** [comment] 2019-07-27 12:04
@dillaman attaching the strace with a timestamp . let me try to update the docker image for 14.2.2 and check
[stace-vol-1-18m.log](https://github.com/ceph/ceph-csi/files/3438135/stace-vol-1-18m.log)

**Comment by Madhu-1** [comment] 2019-07-27 16:52
@dillaman attaching strace for image 14.2.2 , still for some request map took around 2 minutes

[stace-ceph14-2-2.log](https://github.com/ceph/ceph-csi/files/3438382/stace-ceph14-2-2.log)


base docker image details

```
 "CEPH_POINT_RELEASE": "-14.2.2",
                "GIT_BRANCH": "HEAD",
                "GIT_CLEAN": "True",
                "GIT_COMMIT": "5938be9f2df87b3acdca2c94712a58d5b7527a6e",
                "GIT_REPO": "https://github.com/ceph/ceph-container.git",
                "RELEASE": "HEAD",
                "description": "Ceph-CSI Plugin",
                "maintainer": "Dimitri Savineau <dsavinea@redhat.com>",
                "maintainers": "Ceph-CSI Authors",
                "org.label-schema.build-date": "20190305",
                "org.label-schema.license": "GPLv2",
                "org.label-schema.name": "CentOS Base Image",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vendor": "CentOS"
```

**Comment by Madhu-1** [comment] 2019-07-29 13:18
@dillaman did you get anything from strace logs? why rbd map is taking more time?

**Comment by dillaman** [comment] 2019-07-29 13:19
First slow down relates to creating the device, which seems to take about 8 seconds:

> 11:53:34.371238 open("/sys/bus/rbd/add_single_major", O_WRONLY) = 5 <0.000064>
> 11:53:34.371367 write(5, "10.100.74.17:6789 name=admin,key"..., 104) = 104 <8.224837>
> 11:53:42.598492 close(5)                = 0 <0.004319>

Then it seems to require about a minute for the udev events to appear:

> 11:53:42.802391 poll([{fd=4, events=POLLIN}], 1, 120000) = 1 ([{fd=4, revents=POLLIN}]) <0.000054>
> 11:53:42.802538 recvmsg(4, {msg_name(12)={sa_family=AF_NETLINK, pid=-2020614630, groups=00000002}, msg_iov(1)=[{"libudev\0\376\355\312\376(\0\0\0(\0\0\0\224\1\0\0\360\3\35\267{\313\305\356"..., 8192}], msg_controllen=32, [{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, {pid=18705, uid=0, gid=0}}], msg_flags=0}, 0) = 444 <0.000048>
> 11:53:42.802732 poll([{fd=4, events=POLLIN}], 1, 120000) = 1 ([{fd=4, revents=POLLIN}]) <6.577519>
> 11:53:49.381673 recvmsg(4, {msg_name(12)={sa_family=AF_NETLINK, pid=-1598299493, groups=00000002}, msg_iov(1)=[{"libudev\0\376\355\312\376(\0\0\0(\0\0\0\264\0\0\0\360\3\35\267{\313\305\356"..., 8192}], msg_controllen=32, [{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, {pid=18566, uid=0, gid=0}}], msg_flags=0}, 0) = 220 <0.000204>
> 11:53:49.382174 poll([{fd=4, events=POLLIN}], 1, 120000) = 1 ([{fd=4, revents=POLLIN}]) <0.000133>
> 11:53:49.382477 recvmsg(4, {msg_name(12)={sa_family=AF_NETLINK, pid=-2020614630, groups=00000002}, msg_iov(1)=[{"libudev\0\376\355\312\376(\0\0\0(\0\0\0b\0\0\0.X\350\35.X\350\35"..., 8192}], msg_controllen=32, [{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, {pid=18705, uid=0, gid=0}}], msg_flags=0}, 0) = 138 <0.000281>
> ....
> 11:54:30.881569 poll([{fd=4, events=POLLIN}], 1, 120000) = 1 ([{fd=4, revents=POLLIN}]) <17.159268>
> 11:54:48.041022 recvmsg(4, {msg_name(12)={sa_family=AF_NETLINK, pid=-243451708, groups=00000002}, msg_iov(1)=[{"libudev\0\376\355\312\376(\0\0\0(\0\0\0\264\0\0\0\360\3\35\267{\313\305\356"..., 8192}], msg_controllen=32, [{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, {pid=19810, uid=0, gid=0}}], msg_flags=0}, 0) = 220 <0.000031>
> 11:54:48.041202 access("/sys/module/rbd/parameters/single_major", F_OK) = 0 <0.000035>
> 11:54:48.041332 close(4)                = 0 <0.002001>

@idryomov Any ideas about these "rbd map" slowdowns?

**Comment by idryomov** [comment] 2019-07-29 15:07
It would be nice to get a trace with -s 1000, to get more context.  "udevadm monitor -k -u -p" might be useful too.

Did you run this "rbd map" manually or was it executed by something?  Were there concurrent "rbd map" commands being executed, for other images?  I might be misremembering how it works, but this trace suggests that it got 7 other rbd "add" events in the meantime.

**Comment by dillaman** [comment] 2019-07-29 15:10
> Did you run this "rbd map" manually or was it executed by something? Were there concurrent "rbd map" commands being executed, for other images? I might be misremembering how it works, but this trace suggests that it got 7 other rbd "add" events in the meantime.

I think this is a test that is concurrently mapping 50 - 100 krbd devices on a node. This particular log example for for "/dev/rbd4", though.

**Comment by idryomov** [comment] 2019-07-29 16:06
(I assume you meant "/dev/rbd42".)

That might be why udev is getting us in trouble.  It's hard to tell what it is doing...  I would like to see "udev monitor" output to confirm that the kernel event is seen right after the mapping is established and that the entire time is spent waiting for the udev "I'm done with processing my rules, etc" event.

**Comment by dillaman** [comment] 2019-07-29 16:10
The Ceph 14.2.2 strace log (stace-ceph14-2-2.log) shows:

> 16:39:33.189288 write(1, "/dev/rbd4\n", 10) = 10 <0.000019>

**Comment by Madhu-1** [comment] 2019-07-29 16:11
@idryomov @dillaman let me know  what logs you need, i will get it tomorrow.

 udev monitor on host machine or container?
And to add - s 1000 to strace.
 Anything else?

**Comment by idryomov** [comment] 2019-07-29 16:46
@dillaman I was looking at stace-vol-1-18m.log, the one you quoted above.

**Comment by idryomov** [comment] 2019-07-29 17:37
@Madhu-1 Well, you haven't answered my question:
> Did you run this "rbd map" manually or was it executed by something?

"udev monitor" needs to be executed where "rbd map" is executed.  For CSI this would be csi-rbdplugin container run on every node as a DaemonSet, right?

**Comment by Madhu-1** [comment] 2019-07-30 04:00
> @Madhu-1 Well, you haven't answered my question:
> 
sorry, This is a test that is concurrently mapping 50 - 100 krbd devices on a node plugin 

> > Did you run this "rbd map" manually or was it executed by something?
> 
mapping will be done by the node plugin process inside the container. nothing is done manually

> "udev monitor" needs to be executed where "rbd map" is executed. For CSI this would be csi-rbdplugin container run on every node as a DaemonSet, right?

yes you are right

**Comment by Madhu-1** [comment] 2019-07-30 11:52
@idryomov @dillaman attaching the logs with -s 1000 option with strace and udev monitor
[map-2m-13s.log](https://github.com/ceph/ceph-csi/files/3446636/map-2m-13s.log)

[udevadm-monitor.log](https://github.com/ceph/ceph-csi/files/3446639/udevadm-monitor.log)

**Comment by idryomov** [comment] 2019-07-30 16:08
Here the actual mapping took over a minute:

```
11:34:26.477600 open("/sys/bus/rbd/add_single_major", O_WRONLY) = 5 <0.000044>
11:34:26.477712 write(5, "10.97.17.30:6789 name=admin,key=client.admin replicapool csi-vol-92147eb2-b2bd-11e9-b02d-9a9c2946382f -", 103) = 103 <66.794900>
11:35:33.273244 close(5)                = 0 <0.000297>
```

I don't know why it took so long, it could be just calling class methods.  How many OSDs does this cluster have?

The rbd event is fine:

```
11:35:33.308345 recvmsg(4, {msg_name(12)={sa_family=AF_NETLINK, pid=-4305, groups=00000002}, msg_iov(1)=[{"libudev\0\376\355\312\376(\0\0\0(\0\0\0c\0\0\0.X\350\35.X\350\35\0\0\0\0\0\0\0\0ACTION=add\0DEVPATH=/devices/rbd/11\0DEVTYPE=rbd\0SEQNUM=2377\0SUBSYSTEM=rbd\0USEC_INITIALIZED=17659509\0", 8192}], msg_controllen=32, [{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, {pid=30869, uid=0, gid=0}}], msg_flags=0}, 0) = 139 <0.000020>

KERNEL[1817.658803] add      /devices/rbd/11 (rbd)
ACTION=add
DEVPATH=/devices/rbd/11
DEVTYPE=rbd
SEQNUM=2377
SUBSYSTEM=rbd

UDEV  [1817.669251] add      /devices/rbd/11 (rbd)
ACTION=add
DEVPATH=/devices/rbd/11
DEVTYPE=rbd
SEQNUM=2377
SUBSYSTEM=rbd
USEC_INITIALIZED=659509
```

The block event took another minute:

```
11:36:33.695257 recvmsg(4, {msg_name(12)={sa_family=AF_NETLINK, pid=-4290, groups=00000002}, msg_iov(1)=[{"libudev\0\376\355\312\376(\0\0\0(\0\0\0\265\0\0\0\360\3\35\267{\313\305\356\2\0\4\0\20\200\0\0ACTION=add\0DEVNAME=/dev/rbd11\0DEVPATH=/devices/virtual/block/rbd11\0DEVTYPE=disk\0ID_FS_TYPE=\0MAJOR=252\0MINOR=176\0SEQNUM=2386\0SUBSYSTEM=block\0TAGS=:systemd:\0USEC_INITIALIZED=26760528\0", 8192}], msg_controllen=32, [{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, {pid=30374, uid=0, gid=0}}], msg_flags=0}, 0) = 221 <0.000022>

KERNEL[1826.762181] add      /devices/virtual/block/rbd11 (block)
ACTION=add
DEVNAME=/dev/rbd11
DEVPATH=/devices/virtual/block/rbd11
DEVTYPE=disk
MAJOR=252
MINOR=176
SEQNUM=2386
SUBSYSTEM=block
```

Note that the _kernel_ block event came 11 seconds after the rbd event, but the _udev_ block event took another ~50 seconds.  (The udev monitor log was cut off, the udev block event is missing.)

I'm attempting to reproduce locally with no CSI involved -- we have never payed any attention to "map 100 images concurrently" use case.

**Comment by idryomov** [comment] 2019-08-01 12:57
I tested both the actual mapping (i.e. bare syscall) and "rbd map" (which tries to wait for the corresponding udev events) but didn't see anything close to two or three minutes.  That said, the numbers for the bare syscall are higher than I expected to see, so I'm working on some profiling code to make sure we don't block unnecessarily in the kernel.  As for udev, I encountered what I think is a bug in libudev [1], but that should impact only "rbd unmap", not "rbd map".

My test was pretty much the worst case (the kernel had to break the header and object map locks and load the object map for each image).  For the bare syscall test I did 300 images, for "rbd map" I did 150 images to avoid fork bomb OOMs.  The cluster had just 1 OSD with 1 PG.

Bare syscall, 300 images, 1 CPU: 36-40s

```
SECONDS	COUNT
5	53
10	15
15	47
20	50
25	55
30	46
35	34
```

Bare syscall, 300 images, 4 CPUs: 7-9s

```
SECONDS	COUNT
5	163
10	137
```

Bare syscall, 150 images, 4 CPUs: 3-4s

```
SECONDS	COUNT
2	88
3	50
4	12
```

"rbd map", 150 images, 4 CPUs: 11-14s

```
SECONDS	COUNT
5	2
10	91
15	57
```

I used the following super simple script:

```
# for ((i = 1; i <= 150; i++)); do rbd create --size 1G img$i; done
# cat map-150.sh 
function do_it() {
    start=$(date +%s)
    rbd map img$i
    end=$(date +%s)
    runtime=$((end - start))
    echo $runtime >> runtime
}

for ((i = 1; i <= 150; i++)); do
    do_it $i &
done
wait
echo OK
```

What are the resource limits on csi-rbdplugin container?  Perhaps try running something similar from inside it?

Also, looking at "udevadm monitor" output I see some remove events.  Does your workload create some volumes while deleting others?

Can you share some info about the environment?  How many physical nodes (i.e.  how many csi-rbdplugin containers are interacting with the cluster?  How many OSDs, etc?  What else is running on those nodes?

[1] https://tracker.ceph.com/issues/41036

**Comment by Madhu-1** [comment] 2019-08-02 08:46
> I tested both the actual mapping (i.e. bare syscall) and "rbd map" (which tries to wait for the corresponding udev events) but didn't see anything close to two or three minutes. That said, the numbers for the bare syscall are higher than I expected to see, so I'm working on some profiling code to make sure we don't block unnecessarily in the kernel. As for udev, I encountered what I think is a bug in libudev [1], but that should impact only "rbd unmap", not "rbd map".
> 
> My test was pretty much the worst case (the kernel had to break the header and object map locks and load the object map for each image). For the bare syscall test I did 300 images, for "rbd map" I did 150 images to avoid fork bomb OOMs. The cluster had just 1 OSD with 1 PG.
> 
> Bare syscall, 300 images, 1 CPU: 36-40s
> 
> ```
> SECONDS	COUNT
> 5	53
> 10	15
> 15	47
> 20	50
> 25	55
> 30	46
> 35	34
> ```
> 
> Bare syscall, 300 images, 4 CPUs: 7-9s
> 
> ```
> SECONDS	COUNT
> 5	163
> 10	137
> ```
> 
> Bare syscall, 150 images, 4 CPUs: 3-4s
> 
> ```
> SECONDS	COUNT
> 2	88
> 3	50
> 4	12
> ```
> 
> "rbd map", 150 images, 4 CPUs: 11-14s
> 
> ```
> SECONDS	COUNT
> 5	2
> 10	91
> 15	57
> ```
> 
> I used the following super simple script:
> 
> ```
> # for ((i = 1; i <= 150; i++)); do rbd create --size 1G img$i; done
> # cat map-150.sh 
> function do_it() {
>     start=$(date +%s)
>     rbd map img$1
>     end=$(date +%s)
>     runtime=$((end - start))
>     echo $runtime >> runtime
> }
> 
> for ((i = 1; i <= 150; i++)); do
>     do_it $i &
> done
> wait
> echo OK
> ```
> 
> What are the resource limits on csi-rbdplugin container? Perhaps try running something similar from inside it?
> 
There is no resource limit we have on rbd-plugin

> Also, looking at "udevadm monitor" output I see some remove events. Does your workload create some volumes while deleting others?
> 
nope in my testing, I created around 100 volumes and starting mounting each volume into a  pod (there will be 100 parallel requests (mapping)

> Can you share some info about the environment? How many physical nodes (i.e. how many csi-rbdplugin containers are interacting with the cluster? How many OSDs, etc? What else is running on those nodes?
> 
> [1] https://tracker.ceph.com/issues/41036

I don't test it on physical nodes, I use a vagrant setup.
with each node having
4 CPU
4GB RAM
2 100GB devices

its 3 node kuberenetes cluster (1 master,2 worker nodes)

there will  be 1 rbd-plugin running on each node, other than rook-ceph pods nothing am  running on  the node

you can try out the test setup here https://github.com/Madhu-1/k8s-cluster
it deploys kuberentes+rook you need to  deploy csi manually

can you replicate above setup and run rbd map inside a  container?

**Comment by idryomov** [comment] 2019-08-02 10:59
> > Also, looking at "udevadm monitor" output I see some remove events. Does your workload create some volumes while deleting others?
> 
> nope in my testing, I created around 100 volumes and starting mounting each volume into a pod (there will be 100 parallel requests (mapping)

If you grep udevadm-monitor.log for ACTION=remove, you will see quite a lot of these events, so something must be unmapping images while the test is running.

So the images are pre-created?  Do you mount them into existing pods or does your test also create pods?  Are they distributed (e.g. 50 on worker1 and 50 on worker2) or all images are mapped on one of the workers?

> its 3 node kuberenetes cluster (1 master,2 worker nodes)
> 
> there will be 1 rbd-plugin running on each node, other than rook-ceph pods nothing am running on the node

How many OSDs?  Is the cluster otherwise idle?

> you can try out the test setup here https://github.com/Madhu-1/k8s-cluster
> it deploys kuberentes+rook you need to deploy csi manually
> 
> can you replicate above setup and run rbd map inside a container?

It would be challenging because my machine is already spread thin.  I also don't have a lot of operational experience with CSI.  Since you already have a reproducing environment, can you try running "rbd map" manually against this cluster?  Even just from the outside and not from the worker or the plugin container, to get at least some baseline.

One of your strace outputs showed a bare syscall taking over a minute.  As you can see from my results, it could be that your setup is overloaded -- a bare syscall test for 300 images went from 38 seconds to 8 seconds with additional CPUs on the client VM (not the OSD).  Do you keep track of system stats during the test (load averages, etc)?

**Comment by ShyamsundarR** [comment] 2019-08-02 14:29
Aside from the fact that we are dealing with and attempting to understand (and possibly fix) why rbd map times out, I think in the rbd CSI plugin code we need to add some safety workarounds/checks, that will unmap the device on timeout errors from `rbd map` (of course checking if the device is mounted or not etc.). This will ensure that we do not leave behind stale maps in such conditions, which is causing the most problem in certain cases.

Also, the above maybe a good thing to keep as there may be other cases (busyness or otherwise) where we may need to take such actions.

Opening a new issue to track this, and not muddle the conversation here.

**Comment by Madhu-1** [comment] 2019-08-05 05:10
@idryomov 

>If you grep udevadm-monitor.log for ACTION=remove, you will see quite a lot of these events, so something must be unmapping images while the test is running.

if there is an error during the node staging (which means mounting rbd devices  to a path fails) we unmap the rbd device

 I have tested the above script in the container,

I got an error during mapping
```
rbd: image img147: image uses unsupported features: 0x38
```
after disabling these features

```
for ((i = 1; i <= 150; i++)); do rbd feature disable replicapool/img$i object-map fast-diff deep-flatten; done
```

mapping was fast. it took max 10 sec to map few  images


@nehaberry is it possible to test this in OCP?

**Comment by nehaberry** [comment] 2019-08-05 05:54
> @idryomov
> 
> > If you grep udevadm-monitor.log for ACTION=remove, you will see quite a lot of these events, so something must be unmapping images while the test is running.
> 
> if there is an error during the node staging (which means mounting rbd devices to a path fails) we unmap the rbd device
> 
> I have tested the above script in the container,
> 
> I got an error during mapping
> 
> ```
> rbd: image img147: image uses unsupported features: 0x38
> ```
> 
> after disabling these features
> 
> ```
> for ((i = 1; i <= 150; i++)); do rbd feature disable replicapool/img$i object-map fast-diff deep-flatten; done
> ```
> 
> mapping was fast. it took max 10 sec to map few images
> 
> @nehaberry is it possible to test this in OCP?

@Madhu-1 first would need to understand the flow and the issue first :) . Maybe, we can share the cluster and try together sometime ?

**Comment by Madhu-1** [comment] 2019-08-05 05:59
@nehaberry sure

**Comment by idryomov** [comment] 2019-08-05 10:23
> if there is an error during the node staging (which means mounting rbd devices to a path fails) we unmap the rbd device

So you were seeing other, not related to "rbd map", failures during your test?  What was the cause?

> I got an error during mapping
> 
> ```
> rbd: image img147: image uses unsupported features: 0x38
> ```

Unless the image features are spelled out, "rbd create" creates images with "rbd_default_features", which includes object-map, fast-diff and deep-flatten.

**Comment by dillaman** [comment] 2019-08-05 13:20
> Unless the image features are spelled out, "rbd create" creates images with "rbd_default_features", which includes object-map, fast-diff and deep-flatten.

The `ceph-csi` RBD provisioner defaults to (and currently only supports) `layering` [1]

[1] https://github.com/ceph/ceph-csi/blob/f4c80dec9ab82d0239b2b89c9cb9669dad728f08/examples/rbd/storageclass.yaml#L25

**Comment by idryomov** [comment] 2019-08-05 13:25
@dillaman Madhu ran my bash script which does "rbd create".

**Comment by Madhu-1** [comment] 2019-08-08 12:56
the latest result for a different mount type

# Mounting PVC as block device 

For 50 pods to  up and running time taken is  1Min05Sec
max time taken for mapping is around  2 sec
max time  taken to mount  is 1 sec


# for file mount  with format type *xfs*

For 50 pods to  up and running time taken is  2Min20Sec
max time taken for mapping is around 8 sec
max time is taken for format and mount is 1m13s


# For file mount with format type *ext4*

For 50 pods to  up and running time taken is  5Min10Sec
max time taken for mapping is around 1m37sec
max time is taken for format and mount is 2m24s

**Comment by humblec** [comment] 2019-08-08 13:00
> the latest result for a different mount type
> # Mounting PVC as block device
> 
> For 50 pods to up and running time taken is 1Min05Sec
> max time taken for mapping is around 2 sec
> max time taken to mount is 1 sec


This is great result !!! 

> # for file mount with format type _xfs_
> 
> For 50 pods to up and running time taken is 2Min20Sec
> max time taken for mapping is around 8 sec
> max time is taken for format and mount is 1m13s

> # For file mount with format type _ext4_
> 
> For 50 pods to up and running time taken is 5Min10Sec
> max time taken for mapping is around 1m37sec
> max time is taken for format and mount is 2m24s

This ultimately shows a remarkable performance boost wrt filesystem we use for format. At present we are defaulting to `ext4` , may be this is the good time to think about using `xfs` or atleast make it as a choice by SC parameter.

**Comment by Madhu-1** [comment] 2019-08-08 13:03
@humblec yes as per the result. even  I went through rook code,  in rook flex storageclass its added xfs as fstype @travisn can  confirm it

**Comment by Madhu-1** [comment] 2019-08-08 13:04
https://github.com/rook/rook/pull/1928
https://github.com/rook/rook/issues/1280
leaving it here  for reference issue and PR in rook

**Comment by idryomov** [comment] 2019-08-09 11:17
I'm glad that our meeting bore some fruit ;)

Another thing for the future might be to pursue https://bugzilla.redhat.com/show_bug.cgi?id=1523885.  Looks like `formatAndMount()` still doesn't allow passing mkfs options.  `options []string` is for mount options:

https://github.com/ceph/ceph-csi/blob/44e807c36bb2e9e826a0f41f6af5b83a23079713/vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go#L428

rbd images are sparse, so there is no point in running discard on a freshly created image (be it mkfs.ext4 or mkfs.xfs).  This could further decrease the load on workers and shave off some time, especially for large volumes.

**Comment by Madhu-1** [comment] 2019-08-12 08:10
@idryomov agree, this applies for the fresh image, need to identify the image contains any data or not, if not we can set these options in csi node-plugin as a temp fix,

**Comment by humblec** [comment] 2019-08-12 08:22
> I'm glad that our meeting bore some fruit ;)
> 

Yeah , thanks for the discussion!

**Closed** 2019-08-13 15:19 UTC
Labels: Priority-0, bug, release-1.2.0

**Comment by ctheune** [comment] 2023-01-09 09:19
FYI, this might also have been related to this issue with the ceph-rbdnamer rules recommended upstream:
https://tracker.ceph.com/issues/58398

We tracked this down after reviewing our traces and the ones @dillaman and @idryomov where exchanging which looked exactly like the ones we got.
