### ISSUE TITLE
ceph fs subvolumegroup create myfs csi  hangs

### ISSUE THREAD

**Issue by yuchunyun** [ceph/ceph-csi#837] opened 2020-02-20 02:10 UTC
# Describe the bug #
command `ceph fs subvolumegroup create myfs csi` will hangs。This causes the creation of the PVC to fail

# Environment details #

- Image/version of Ceph CSI driver
```
{
    "mon": {
        "ceph version 14.2.5 (ad5bd132e1492173c85fda2cc863152730b16a92) nautilus (stable)": 3
    },
    "mgr": {
        "ceph version 14.2.5 (ad5bd132e1492173c85fda2cc863152730b16a92) nautilus (stable)": 1
    },
    "osd": {
        "ceph version 14.2.5 (ad5bd132e1492173c85fda2cc863152730b16a92) nautilus (stable)": 6
    },
    "mds": {
        "ceph version 14.2.5 (ad5bd132e1492173c85fda2cc863152730b16a92) nautilus (stable)": 2
    },
    "overall": {
        "ceph version 14.2.5 (ad5bd132e1492173c85fda2cc863152730b16a92) nautilus (stable)": 12
    }
}
```
- helm chart version
- Kubernetes cluster version
`1.17.2`
- Logs
csi-provisioner
```
I0219 05:34:26.068482       1 connection.go:180] GRPC call: /csi.v1.Controller/CreateVolume
I0219 05:34:26.068639       1 connection.go:181] GRPC request: {"capacity_range":{"required_bytes":4294967296},"name":"pvc-92b88c57-ae3f-4bc6-9dcf-890291ee1e71","parameters":{"clusterID":"c78af144-d24e-41ad-8870-bebe3d2ad9e7","fsName":"myfs","pool":"myfs_data"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":5}}]}
I0219 05:34:28.126294       1 leaderelection.go:282] successfully renewed lease zcloud/cephfs-csi-ceph-com
...
I0219 05:36:56.071933       1 connection.go:183] GRPC response: {}
I0219 05:36:56.073332       1 connection.go:184] GRPC error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
csi-cephfsplugin
```
I0219 05:34:26.973946       1 utils.go:157] ID: 52 Req-ID: pvc-d77b9cc1-8a3a-4f1b-b27f-f88b99ac233b GRPC call: /csi.v1.Controller/CreateVolume
I0219 05:34:26.974058       1 utils.go:158] ID: 52 Req-ID: pvc-d77b9cc1-8a3a-4f1b-b27f-f88b99ac233b GRPC request: {"capacity_range":{"required_bytes":4294967296},"name":"pvc-d77b9cc1-8a3a-4f1b-b27f-f88b99ac233b","parameters":{"clusterID":"ccddbd8f-ca7c-45cc-a3f3-7d6969dd7f10","fsName":"myfs"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["debug"]}},"access_mode":{"mode":5}}]}
I0219 05:34:26.980688       1 util.go:48] ID: 52 Req-ID: pvc-d77b9cc1-8a3a-4f1b-b27f-f88b99ac233b cephfs: EXEC ceph [-m 10.43.243.46:6789,10.43.118.135:6789,10.43.151.35:6789 --id admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs get myfs --format=json]
I0219 05:34:26.807141       1 util.go:48] ID: 52 Req-ID: pvc-d77b9cc1-8a3a-4f1b-b27f-f88b99ac233b cephfs: EXEC ceph [-m 10.43.243.46:6789,10.43.118.135:6789,10.43.151.35:6789 --id admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs ls --format=json]
I0219 05:34:28.457888       1 fsjournal.go:137] ID: 52 Req-ID: pvc-d77b9cc1-8a3a-4f1b-b27f-f88b99ac233b Generated Volume ID (0001-0024-ccddbd8f-ca7c-45cc-a3f3-7d6969dd7f10-0000000000000001-6e903286-52e8-11ea-b878-0a580a2a0114) and subvolume name (csi-vol-6e903286-52e8-11ea-b878-0a580a2a0114) for request name (pvc-d77b9cc1-8a3a-4f1b-b27f-f88b99ac233b)
I0219 05:34:29.458473       1 util.go:48] ID: 52 Req-ID: pvc-d77b9cc1-8a3a-4f1b-b27f-f88b99ac233b cephfs: EXEC ceph [fs subvolumegroup create myfs csi -m 10.43.243.46:6789,10.43.118.135:6789,10.43.151.35:6789 -c /etc/ceph/ceph.conf -n client.admin --keyfile=***stripped***]
I0219 05:34:41.742976       1 utils.go:157] ID: 53 GRPC call: /csi.v1.Identity/Probe
```
# Steps to reproduce #

I manually executed commands `ceph fs subvolumegroup create myfs csi` in the ceph cluster to get stuck。I delete the ceph cluster and re-execute it, the same result

**Comment by yuchunyun** [comment] 2020-02-20 02:12
@Madhu-1
@pohly 
@zmc 
@clkao @kshlm 
Can anyone help me
thanks

**Comment by yuchunyun** [comment] 2020-02-20 02:13
my ceph cluster is healthy
```
  cluster:
    id:     8483f86b-ddb9-452a-af0a-72b026ef4e85
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum c,a,b (age 34m)
    mgr: ceph-mgr-584b4b9494-whxtq(active, since 26m)
    mds: myfs:1 {0=ceph-mds-7b877f6c8f-vzl8t=up:active} 1 up:standby
    osd: 6 osds: 6 up (since 27m), 6 in (since 27m)
 
  data:
    pools:   2 pools, 300 pgs
    objects: 22 objects, 2.2 KiB
    usage:   6.0 GiB used, 108 GiB / 114 GiB avail
    pgs:     300 active+clean
```

**Comment by Madhu-1** [comment] 2020-02-20 03:11
cc @joscollin

**Comment by joscollin** [comment] 2020-02-20 03:36
@yuchunyun Could you please provide the ceph mgr logs to check?

**Comment by yuchunyun** [comment] 2020-02-20 03:47
```
2020-02-20 01:47:55.531 7f44cfa8c700  0 log_channel(audit) log [DBG] : from='client.4595 -' entity='client.admin' cmd=[{"prefix": "fs volume ls", "target": ["mgr", ""]}]: dispatch
2020-02-20 01:47:57.099 7f44cea8a700  0 log_channel(cluster) log [DBG] : pgmap v52: 300 pgs: 300 active+clean; 2.2 KiB data, 15 MiB used, 108 GiB / 114 GiB avail
2020-02-20 01:47:59.099 7f44cea8a700  0 log_channel(cluster) log [DBG] : pgmap v53: 300 pgs: 300 active+clean; 2.2 KiB data, 15 MiB used, 108 GiB / 114 GiB avail
2020-02-20 01:48:01.107 7f44cea8a700  0 log_channel(cluster) log [DBG] : pgmap v54: 300 pgs: 300 active+clean; 2.2 KiB data, 15 MiB used, 108 GiB / 114 GiB avail
2020-02-20 01:48:03.107 7f44cea8a700  0 log_channel(cluster) log [DBG] : pgmap v55: 300 pgs: 300 active+clean; 2.2 KiB data, 15 MiB used, 108 GiB / 114 GiB avail
2020-02-20 01:48:05.111 7f44cea8a700  0 log_channel(cluster) log [DBG] : pgmap v56: 300 pgs: 300 active+clean; 2.2 KiB data, 15 MiB used, 108 GiB / 114 GiB avail
2020-02-20 01:48:07.111 7f44cea8a700  0 log_channel(cluster) log [DBG] : pgmap v57: 300 pgs: 300 active+clean; 2.2 KiB data, 15 MiB used, 108 GiB / 114 GiB avail
2020-02-20 01:48:08.199 7f44cfa8c700  0 log_channel(audit) log [DBG] : from='client.4604 -' entity='client.admin' cmd=[{"prefix": "fs subvolumegroup create", "vol_name": "myfs", "target": ["mgr", ""], "group_name": "csi"}]: dispatch
2020-02-20 01:48:09.111 7f44cea8a700  0 log_channel(cluster) log [DBG] : pgmap v58: 300 pgs: 300 active+clean; 2.2 KiB data, 15 MiB used, 108 GiB / 114 GiB avail
2020-02-20 01:48:11.115 7f44cea8a700  0 log_channel(cluster) log [DBG] : pgmap v59: 300 pgs: 300 active+clean; 2.2 KiB data, 15 MiB used, 108 GiB / 114 GiB avail
2020-02-20 01:48:13.115 7f44cea8a700  0 log_channel(cluster) log [DBG] : pgmap v60: 300 pgs: 300 active+clean; 2.2 KiB data, 15 MiB used, 108 GiB / 114 GiB avail
```
Please ignore the time in the log

**Comment by joscollin** [comment] 2020-02-20 04:14
@yuchunyun And what is your analysis from those logs? What does it reveal to you?

**Comment by yuchunyun** [comment] 2020-02-20 04:18
@joscollin 
I can't see an exception from the log。
Only know that mgr has received the request, but where is the result?

**Comment by yuchunyun** [comment] 2020-02-20 04:24
@joscollin 
the auth for mgr is:
```
ceph auth get-or-create mgr.${MGR_NAME} mon 'allow profile mgr' osd 'allow *' mds 'allow *' -o /var/lib/ceph/mgr/ceph-${MGR_NAME}/keyring```
is there not enough authority?

**Comment by yuchunyun** [comment] 2020-02-20 05:52
@joscollin 
I have increased the permissions for mgr, but its log is still the same
```
mgr.ceph-mgr-584b4b9494-mwhq8
        key: AQCxHE5elMrBNxAAo4ICz4xImqXDWFGC1wVQIA==
        caps: [mds] allow *
        caps: [mgr] allow *
        caps: [mon] allow *
        caps: [osd] allow *
```

**Comment by joscollin** [comment] 2020-02-20 06:13
@yuchunyun Try to find what does the log says about the command `ceph fs subvolumegroup create myfs csi`. Is the subvolumegroup created in the volume?

**Comment by yuchunyun** [comment] 2020-02-20 06:16
There is nothing else in the  log. `ceph fs volume ls` or `ceph fs subvolumegroup ls myfs` will now become stuck

**Comment by joscollin** [comment] 2020-02-20 09:45
What is the output of `ceph fs status`?

**Comment by yuchunyun** [comment] 2020-02-20 09:54
```
myfs - 0 clients
====
+------+--------+---------------------------+---------------+-------+-------+
| Rank | State  |            MDS            |    Activity   |  dns  |  inos |
+------+--------+---------------------------+---------------+-------+-------+
|  0   | active | ceph-mds-845ccd9557-6mpth | Reqs:    0 /s |   10  |   13  |
+------+--------+---------------------------+---------------+-------+-------+
+---------------+----------+-------+-------+
|      Pool     |   type   |  used | avail |
+---------------+----------+-------+-------+
| myfs_metadata | metadata | 1024k | 51.1G |
|   myfs_data   |   data   |    0  | 51.1G |
+---------------+----------+-------+-------+
+---------------------------+
|        Standby MDS        |
+---------------------------+
| ceph-mds-845ccd9557-n4d2n |
+---------------------------+
```

**Comment by yuchunyun** [comment] 2020-02-20 09:58
@joscollin 
After I redeployed the ceph cluster, I was able to execute the `ceph fs status  ` command normally, but as soon as I executed `ceph fs subvolumegroup create myfs csi`, I would get stuck executing `ceph fs status` or `ceph fs volume ls`

**Comment by joscollin** [comment] 2020-02-20 11:33
@yuchunyun Can you upgrade to the latest ceph 14.2.7 and see if the problem persist?

**Comment by yuchunyun** [comment] 2020-02-20 13:20
I've been upgraded, but the problem is still there
```
[root@ceph-mgr-6d8c5bdd54-hszsl ceph]# ceph versions
{
    "mon": {
        "ceph version 14.2.7 (3d58626ebeec02d8385a4cefb92c6cbc3a45bfe8) nautilus (stable)": 3
    },
    "mgr": {
        "ceph version 14.2.7 (3d58626ebeec02d8385a4cefb92c6cbc3a45bfe8) nautilus (stable)": 1
    },
    "osd": {
        "ceph version 14.2.7 (3d58626ebeec02d8385a4cefb92c6cbc3a45bfe8) nautilus (stable)": 6
    },
    "mds": {
        "ceph version 14.2.7 (3d58626ebeec02d8385a4cefb92c6cbc3a45bfe8) nautilus (stable)": 2
    },
    "overall": {
        "ceph version 14.2.7 (3d58626ebeec02d8385a4cefb92c6cbc3a45bfe8) nautilus (stable)": 12
    }
}
[root@ceph-mgr-6d8c5bdd54-hszsl ceph]# ceph fs volume ls
[
  {
    "name": "myfs"
  }
]
[root@ceph-mgr-6d8c5bdd54-hszsl ceph]# ceph fs status   
myfs - 0 clients
====
+------+--------+---------------------------+---------------+-------+-------+
| Rank | State  |            MDS            |    Activity   |  dns  |  inos |
+------+--------+---------------------------+---------------+-------+-------+
|  0   | active | ceph-mds-76b4f74d48-qbr8p | Reqs:    0 /s |   10  |   13  |
+------+--------+---------------------------+---------------+-------+-------+
+---------------+----------+-------+-------+
|      Pool     |   type   |  used | avail |
+---------------+----------+-------+-------+
| myfs_metadata | metadata | 1024k | 51.1G |
|   myfs_data   |   data   |    0  | 51.1G |
+---------------+----------+-------+-------+
+---------------------------+
|        Standby MDS        |
+---------------------------+
| ceph-mds-76b4f74d48-pkj44 |
+---------------------------+
MDS version: ceph version 14.2.7 (3d58626ebeec02d8385a4cefb92c6cbc3a45bfe8) nautilus (stable)
```
`ceph fs subvolumegroup create myfs csi` stuck

**Comment by batrick** [comment] 2020-02-20 17:07
@yuchunyun please increase debugging on the mgr, retry, then post the logs.

````
ceph config set mgr debug_mgr 20
````

**Comment by joscollin** [comment] 2020-02-21 04:05
@batrick I think it is 20/20 by default. Anyway @yuchunyun you could check it `get`

**Comment by yuchunyun** [comment] 2020-02-21 05:06
@joscollin  @batrick 
I turn on debug and execute the command again
```
2020-02-21 00:37:34.633 7f4439226700  4 mgr.server _handle_command decoded 2
2020-02-21 00:37:34.633 7f4439226700  4 mgr.server _handle_command prefix=fs volume ls
2020-02-21 00:37:34.633 7f4439226700 10 mgr.server _allowed_command  client.admin capable
2020-02-21 00:37:34.633 7f4439226700  0 log_channel(audit) log [DBG] : from='client.4549 -' entity='client.admin' cmd=[{"prefix": "fs volume ls", "target": ["mgr", ""]}]: dispatch
2020-02-21 00:37:34.633 7f4439226700  4 mgr.server _handle_command passing through 2
2020-02-21 00:37:34.837 7f4438224700 10 mgr.server tick 
2020-02-21 00:37:34.837 7f4438224700 10 mgr update_delta_stats  v20366
2020-02-21 00:37:34.837 7f4438224700 10 mgr.server operator() 300 pgs: 300 active+clean; 2.2 KiB data, 14 MiB used, 108 GiB / 114 GiB avail
2020-02-21 00:37:34.837 7f4438224700 10 mgr.server operator() 0 health checks
2020-02-21 00:37:34.837 7f4438224700 20 mgr.server operator() health checks:
{}

2020-02-21 00:37:34.837 7f4438224700  0 log_channel(cluster) log [DBG] : pgmap v20366: 300 pgs: 300 active+clean; 2.2 KiB data, 14 MiB used, 108 GiB / 114 GiB avail
2020-02-21 00:37:34.837 7f4438224700 20 mgr.server send_report  + osd,0 SLOW_OPS(0|(0,0))
2020-02-21 00:37:34.837 7f4438224700 20 mgr.server send_report  + osd,0 PENDING_CREATING_PGS(0|(0,0))
2020-02-21 00:37:34.837 7f4438224700 20 mgr.server adjust_pgs 
2020-02-21 00:37:34.837 7f4438224700 10 mgr.server operator() creating_or_unknown 0 max_creating 1024 left 1024
2020-02-21 00:37:34.837 7f4438224700 20 mgr.server operator() misplaced_ratio 0 degraded_ratio 0 inactive_pgs_ratio 0 unknown_pgs_ratio 0; target_max_misplaced_ratio 0.05
2020-02-21 00:37:34.841 7f44488ae700 10 mgr tick tick
2020-02-21 00:37:34.841 7f44488ae700  4 mgr send_beacon active
2020-02-21 00:37:34.841 7f44488ae700 10 mgr send_beacon sending beacon as gid 4402
2020-02-21 00:37:35.541 7f44508be700 10 mgr.server ms_handle_authentication ms_handle_authentication new session 0x55e48cecdee0 con 0x55e48d7de000 entity mgr.ceph-mgr-58dbb9d74b-k4nqx addr 
2020-02-21 00:37:35.541 7f4439226700  4 mgr.server handle_open from 0x55e48d7de000  client,ceph-mgr-58dbb9d74b-k4nqx
2020-02-21 00:37:35.541 7f4439226700  4 mgr.server handle_report from 0x55e48d7de000 client,ceph-mgr-58dbb9d74b-k4nqx
2020-02-21 00:37:35.541 7f4439226700  4 mgr.server handle_report rejecting report from non-daemon client ceph-mgr-58dbb9d74b-k4nqx
2020-02-21 00:37:35.749 7f4433a1b700 20 mgr[rbd_support] PerfHandler: tick
2020-02-21 00:37:35.749 7f4433a1b700 10 ceph_option_get mgr_stats_period found: 5
2020-02-21 00:37:35.749 7f44331da700 20 mgr[rbd_support] TaskHandler: tick
2020-02-21 00:37:36.541 7f44518c0700 10 mgr.server ms_handle_authentication ms_handle_authentication new session 0x55e48cbff930 con 0x55e48db5ac00 entity mgr.ceph-mgr-58dbb9d74b-k4nqx addr 
2020-02-21 00:37:36.541 7f4439226700  4 mgr.server handle_open from 0x55e48db5ac00  client,ceph-mgr-58dbb9d74b-k4nqx
2020-02-21 00:37:36.541 7f4439226700  4 mgr.server handle_report from 0x55e48db5ac00 client,ceph-mgr-58dbb9d74b-k4nqx
2020-02-21 00:37:36.541 7f4439226700  4 mgr.server handle_report rejecting report from non-daemon client ceph-mgr-58dbb9d74b-k4nqx
2020-02-21 00:37:36.837 7f4438224700 10 mgr.server tick 
2020-02-21 00:37:36.837 7f4438224700 10 mgr update_delta_stats  v20367
2020-02-21 00:37:36.837 7f4438224700 10 mgr.server operator() 300 pgs: 300 active+clean; 2.2 KiB data, 14 MiB used, 108 GiB / 114 GiB avail
2020-02-21 00:37:36.837 7f4438224700 10 mgr.server operator() 0 health checks
2020-02-21 00:37:36.837 7f4438224700 20 mgr.server operator() health checks:
{}
```

However, I have good news. After I rebooted all nodes，redeploy ceph clusters and csi using containers, everything was back to normal.
My nodes used k8s1.13 before, but problems occurred after upgrading k8s1.17. After I restarted the nodes, the problem was resolved. I'm not sure if it's the k8s problem，why does it affect ceph

**Comment by joscollin** [comment] 2020-02-21 05:28
@yuchunyun You had a ceph upgrade, so you needed to restart the daemons. Good to know that the issue is resolved.

**Comment by yuchunyun** [comment] 2020-02-21 05:34
@joscollin 
thanks.
my ceph cluster is deployed in containers. I didn't understand why the k8s upgrade would affect the new ceph cluster (I didn't use the previous ceph, but redeployed one), so I restarted the physical machine and redeployed the ceph cluster in containers. And I still use ceph v14.2.4

**Comment by Madhu-1** [comment] 2020-02-25 05:29
@yuchunyun as this is nothing to do with ceph-csi, closing this one now. as this is more specific to the ceph cluster, if required we can open one in ceph?

**Closed by Madhu-1** 2020-02-25 05:29 UTC
Labels: cephfs
