### ISSUE TITLE
Revert code added to maintain cephfs mount cache on nodes

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#824] opened 2020-02-09 12:48 UTC
As functionality added by PR #282 for CephFS fuse mounts does not work as intended, from a code maintainability standpoint we should revert this commit or remove the added code.

**Comment by jianglingxia** [comment] 2020-02-10 07:38
if the #282  PR reverted ,the ceph csi driver daemonset plugin existed,caused the pod mount path transport endpoint is not connected error  problem can resolved? @ShyamsundarR 
thanks

**Comment by Madhu-1** [comment] 2020-02-10 07:39
it won't resolve any issue. this code is not working as expected am working on removing the code

**Comment by jianglingxia** [comment] 2020-02-10 08:01
@Madhu-1  really thanks, i want to know that the transport endpoint is not connected error ,the problem is cephfs-fuse client reason? not csi driver reason is right?

**Comment by Madhu-1** [comment] 2020-02-10 08:56
@jianglingxia see https://github.com/ceph/ceph-csi/issues/703#issuecomment-557520551 for the more detailed explanation

**Comment by Madhu-1** [comment] 2020-02-25 05:31
closing this one as #825 is merged

**Closed by Madhu-1** 2020-02-25 05:31 UTC

**Comment by huaizong** [comment] 2020-04-12 09:12
@ShyamsundarR  @jianglingxia  As PR #282 describe,  mount cache only work if Pod can restart when csi container exit, it may trigger  by health probe check or other similar technology. 

If Pod not check mount path, mount cache can not help in thhe scenarios. 

** NoGoal **

***Pod should exit and restart*** when csi plugin pod exit and mount point lost. if pod not exit will get error of transport endpoint is not connected.
