### ISSUE TITLE
Storage Class should be included with the helm charts

### ISSUE THREAD

**Issue by ba-work** [ceph/ceph-csi#1765] opened 2020-12-04 17:32 UTC
# Describe the feature you'd like to have #

What new functionality do you want?
- I would like to have to the ability to deploy a Storage Class when using the helm chart.
- This means the helm chart should handle creating the csi-<rbd/cephfs>-secret as well.

# What is the value to the end user? (why is it a priority?) #

How would the end user gain value from having this feature?
- The user would be able to deploy their desired csi quicker and easier. 
- There is no reason not to include both the secret and storage creation as csi is useless without a storage class. This should be included in both helm charts, other csi helm charts include a retain and a delete version of storage class.

# How will we know we have a good solution? (acceptance criteria) #

Add a list of criteria that should be met for this feature to be useful
- I should be able to apply the helm charts and then be able to `kubectl get storageclass -A` and see the respective storage classes

# Additional context #

- All of the documentation around this csi includes steps for creation the secret and the storage class. This should be included in the helm chart

**Comment by Madhu-1** [comment] 2020-12-07 07:37
@ba-work Thanks for creating the issue. This looks to be the duplicate of https://github.com/ceph/ceph-csi/issues/1483. closing it for the same reason, please feel free to reopen if its not.

**Closed by Madhu-1** 2020-12-07 07:37 UTC
