### ISSUE TITLE
provisioner CreateVolume endless loop

### ISSUE THREAD

**Issue by muhlba91** [ceph/ceph-csi#284] opened 2019-03-26 13:10 UTC
I have deployed the CephFS provisioner according to `deploy/cephfs/kubernetes` of the `csi-v1.0` branch (Ceph deployed with Rook). After the driver starts, I created a simple PVC and the provisioner picks it up.
However, it starts an endless loop calling `CreateVolume` over and over again:
```
I0326 13:05:12.634989       1 utils.go:105] GRPC call: /csi.v1.Controller/CreateVolume
I0326 13:05:12.635005       1 utils.go:106] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-56ce1ad0-4fc7-11e9-85e4-96000020c040","parameters":{"monitors":"rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790","pool":"ceph-fs-data0","provisionVolume":"true"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":5}}]}
I0326 13:05:12.636094       1 hashed.go:47] hashedKeyMutex.LockKey(...) called for id "csi-cephfs-pvc-56ce1ad0-4fc7-11e9-85e4-96000020c040"
I0326 13:05:12.636102       1 hashed.go:49] hashedKeyMutex.LockKey(...) for id "csi-cephfs-pvc-56ce1ad0-4fc7-11e9-85e4-96000020c040" completed.
I0326 13:05:12.636240       1 util.go:60] cephfs: EXEC ceph-fuse [/var/lib/kubelet/plugins//controller/volumes/root-csi-cephfs-pvc-56ce1ad0-4fc7-11e9-85e4-96000020c040 -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790 -c /etc/ceph/ceph.conf -n client.provisioner --key=***stripped*** -r / -o nonempty]
I0326 13:05:17.807048       1 volume.go:69] cephfs: volume csi-cephfs-pvc-56ce1ad0-4fc7-11e9-85e4-96000020c040 already exists, skipping creation
I0326 13:05:17.807099       1 util.go:60] cephfs: EXEC umount [/var/lib/kubelet/plugins//controller/volumes/root-csi-cephfs-pvc-56ce1ad0-4fc7-11e9-85e4-96000020c040]
I0326 13:05:17.844416       1 util.go:60] cephfs: EXEC ceph [-m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790 -n client.provisioner --key=***stripped*** -c /etc/ceph/ceph.conf -f json auth get-or-create client.user-csi-cephfs-pvc-56ce1ad0-4fc7-11e9-85e4-96000020c040 mds allow rw path=/csi-volumes/csi-cephfs-pvc-56ce1ad0-4fc7-11e9-85e4-96000020c040 mon allow r osd allow rw pool=ceph-fs-data0 namespace=ns-csi-cephfs-pvc-56ce1ad0-4fc7-11e9-85e4-96000020c040]
I0326 13:05:23.169340       1 controllerserver.go:87] cephfs: successfully created volume csi-cephfs-pvc-56ce1ad0-4fc7-11e9-85e4-96000020c040
I0326 13:05:23.204812       1 k8scmcache.go:126] k8s-cm-cache: configmap csi-cephfs-pvc-56ce1ad0-4fc7-11e9-85e4-96000020c040 already exists, skipping configmap creation
I0326 13:05:23.204825       1 hashed.go:54] hashedKeyMutex.UnlockKey(...) called for id "csi-cephfs-pvc-56ce1ad0-4fc7-11e9-85e4-96000020c040"
I0326 13:05:23.204832       1 hashed.go:56] hashedKeyMutex.UnlockKey(...) for id "csi-cephfs-pvc-56ce1ad0-4fc7-11e9-85e4-96000020c040" completed.
I0326 13:05:23.204846       1 utils.go:111] GRPC response: {"volume":{"capacity_bytes":1073741824,"volume_context":{"monitors":"rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790","pool":"ceph-fs-data0","provisionVolume":"true"},"volume_id":"csi-cephfs-pvc-56ce1ad0-4fc7-11e9-85e4-96000020c040"}}
I0326 13:06:38.494444       1 utils.go:105] GRPC call: /csi.v1.Identity/GetPluginCapabilities
I0326 13:06:38.494513       1 utils.go:106] GRPC request: {}
I0326 13:06:38.494935       1 utils.go:111] GRPC response: {"capabilities":[{"Type":{"Service":{"type":1}}}]}
I0326 13:06:38.496567       1 utils.go:105] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I0326 13:06:38.496576       1 utils.go:106] GRPC request: {}
I0326 13:06:38.496866       1 controllerserver-default.go:55] Using default ControllerGetCapabilities
I0326 13:06:38.496873       1 utils.go:111] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}}]}
I0326 13:06:38.499209       1 utils.go:105] GRPC call: /csi.v1.Identity/GetPluginInfo
I0326 13:06:38.499229       1 utils.go:106] GRPC request: {}
I0326 13:06:38.499541       1 identityserver-default.go:34] Using default GetPluginInfo
I0326 13:06:38.499546       1 utils.go:111] GRPC response: {"name":"cephfs.csi.ceph.com","vendor_version":"1.0.0"}
I0326 13:06:38.508145       1 utils.go:105] GRPC call: /csi.v1.Controller/CreateVolume
I0326 13:06:38.508155       1 utils.go:106] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-fda02c2a-4fc7-11e9-85e4-96000020c040","parameters":{"monitors":"rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790","pool":"ceph-fs-data0","provisionVolume":"true"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":5}}]}
I0326 13:06:38.509749       1 hashed.go:47] hashedKeyMutex.LockKey(...) called for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040"
I0326 13:06:38.509765       1 hashed.go:49] hashedKeyMutex.LockKey(...) for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040" completed.
I0326 13:06:38.509913       1 util.go:60] cephfs: EXEC ceph-fuse [/var/lib/kubelet/plugins//controller/volumes/root-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790 -c /etc/ceph/ceph.conf -n client.provisioner --key=***stripped*** -r / -o nonempty]
I0326 13:06:43.904271       1 util.go:60] cephfs: EXEC setfattr [-n ceph.quota.max_bytes -v 1073741824 /var/lib/kubelet/plugins/controller/volumes/root-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040/csi-volumes/csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040-creating]
I0326 13:06:43.929341       1 util.go:60] cephfs: EXEC setfattr [-n ceph.dir.layout.pool -v ceph-fs-data0 /var/lib/kubelet/plugins/controller/volumes/root-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040/csi-volumes/csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040-creating]
I0326 13:06:43.954203       1 util.go:60] cephfs: EXEC setfattr [-n ceph.dir.layout.pool_namespace -v ns-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 /var/lib/kubelet/plugins/controller/volumes/root-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040/csi-volumes/csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040-creating]
I0326 13:06:43.993666       1 util.go:60] cephfs: EXEC umount [/var/lib/kubelet/plugins//controller/volumes/root-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040]
I0326 13:06:44.048055       1 util.go:60] cephfs: EXEC ceph [-m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790 -n client.provisioner --key=***stripped*** -c /etc/ceph/ceph.conf -f json auth get-or-create client.user-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 mds allow rw path=/csi-volumes/csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 mon allow r osd allow rw pool=ceph-fs-data0 namespace=ns-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040]
I0326 13:06:49.436345       1 controllerserver.go:87] cephfs: successfully created volume csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040
I0326 13:06:49.503059       1 k8scmcache.go:154] k8s-cm-cache: configmap csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 successfully created
I0326 13:06:49.503076       1 hashed.go:54] hashedKeyMutex.UnlockKey(...) called for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040"
I0326 13:06:49.503085       1 hashed.go:56] hashedKeyMutex.UnlockKey(...) for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040" completed.
I0326 13:06:49.503093       1 utils.go:111] GRPC response: {"volume":{"capacity_bytes":1073741824,"volume_context":{"monitors":"rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790","pool":"ceph-fs-data0","provisionVolume":"true"},"volume_id":"csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040"}}
I0326 13:06:53.509025       1 utils.go:105] GRPC call: /csi.v1.Controller/CreateVolume
I0326 13:06:53.509043       1 utils.go:106] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-fda02c2a-4fc7-11e9-85e4-96000020c040","parameters":{"monitors":"rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790","pool":"ceph-fs-data0","provisionVolume":"true"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":5}}]}
I0326 13:06:53.510860       1 hashed.go:47] hashedKeyMutex.LockKey(...) called for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040"
I0326 13:06:53.510871       1 hashed.go:49] hashedKeyMutex.LockKey(...) for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040" completed.
I0326 13:06:53.511012       1 util.go:60] cephfs: EXEC ceph-fuse [/var/lib/kubelet/plugins//controller/volumes/root-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790 -c /etc/ceph/ceph.conf -n client.provisioner --key=***stripped*** -r / -o nonempty]
I0326 13:06:58.643043       1 volume.go:69] cephfs: volume csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 already exists, skipping creation
I0326 13:06:58.643106       1 util.go:60] cephfs: EXEC umount [/var/lib/kubelet/plugins//controller/volumes/root-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040]
I0326 13:06:58.680776       1 util.go:60] cephfs: EXEC ceph [-m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790 -n client.provisioner --key=***stripped*** -c /etc/ceph/ceph.conf -f json auth get-or-create client.user-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 mds allow rw path=/csi-volumes/csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 mon allow r osd allow rw pool=ceph-fs-data0 namespace=ns-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040]
I0326 13:07:04.009169       1 controllerserver.go:87] cephfs: successfully created volume csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040
I0326 13:07:04.050617       1 k8scmcache.go:126] k8s-cm-cache: configmap csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 already exists, skipping configmap creation
I0326 13:07:04.050631       1 hashed.go:54] hashedKeyMutex.UnlockKey(...) called for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040"
I0326 13:07:04.050640       1 hashed.go:56] hashedKeyMutex.UnlockKey(...) for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040" completed.
I0326 13:07:04.050648       1 utils.go:111] GRPC response: {"volume":{"capacity_bytes":1073741824,"volume_context":{"monitors":"rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790","pool":"ceph-fs-data0","provisionVolume":"true"},"volume_id":"csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040"}}
I0326 13:07:09.509910       1 utils.go:105] GRPC call: /csi.v1.Controller/CreateVolume
I0326 13:07:09.509927       1 utils.go:106] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-fda02c2a-4fc7-11e9-85e4-96000020c040","parameters":{"monitors":"rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790","pool":"ceph-fs-data0","provisionVolume":"true"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":5}}]}
I0326 13:07:09.511038       1 hashed.go:47] hashedKeyMutex.LockKey(...) called for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040"
I0326 13:07:09.511050       1 hashed.go:49] hashedKeyMutex.LockKey(...) for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040" completed.
I0326 13:07:09.511207       1 util.go:60] cephfs: EXEC ceph-fuse [/var/lib/kubelet/plugins//controller/volumes/root-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790 -c /etc/ceph/ceph.conf -n client.provisioner --key=***stripped*** -r / -o nonempty]
I0326 13:07:14.651792       1 volume.go:69] cephfs: volume csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 already exists, skipping creation
I0326 13:07:14.651840       1 util.go:60] cephfs: EXEC umount [/var/lib/kubelet/plugins//controller/volumes/root-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040]
I0326 13:07:14.690228       1 util.go:60] cephfs: EXEC ceph [-m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790 -n client.provisioner --key=***stripped*** -c /etc/ceph/ceph.conf -f json auth get-or-create client.user-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 mds allow rw path=/csi-volumes/csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 mon allow r osd allow rw pool=ceph-fs-data0 namespace=ns-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040]
I0326 13:07:20.014297       1 controllerserver.go:87] cephfs: successfully created volume csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040
I0326 13:07:20.048213       1 k8scmcache.go:126] k8s-cm-cache: configmap csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 already exists, skipping configmap creation
I0326 13:07:20.048230       1 hashed.go:54] hashedKeyMutex.UnlockKey(...) called for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040"
I0326 13:07:20.048250       1 hashed.go:56] hashedKeyMutex.UnlockKey(...) for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040" completed.
I0326 13:07:20.048269       1 utils.go:111] GRPC response: {"volume":{"capacity_bytes":1073741824,"volume_context":{"monitors":"rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790","pool":"ceph-fs-data0","provisionVolume":"true"},"volume_id":"csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040"}}
I0326 13:07:26.711103       1 utils.go:105] GRPC call: /csi.v1.Controller/CreateVolume
I0326 13:07:26.711118       1 utils.go:106] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-fda02c2a-4fc7-11e9-85e4-96000020c040","parameters":{"monitors":"rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790","pool":"ceph-fs-data0","provisionVolume":"true"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":5}}]}
I0326 13:07:26.712839       1 hashed.go:47] hashedKeyMutex.LockKey(...) called for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040"
I0326 13:07:26.712849       1 hashed.go:49] hashedKeyMutex.LockKey(...) for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040" completed.
I0326 13:07:26.712977       1 util.go:60] cephfs: EXEC ceph-fuse [/var/lib/kubelet/plugins//controller/volumes/root-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790 -c /etc/ceph/ceph.conf -n client.provisioner --key=***stripped*** -r / -o nonempty]
I0326 13:07:31.849385       1 volume.go:69] cephfs: volume csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 already exists, skipping creation
I0326 13:07:31.849438       1 util.go:60] cephfs: EXEC umount [/var/lib/kubelet/plugins//controller/volumes/root-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040]
I0326 13:07:31.887601       1 util.go:60] cephfs: EXEC ceph [-m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790 -n client.provisioner --key=***stripped*** -c /etc/ceph/ceph.conf -f json auth get-or-create client.user-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 mds allow rw path=/csi-volumes/csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 mon allow r osd allow rw pool=ceph-fs-data0 namespace=ns-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040]
I0326 13:07:37.213584       1 controllerserver.go:87] cephfs: successfully created volume csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040
I0326 13:07:37.256093       1 k8scmcache.go:126] k8s-cm-cache: configmap csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 already exists, skipping configmap creation
I0326 13:07:37.256111       1 hashed.go:54] hashedKeyMutex.UnlockKey(...) called for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040"
I0326 13:07:37.256118       1 hashed.go:56] hashedKeyMutex.UnlockKey(...) for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040" completed.
I0326 13:07:37.256124       1 utils.go:111] GRPC response: {"volume":{"capacity_bytes":1073741824,"volume_context":{"monitors":"rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790","pool":"ceph-fs-data0","provisionVolume":"true"},"volume_id":"csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040"}}
I0326 13:07:45.351879       1 utils.go:105] GRPC call: /csi.v1.Controller/CreateVolume
I0326 13:07:45.351896       1 utils.go:106] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-fda02c2a-4fc7-11e9-85e4-96000020c040","parameters":{"monitors":"rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790","pool":"ceph-fs-data0","provisionVolume":"true"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":5}}]}
I0326 13:07:45.353017       1 hashed.go:47] hashedKeyMutex.LockKey(...) called for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040"
I0326 13:07:45.353027       1 hashed.go:49] hashedKeyMutex.LockKey(...) for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040" completed.
I0326 13:07:45.353172       1 util.go:60] cephfs: EXEC ceph-fuse [/var/lib/kubelet/plugins//controller/volumes/root-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790 -c /etc/ceph/ceph.conf -n client.provisioner --key=***stripped*** -r / -o nonempty]
I0326 13:07:50.490417       1 volume.go:69] cephfs: volume csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 already exists, skipping creation
I0326 13:07:50.490500       1 util.go:60] cephfs: EXEC umount [/var/lib/kubelet/plugins//controller/volumes/root-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040]
I0326 13:07:50.528508       1 util.go:60] cephfs: EXEC ceph [-m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790 -n client.provisioner --key=***stripped*** -c /etc/ceph/ceph.conf -f json auth get-or-create client.user-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 mds allow rw path=/csi-volumes/csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 mon allow r osd allow rw pool=ceph-fs-data0 namespace=ns-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040]
I0326 13:07:55.912276       1 controllerserver.go:87] cephfs: successfully created volume csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040
I0326 13:07:55.947125       1 k8scmcache.go:126] k8s-cm-cache: configmap csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 already exists, skipping configmap creation
I0326 13:07:55.947146       1 hashed.go:54] hashedKeyMutex.UnlockKey(...) called for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040"
I0326 13:07:55.947153       1 hashed.go:56] hashedKeyMutex.UnlockKey(...) for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040" completed.
I0326 13:07:55.947159       1 utils.go:111] GRPC response: {"volume":{"capacity_bytes":1073741824,"volume_context":{"monitors":"rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790","pool":"ceph-fs-data0","provisionVolume":"true"},"volume_id":"csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040"}}
I0326 13:08:05.720526       1 utils.go:105] GRPC call: /csi.v1.Controller/CreateVolume
I0326 13:08:05.720546       1 utils.go:106] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-fda02c2a-4fc7-11e9-85e4-96000020c040","parameters":{"monitors":"rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790","pool":"ceph-fs-data0","provisionVolume":"true"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":5}}]}
I0326 13:08:05.721709       1 hashed.go:47] hashedKeyMutex.LockKey(...) called for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040"
I0326 13:08:05.721717       1 hashed.go:49] hashedKeyMutex.LockKey(...) for id "csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040" completed.
I0326 13:08:05.721850       1 util.go:60] cephfs: EXEC ceph-fuse [/var/lib/kubelet/plugins//controller/volumes/root-csi-cephfs-pvc-fda02c2a-4fc7-11e9-85e4-96000020c040 -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790 -c /etc/ceph/ceph.conf -n client.provisioner --key=***stripped*** -r / -o nonempty]
```

I can confirm that the provisioner successfully created one client (`ceph auth ls`) and one volume (directory) in the Ceph filesystem.

**Comment by gman0** [comment] 2019-03-26 13:58
This is expected behavior for now. There are a few changes planned that should improve the performance.

**Comment by ShyamsundarR** [comment] 2019-03-26 14:04
> This is expected behavior for now. There are a few changes planned that should improve the performance.

Ah! @gman0 so the 11 seconds to respond to the request is causing the driver to reject the response (due to some timeout?) and retry? Is that what is happening here?

**Comment by gman0** [comment] 2019-03-26 14:13
Afaik, the rpc on external-provisioner's side times out and retries. https://github.com/ceph/ceph-csi/issues/279 will take care of those timeouts, https://github.com/ceph/ceph-csi/issues/269 will save some load on repeatedly mounting cephfs root.

**Comment by muhlba91** [comment] 2019-03-26 14:40
@gman0 when can we expect a release taking care of those issues?
Atm, this prevents creating any PVC at all since even though the volume gets created in Ceph it's not bound and neither registered as a volume in Kubernetes.

**Comment by ShyamsundarR** [comment] 2019-03-26 14:50
@muhlba91 I would try adding a higher operation timeout for the driver in the interim to overcome the problem. IOW, use the `operationtimeout` option and move it to 20 seconde instead of 10 seconds which is the [default](https://github.com/kubernetes-csi/external-provisioner/blob/41036d7a3f8a5dae7aa48ac33131b44958fb0cf6/cmd/csi-provisioner/csi-provisioner.go#L59) for the driver.

A patch to the provisioner deployment [file](https://github.com/ceph/ceph-csi/blob/ff7d649c9dc9667baf2f1d27f358193a43cee162/deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml#L1) would look as follows (NOTE: NOT tested by me):
```
diff --git a/deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml b/deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
index af596293..ba56141d 100644
--- a/deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
+++ b/deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml
@@ -32,6 +32,7 @@ spec:
           args:
             - "--csi-address=$(ADDRESS)"
             - "--v=5"
+            - "--operationtimeout=20"
           env:
             - name: ADDRESS
               value: unix:///csi/csi-provisioner.sock
```

**Comment by gman0** [comment] 2019-03-26 16:04
@muhlba91 none? Uff... I'll try to push a PR this weekend, hopefully speeding things up at least a bit. What @ShyamsundarR suggested could help.

**Comment by muhlba91** [comment] 2019-03-26 16:17
@gman0 no, no PVC gets created and bound at all. For every PVC I try to create, I end up in this loop.

@ShyamsundarR the provisioner doesn‘t accept this command line argument. I end up with a crashing pod throwing the error it‘s an unknown command line argument.

**Comment by gman0** [comment] 2019-03-26 17:13
@muhlba91 

According to https://github.com/kubernetes-csi/external-provisioner/blob/41036d7a3f8a5dae7aa48ac33131b44958fb0cf6/cmd/csi-provisioner/csi-provisioner.go#L59

it should be just `timeout`, not `operationtimeout`.

**Comment by ShyamsundarR** [comment] 2019-03-26 17:46
> @muhlba91
> 
> According to https://github.com/kubernetes-csi/external-provisioner/blob/41036d7a3f8a5dae7aa48ac33131b44958fb0cf6/cmd/csi-provisioner/csi-provisioner.go#L59
> 
> it should be just `timeout`, not `operationtimeout`.

Yes, my mistake, confused the variable name with the option name. Please try `timeout` instead. Thanks @gman0 for catching that.

**Comment by muhlba91** [comment] 2019-03-27 06:13
@ShyamsundarR I think this change is not in a release yet and I get the same error as before when using `operationtimeout`.

The commit adding this timeout is https://github.com/kubernetes-csi/external-provisioner/commit/45a92e290be317396c3c8f5b67a842fad85822f6#diff-38b23914da9991d96c9ec4fc3c2525aa but all releases are from December (https://github.com/kubernetes-csi/external-provisioner/releases).

**Comment by Madhu-1** [comment] 2019-07-16 14:11
this is fixed in https://github.com/ceph/ceph-csi/pull/443, closing this one.
please reopen if the issue persists

**Closed by Madhu-1** 2019-07-16 14:11 UTC
