### ISSUE TITLE
Add periodic logs for CLI/commands that hang during execution, to aid better troubleshooting

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#847] opened 2020-02-29 14:00 UTC
There are times when invoked CLIs do not return in time, or at all. Usually this is due to  incorrectly configured or unreachable MONs, or at times due to sending a command to an unhealthy Ceph cluster.

The logs for such instances, need to be investigated to determine which CLI may have failed, looking at other logs for the gRPC request that have been written.

It would be better if every CLI or command invocation, starts a timer and prints out something akin to "waiting for command X to complete" based on and exponential timer expiration. This would help troubleshooting and determining issues where such hangs are observed.

There was a prior attempt to cancel outstanding CLIs, if they did not return in time #194 this request is to instead log the same, for ease of troubleshooting.

Thanks to @phlogistonjohn for suggesting the enhancement.

**Comment by phlogistonjohn** [comment] 2020-03-06 14:59
I should note that in principle this can apply to either command line based actions or in-process actions via function calls. The trick will be figuring out what kind of layering and granularity you want.

**Comment by Madhu-1** [comment] 2020-03-12 09:48
will this make sense after migrating to go-ceph bindings?

**Comment by ShyamsundarR** [comment] 2020-03-13 23:52
> will this be helpful after migrating to go-ceph bindings?

It would be helpful eitherway, BUT as the move to go-ceph bindings is so close, it can be picked up post the same IMO.

**Comment by nixpanic** [comment] 2020-07-31 11:43
Duplicate of #694 and #1216

**Closed by nixpanic** 2020-07-31 11:43 UTC
Labels: enhancement
