### ISSUE TITLE
ceph-csi v3.4.0 may always use krbd thought I configured mounter 

### ISSUE THREAD

**Issue by abmybgx** [ceph/ceph-csi#2465] opened 2021-08-31 11:26 UTC
# Describe the bug #

I just configured storageclass with "mounter: rbd-nbd". But I got below error, seems it also used krbd as device-type.
![image](https://user-images.githubusercontent.com/34848440/131493557-62b0b590-4f0d-421f-be0a-acbcc417e43d.png)
![image](https://user-images.githubusercontent.com/34848440/131493430-8db0b9f4-134c-44bc-a126-465111067b4c.png)

# Environment details #

- Image/version of Ceph CSI driver : v3.4.0
- Helm chart version : 3.4.0-canary
- Kernel version : Linux SZ-IDC-172-20-56-50 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : rbd-nbd
- Kubernetes cluster version : v1.18.9
- Ceph cluster version : v1.16.5

# Steps to reproduce #

1. helm install ceph-csi-rbd ceph-csi-rbd
2. use volumeClaimTemplates in a statefulset to use the storageclass
3. kubectl describe xxx

# Actual results #

![image](https://user-images.githubusercontent.com/34848440/131493430-8db0b9f4-134c-44bc-a126-465111067b4c.png)

# Expected behavior #

use nbd to mount.

 # Other

I used ceph-csi v1.2.2 before, it's usable.

**Comment by Madhu-1** [comment] 2021-09-03 06:05
@abmybgx please provide the logs from the csi-rbdplugin container from the node where the mount is failing.

**Comment by abmybgx** [comment] 2021-09-03 06:11
> @Madhu-1 

![image](https://user-images.githubusercontent.com/34848440/131959069-2f543d99-d8d8-4a3c-8855-e42b63a8020c.png)

**Comment by Madhu-1** [comment] 2021-09-03 06:14
can you please check `/sys/module/nbd` path present on the node if not can be please run `modprobe nbd`  and `rbd-nbd --version` on the node and see if rbd-nbd is present?

**Comment by abmybgx** [comment] 2021-09-03 06:26
![image](https://user-images.githubusercontent.com/34848440/131960061-92a0aa70-c64c-49f1-a7d3-4ed99670f99b.png)
![image](https://user-images.githubusercontent.com/34848440/131960138-1b51f774-9bb0-4399-a2ad-368f8e474c0d.png)

**Comment by Madhu-1** [comment] 2021-09-03 06:27
@abmybgx the above confirms that you don't have rbd-nbd available on your node. because of that krbd is tried by default

**Comment by Madhu-1** [comment] 2021-09-03 06:29
https://github.com/ceph/ceph-csi/blob/8fc7db8d80c06acd2d2c54620849e223b87590f8/internal/rbd/rbd_attach.go#L196-L216 this check is failing on your clusters. you should be able to  see the logs when  cephcsi start

**Comment by Madhu-1** [comment] 2021-09-03 06:32
> @abmybgx the above confirms that you don't have rbd-nbd available on your node. because of that krbd is tried by default

apologies for this one. can you please below the output from the node?

```
# modrobe nbd
# lsmod | grep nbd
```

**Comment by abmybgx** [comment] 2021-09-03 06:38
![image](https://user-images.githubusercontent.com/34848440/131960988-229d679e-8b83-47d8-849b-c8bdd2ce33d9.png)
Maybe the server was installed nbd before, but is unusable now, I'll reinstall it and have a check

**Comment by Madhu-1** [comment] 2021-09-03 06:39
Thanks for providing the information, in that case, am closing this issue as not a bug. please feel free to open a new issue if you face any issues again.

**Closed as completed by Madhu-1** 2021-09-03 06:39 UTC
Labels: bug, component/rbd, Logs-needed
