### ISSUE TITLE
Problems with creating and attaching pvc cephfs

### ISSUE THREAD

**Issue by kuhar2007** [ceph/ceph-csi#3428] opened 2022-10-12 13:15 UTC
I redeployed one from five ceph nodes (**not rook**).
4 nodes have ceph v14.210 and the last node got v 14.2.22 after redeploy.

I updated ceph csi to last version 3.7. I think that will fix my problem, but no.

When I try create cephfs volume, I have next errors from pvc:
`Events:
  Type     Reason                Age              From                                                                                                   Message
  ----     ------                ----             ----                                                                                                   -------
  Normal   ExternalProvisioning  5s               persistentvolume-controller                                                                            waiting for a volume to be created, either by external provisioner "cephfs.csi.ceph.com" or manually created by system administrator
  Warning  ProvisioningFailed    5s               cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-f69755684-gv9kz_8262deb3-dcc7-4463-8a30-b124679da43a  failed to provision volume with StorageClass "cephfs": rpc error: code = Internal desc = rados: ret=-2, No such file or directory: "error in open /volumes/_/volumes/kubernetes/test-k8s-volumes:csi-vol-2c2275d7-4a2e-11ed-87cf-62cdbefcaf73.meta"
  Warning  ProvisioningFailed    3s               cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-f69755684-gv9kz_8262deb3-dcc7-4463-8a30-b124679da43a  failed to provision volume with StorageClass "cephfs": rpc error: code = Internal desc = rados: ret=-2, No such file or directory: "error in open /volumes/_/volumes/kubernetes/test-k8s-volumes:csi-vol-2c7af0ce-4a2e-11ed-87cf-62cdbefcaf73.meta"
  Warning  ProvisioningFailed    2s               cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-f69755684-gv9kz_8262deb3-dcc7-4463-8a30-b124679da43a  failed to provision volume with StorageClass "cephfs": rpc error: code = Internal desc = rados: ret=-2, No such file or directory: "error in open /volumes/_/volumes/kubernetes/test-k8s-volumes:csi-vol-2d993fe4-4a2e-11ed-87cf-62cdbefcaf73.meta"
  Normal   Provisioning          0s (x4 over 5s)  cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-f69755684-gv9kz_8262deb3-dcc7-4463-8a30-b124679da43a  External provisioner is provisioning volume for claim "ceph-csi/test-volume"`

Logs from cephfs-provisioner here:
```
I1012 10:33:38.762362       1 leaderelection.go:278] successfully renewed lease ceph-csi/cephfs-csi-ceph-com
I1012 10:33:39.205952       1 controller.go:1337] provision "ceph-csi/test-volume" class "cephfs": started
I1012 10:33:39.207364       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"ceph-csi", Name:"test-volume", UID:"345ad256-5cef-4b48-a2ec-872357ce8a88", APIVersion:"v1", ResourceVersion:"115056323", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "ceph-csi/test-volume"
I1012 10:33:39.212151       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateVolume
I1012 10:33:39.212192       1 connection.go:184] GRPC request: {"capacity_range":{"required_bytes":53687091200},"name":"pvc-345ad256-5cef-4b48-a2ec-872357ce8a88","parameters":{"clusterID":"<cluster-id>","[csi.storage.k8s.io/pv/name](http://csi.storage.k8s.io/pv/name)":"pvc-345ad256-5cef-4b48-a2ec-872357ce8a88","[csi.storage.k8s.io/pvc/name](http://csi.storage.k8s.io/pvc/name)":"test-volume","[csi.storage.k8s.io/pvc/namespace](http://csi.storage.k8s.io/pvc/namespace)":"ceph-csi","fsName":"cephfs"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"mount_flags":["noatime"]}},"access_mode":{"mode":5}}]}
I1012 10:33:39.620805       1 connection.go:186] GRPC response: {}
I1012 10:33:39.621159       1 connection.go:187] GRPC error: rpc error: code = Internal desc = rados: ret=-2, No such file or directory: "error in open /volumes/_/volumes/kubernetes/test-k8s-volumes:csi-vol-55c8b492-4a19-11ed-860d-7258ef3a62b4.meta"
I1012 10:33:39.621317       1 controller.go:788] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = Internal desc = rados: ret=-2, No such file or directory: "error in open /volumes/_/volumes/kubernetes/test-k8s-volumes:csi-vol-55c8b492-4a19-11ed-860d-7258ef3a62b4.meta"
I1012 10:33:39.622679       1 controller.go:1075] Final error received, removing PVC 345ad256-5cef-4b48-a2ec-872357ce8a88 from claims in progress
W1012 10:33:39.622929       1 controller.go:934] Retrying syncing claim "345ad256-5cef-4b48-a2ec-872357ce8a88", failure 5
E1012 10:33:39.623086       1 controller.go:957] error syncing claim "345ad256-5cef-4b48-a2ec-872357ce8a88": failed to provision volume with StorageClass "cephfs": rpc error: code = Internal desc = rados: ret=-2, No such file or directory: "error in open /volumes/_/volumes/kubernetes/test-k8s-volumes:csi-vol-55c8b492-4a19-11ed-860d-7258ef3a62b4.meta"
I1012 10:33:39.623257       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"ceph-csi", Name:"test-volume", UID:"345ad256-5cef-4b48-a2ec-872357ce8a88", APIVersion:"v1", ResourceVersion:"115056323", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "cephfs": rpc error: code = Internal desc = rados: ret=-2, No such file or directory: "error in open /volumes/_/volumes/kubernetes/test-k8s-volumes:csi-vol-55c8b492-4a19-11ed-860d-7258ef3a62b4.meta"
I1012 10:33:43.785002       1 leaderelection.go:278] successfully renewed lease ceph-csi/cephfs-csi-ceph-com
```

My storage class:
```

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cephfs
  selfLink: /apis/storage.k8s.io/v1/storageclasses/cephfs
  uid: eda10318-fd58-49e1-87f8-a2fb63cb3e95
  resourceVersion: '114011121'
  creationTimestamp: '2022-10-11T11:21:24Z'
  annotations:
    [kubectl.kubernetes.io/last-applied-configuration](http://kubectl.kubernetes.io/last-applied-configuration): >
      {"allowVolumeExpansion":true,"apiVersion":"[storage.k8s.io/v1](http://storage.k8s.io/v1)","kind":"StorageClass","metadata":{"annotations":{},"name":"cephfs"},"mountOptions":["noatime"],"parameters":{"clusterID":"86bcbcaa-f136-4fb7-90b2-863db7a254da","[csi.storage.k8s.io/controller-expand-secret-name](http://csi.storage.k8s.io/controller-expand-secret-name)":"csi-cephfs-secret","[csi.storage.k8s.io/controller-expand-secret-namespace](http://csi.storage.k8s.io/controller-expand-secret-namespace)":"ceph-csi","[csi.storage.k8s.io/node-stage-secret-name](http://csi.storage.k8s.io/node-stage-secret-name)":"csi-cephfs-secret","[csi.storage.k8s.io/node-stage-secret-namespace](http://csi.storage.k8s.io/node-stage-secret-namespace)":"ceph-csi","[csi.storage.k8s.io/provisioner-secret-name](http://csi.storage.k8s.io/provisioner-secret-name)":"csi-cephfs-secret","[csi.storage.k8s.io/provisioner-secret-namespace](http://csi.storage.k8s.io/provisioner-secret-namespace)":"ceph-csi","fsName":"cephfs"},"provisioner":"[cephfs.csi.ceph.com](http://cephfs.csi.ceph.com/)","reclaimPolicy":"Delete"}
  managedFields:
    - manager: kubectl
      operation: Update
      apiVersion: [storage.k8s.io/v1](http://storage.k8s.io/v1)
      time: '2022-10-11T11:21:24Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:allowVolumeExpansion: {}
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:mountOptions: {}
        f:parameters:
          .: {}
          f:clusterID: {}
          f:csi.storage.k8s.io/controller-expand-secret-name: {}
          f:csi.storage.k8s.io/controller-expand-secret-namespace: {}
          f:csi.storage.k8s.io/node-stage-secret-name: {}
          f:csi.storage.k8s.io/node-stage-secret-namespace: {}
          f:csi.storage.k8s.io/provisioner-secret-name: {}
          f:csi.storage.k8s.io/provisioner-secret-namespace: {}
          f:fsName: {}
        f:provisioner: {}
        f:reclaimPolicy: {}
        f:volumeBindingMode: {}
allowVolumeExpansion: true
allowedTopologies: []
mountOptions:
  - noatime
parameters:
  clusterID: <cluster-id>
  [csi.storage.k8s.io/controller-expand-secret-name](http://csi.storage.k8s.io/controller-expand-secret-name): csi-cephfs-secret
  [csi.storage.k8s.io/controller-expand-secret-namespace](http://csi.storage.k8s.io/controller-expand-secret-namespace): ceph-csi
  [csi.storage.k8s.io/node-stage-secret-name](http://csi.storage.k8s.io/node-stage-secret-name): csi-cephfs-secret
  [csi.storage.k8s.io/node-stage-secret-namespace](http://csi.storage.k8s.io/node-stage-secret-namespace): ceph-csi
  [csi.storage.k8s.io/provisioner-secret-name](http://csi.storage.k8s.io/provisioner-secret-name): csi-cephfs-secret
  [csi.storage.k8s.io/provisioner-secret-namespace](http://csi.storage.k8s.io/provisioner-secret-namespace): ceph-csi
  fsName: cephfs
provisioner: [cephfs.csi.ceph.com](http://cephfs.csi.ceph.com/)
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

What's interesting:
- I can create subvolumes manually and have no errors:
ceph fs subvolumegroup create cephfs csi

- If I use old cephfs-provisioner - all works. Archived provisioner locate here:
 https://github.com/kubernetes-retired/external-storage/tree/master/ceph/cephfs
 
Cephfs worked before I redeployed ceph osd node.
Could somebody help me?

**Comment by Madhu-1** [comment] 2022-10-12 13:17
@kuhar2007 can you please provide below outputs

* ceph -s
* ceph fs ls

**Comment by Madhu-1** [comment] 2022-10-12 13:18
>b124679da43a failed to provision volume with StorageClass "cephfs": rpc error: code = Internal desc = rados: ret=-2, No such file or directory: "error in open /volumes/_/volumes/kubernetes/test-k8s-volumes:csi-vol-2d993fe4-4a2e-11ed-87cf-62cdbefcaf73.meta

This is something coming from ceph, @kotreshhr @mchangir any idea about this error?

**Comment by Madhu-1** [comment] 2022-10-12 13:18
@kuhar2007 please also provide csi-cephfsplugin container logs from the csi-cephfs provisioner pod.

**Comment by kuhar2007** [comment] 2022-10-12 13:28
```
ceph -s
  cluster:
    id:     <cluster-id>
    health: HEALTH_WARN
            258 pgs not deep-scrubbed in time
            169 pgs not scrubbed in time

  services:
    mon: 3 daemons, quorum ceph01,ceph02,ceph03 (age 5h)
    mgr: ceph03(active, since 4d), standbys: ceph01, ceph02
    mds: cephfs:1 {0=ceph03=up:active} 2 up:standby
    osd: 20 osds: 20 up (since 4d), 20 in (since 4d); 20 remapped pgs

  data:
    pools:   16 pools, 921 pgs
    objects: 11.03M objects, 23 TiB
    usage:   70 TiB used, 122 TiB / 192 TiB avail
    pgs:     196242/33080469 objects misplaced (0.593%)
             900 active+clean
             19  active+remapped+backfill_wait
             1   active+clean+scrubbing+deep
             1   active+remapped+backfilling

  io:
    client:   82 KiB/s rd, 13 MiB/s wr, 73 op/s rd, 741 op/s wr
    recovery: 16 MiB/s, 4 objects/s
```

`ceph fs ls
name: cephfs, metadata pool: cephfs_metadata, data pools: [cephfs_data ]`

Logs from  csi-cephfsplugin I wrote in my first message.

**Comment by Madhu-1** [comment] 2022-10-12 13:44
>Logs from csi-cephfsplugin I wrote in my first message.

 @kuhar2007 we have 5/6 containers running in the cephfs provisioner pod the logs you provided is from csi-provisioner container i need to take a look at the csi-cephfsplugin container logs.

**Comment by kuhar2007** [comment] 2022-10-12 13:51
Logs from csi-cephfsplugin-provisioner container csi-cephfsplugin:
```
I1012 13:48:34.760113       1 utils.go:195] ID: 23 Req-ID: pvc-4aa9cddd-54ca-4e68-8b61-52c217b0dbb2 GRPC call: /csi.v1.Controller/CreateVolume
I1012 13:48:34.760544       1 utils.go:206] ID: 23 Req-ID: pvc-4aa9cddd-54ca-4e68-8b61-52c217b0dbb2 GRPC request: {"capacity_range":{"required_bytes":53687091200},"name":"pvc-4aa9cddd-54ca-4e68-8b61-52c217b0dbb2","parameters":{"clusterID":"<cluster-id>","csi.storage.k8s.io/pv/name":"pvc-4aa9cddd-54ca-4e68-8b61-52c217b0dbb2","csi.storage.k8s.io/pvc/name":"test-volume","csi.storage.k8s.io/pvc/namespace":"ceph-csi","fsName":"cephfs"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"mount_flags":["noatime"]}},"access_mode":{"mode":5}}]}
I1012 13:48:34.767074       1 omap.go:88] ID: 23 Req-ID: pvc-4aa9cddd-54ca-4e68-8b61-52c217b0dbb2 got omap values: (pool="cephfs_metadata", namespace="csi", name="csi.volumes.default"): map[]
I1012 13:48:34.772401       1 omap.go:158] ID: 23 Req-ID: pvc-4aa9cddd-54ca-4e68-8b61-52c217b0dbb2 set omap keys (pool="cephfs_metadata", namespace="csi", name="csi.volumes.default"): map[csi.volume.pvc-4aa9cddd-54ca-4e68-8b61-52c217b0dbb2:90df7c0a-4a34-11ed-a1fb-3a31b3d4c580])
I1012 13:48:34.774716       1 omap.go:158] ID: 23 Req-ID: pvc-4aa9cddd-54ca-4e68-8b61-52c217b0dbb2 set omap keys (pool="cephfs_metadata", namespace="csi", name="csi.volume.90df7c0a-4a34-11ed-a1fb-3a31b3d4c580"): map[csi.imagename:csi-vol-90df7c0a-4a34-11ed-a1fb-3a31b3d4c580 csi.volname:pvc-4aa9cddd-54ca-4e68-8b61-52c217b0dbb2])
I1012 13:48:34.774835       1 fsjournal.go:293] ID: 23 Req-ID: pvc-4aa9cddd-54ca-4e68-8b61-52c217b0dbb2 Generated Volume ID (0001-0024-86bcbcaa-f136-4fb7-90b2-863db7a254da-0000000000000001-90df7c0a-4a34-11ed-a1fb-3a31b3d4c580) and subvolume name (csi-vol-90df7c0a-4a34-11ed-a1fb-3a31b3d4c580) for request name (pvc-4aa9cddd-54ca-4e68-8b61-52c217b0dbb2)
I1012 13:48:34.779776       1 volume.go:246] ID: 23 Req-ID: pvc-4aa9cddd-54ca-4e68-8b61-52c217b0dbb2 cephfs: created subvolume group /volumes/kubernetes/test-k8s-volumes
E1012 13:48:35.404359       1 volume.go:260] ID: 23 Req-ID: pvc-4aa9cddd-54ca-4e68-8b61-52c217b0dbb2 failed to create subvolume csi-vol-90df7c0a-4a34-11ed-a1fb-3a31b3d4c580 in fs cephfs: rados: ret=-2, No such file or directory: "error in open /volumes/_/volumes/kubernetes/test-k8s-volumes:csi-vol-90df7c0a-4a34-11ed-a1fb-3a31b3d4c580.meta"
E1012 13:48:35.404429       1 controllerserver.go:84] ID: 23 Req-ID: pvc-4aa9cddd-54ca-4e68-8b61-52c217b0dbb2 failed to create volume pvc-4aa9cddd-54ca-4e68-8b61-52c217b0dbb2: rados: ret=-2, No such file or directory: "error in open /volumes/_/volumes/kubernetes/test-k8s-volumes:csi-vol-90df7c0a-4a34-11ed-a1fb-3a31b3d4c580.meta"
I1012 13:48:35.409390       1 omap.go:125] ID: 23 Req-ID: pvc-4aa9cddd-54ca-4e68-8b61-52c217b0dbb2 removed omap keys (pool="cephfs_metadata", namespace="csi", name="csi.volumes.default"): [csi.volume.pvc-4aa9cddd-54ca-4e68-8b61-52c217b0dbb2]
E1012 13:48:35.409524       1 utils.go:210] ID: 23 Req-ID: pvc-4aa9cddd-54ca-4e68-8b61-52c217b0dbb2 GRPC error: rpc error: code = Internal desc = rados: ret=-2, No such file or directory: "error in open /volumes/_/volumes/kubernetes/test-k8s-volumes:csi-vol-90df7c0a-4a34-11ed-a1fb-3a31b3d4c580.meta"
```

**Comment by kotreshhr** [comment] 2022-10-12 13:59
> >b124679da43a failed to provision volume with StorageClass "cephfs": rpc error: code = Internal desc = rados: ret=-2, No such file or directory: "error in open /volumes/_/volumes/kubernetes/test-k8s-volumes:csi-vol-2d993fe4-4a2e-11ed-87cf-62cdbefcaf73.meta
> 
> This is something coming from ceph, @kotreshhr @mchangir any idea about this error?

Do we have mgr logs associated with this?

**Comment by kuhar2007** [comment] 2022-10-13 14:07
@kotreshhr mgr logs write something like this:
`Oct 13 16:04:52 ceph01 ceph-mgr[1881]: 2022-10-13 16:04:52.096 7f450534b700 -1 mgr.server reply reply (2) No such file or directory error in open /volumes/_/volumes/kubernetes/test-k8s-volumes:csi-vol-01921ca4-4b00-11ed-aaa9-5eb424f20c91.meta`

**Comment by kuhar2007** [comment] 2022-10-14 07:58
Cephfs-provisioner at okd4 has same errors:
```
I1014 07:54:42.984441 1 controller.go:1337] provision "cert-manager/test-vol" class "cephfs": started
I1014 07:54:42.984660 1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"cert-manager", Name:"test-vol", UID:"2079a350-8e98-4911-b968-e6f82f06af42", APIVersion:"v1", ResourceVersion:"102504467", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "cert-manager/test-vol"
I1014 07:54:42.987939 1 connection.go:183] GRPC call: /csi.v1.Controller/CreateVolume
I1014 07:54:42.987954 1 connection.go:184] GRPC request: {"capacity_range":{"required_bytes":53687091200},"name":"pvc-2079a350-8e98-4911-b968-e6f82f06af42","parameters":{"clusterID":"86bcbcaa-f136-4fb7-90b2-863db7a254da","csi.storage.k8s.io/pv/name":"pvc-2079a350-8e98-4911-b968-e6f82f06af42","csi.storage.k8s.io/pvc/name":"test-vol","csi.storage.k8s.io/pvc/namespace":"cert-manager","fsName":"cephfs"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"mount_flags":["debug","noatime","nouuid"]}},"access_mode":{"mode":5}}]}
I1014 07:54:43.028694 1 connection.go:186] GRPC response: {}
I1014 07:54:43.028757 1 connection.go:187] GRPC error: rpc error: code = Internal desc = rados: ret=-2, No such file or directory: "error in open /volumes/_/volumes/kubernetes/okd4-volumes:csi-vol-76936674-4b95-11ed-8cd8-0a580aeb0208.meta"
I1014 07:54:43.028781 1 controller.go:764] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = Internal desc = rados: ret=-2, No such file or directory: "error in open /volumes/_/volumes/kubernetes/okd4-volumes:csi-vol-76936674-4b95-11ed-8cd8-0a580aeb0208.meta"
I1014 07:54:43.028817 1 controller.go:1075] Final error received, removing PVC 2079a350-8e98-4911-b968-e6f82f06af42 from claims in progress
W1014 07:54:43.028827 1 controller.go:934] Retrying syncing claim "2079a350-8e98-4911-b968-e6f82f06af42", failure 7
E1014 07:54:43.028851 1 controller.go:957] error syncing claim "2079a350-8e98-4911-b968-e6f82f06af42": failed to provision volume with StorageClass "cephfs": rpc error: code = Internal desc = rados: ret=-2, No such file or directory: "error in open /volumes/_/volumes/kubernetes/okd4-volumes:csi-vol-76936674-4b95-11ed-8cd8-0a580aeb0208.meta"
I1014 07:54:43.028931 1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"cert-manager", Name:"test-vol", UID:"2079a350-8e98-4911-b968-e6f82f06af42", APIVersion:"v1", ResourceVersion:"102504467", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "cephfs": rpc error: code = Internal desc = rados: ret=-2, No such file or directory: "error in open /volumes/_/volumes/kubernetes/okd4-volumes:csi-vol-76936674-4b95-11ed-8cd8-0a580aeb0208.meta"

```

**Comment by Madhu-1** [comment] 2022-10-14 08:05
@kuhar2007 AFAIK this is not related to cephcsi, its mostly problem with ceph cluster. can you create the ceph fs subvolume manually and share the output here?

**Comment by kuhar2007** [comment] 2022-10-17 06:54
@Madhu-1 this command didn't make output:
```
[root@ceph01 ~]# ceph fs subvolumegroup create cephfs csi
[root@ceph01 ~]# ceph fs subvolumegroup ls cephfs | grep csi
        "name": "csi"
[root@ceph01 ~]# ceph fs subvolumegroup create cephfs csi-2
[root@ceph01 ~]# ceph fs subvolumegroup ls cephfs | grep csi
        "name": "csi-2"
        "name": "csi"
```

**Comment by Madhu-1** [comment] 2022-10-17 07:03
@kuhar2007 you need to create subvolume not the group, refer https://docs.ceph.com/en/quincy/cephfs/fs-volumes/#fs-subvolumes for the right command

**Comment by kuhar2007** [comment] 2022-10-17 08:24
@Madhu-1 Sorry for wrong command:
```
[root@ceph01 ~]# ceph fs subvolume create cephfs csi
[root@ceph01 ~]# ceph fs subvolume ls cephfs | grep csi
        "name": "csi"
[root@ceph01 ~]# ceph fs subvolume create cephfs csi-2
[root@ceph01 ~]# ceph fs subvolume ls cephfs | grep csi
        "name": "csi-2"
        "name": "csi"
[root@ceph01 ~]# ceph fs subvolume ls cephfs
[
    {
        "name": "csi-2"
    },
    {
        "name": "csi"
    }
]
```

**Comment by Madhu-1** [comment] 2022-10-17 08:29
@kuhar2007 can you please create it in the csi group

```
ceph fs subvolume create cephfs test csi
```

**Comment by kuhar2007** [comment] 2022-10-17 08:34
@Madhu-1  I did this command and didn't get any errors.
How can I check results?

**Comment by Madhu-1** [comment] 2022-10-17 08:35
> @Madhu-1 I did this command and didn't get any errors. How can I check results?

same way `ceph fs subvolume ls cephfs csi`

**Comment by Madhu-1** [comment] 2022-10-17 08:36
@kotreshhr any idea why CLI commands are passing and csi commands are getting this error?

**Comment by kuhar2007** [comment] 2022-10-17 08:55
@Madhu-1 here is my output:
```
[root@ceph01 ~]# ceph fs subvolume create cephfs test csi
[root@ceph01 ~]# ceph fs subvolume ls cephfs
[
    {
        "name": "csi-2"
    },
    {
        "name": "kubernetes"
    },
    {
        "name": "csi"
    }
]
[root@ceph01 ~]# ceph fs subvolume ls cephfs csi
[
    {
        "name": "test-k8s-volumes"
    },
    {
        "name": "csi-vol-43a2c850-705e-11eb-aea3-3e6c3636dc2d"
    },
    {
        "name": "test"
    }
]
```

**Comment by kotreshhr** [comment] 2022-10-18 04:56
@kuhar2007 If this is consistently happening with csi commands, please enable mgr debug logs, reproduce the issue and share the mgr logs. But I would suggest you to try this on the supported ceph cluster version (pacific[16.x], quincy[17.x]). Nautilus[14.x] is unsupported and lot of changes have gone in after that.

@Madhu-1 
Is this happening during subvolume creation phase ? We do mantain a '/volumes/_<groupname>:<subvolname>.meta' metadata file for supporting subvolume authorize/deauthorize functions. But the filename format and filepath referenced here is not exactly matching. I didn't cross verify on nautilus though.

**Comment by kuhar2007** [comment] 2022-10-18 08:17
@kotreshhr it isn't easy to upgrade ceph cluster safely to the last version pacific or quincy. We have a lot of dependencies.

**Comment by Madhu-1** [comment] 2022-10-18 08:29
> @kuhar2007 If this is consistently happening with csi commands, please enable mgr debug logs, reproduce the issue and share the mgr logs. But I would suggest you to try this on the supported ceph cluster version (pacific[16.x], quincy[17.x]). Nautilus[14.x] is unsupported and lot of changes have gone in after that.
> 
> @Madhu-1 Is this happening during subvolume creation phase ? We do mantain a '/volumes/_:.meta' metadata file for supporting subvolume authorize/deauthorize functions. But the filename format and filepath referenced here is not exactly matching. I didn't cross verify on nautilus though.

Yes its happening during the create operation, Yes that is the crazy part here the error message doesnt match the subvolumegroup which is `csi` in our case and the error only happens to have with cephcsi not with CLI command (this is what i dont understand)

**Comment by kuhar2007** [comment] 2022-10-18 08:40
@kotreshhr @Madhu-1 I have one more idea. I use k8s which deployed in openstack version stein, this version use ceph-common packages lower then 14 version (v12), after installing new packages for nautilus(14.2.22), it (ceph) got  new feature about secure connections, that you can block unsecure connection, and if I allow unsecure connection ceph all works normally, instead of cephfs, if disallow - all down (openstack and k8s inside openstack). Maybe it can affect something for csi-cephfs?

**Comment by Madhu-1** [comment] 2022-10-18 08:45
> @kotreshhr @Madhu-1 I have one more idea. I use k8s which deployed in openstack version stein, this version use ceph-common packages lower then 14 version (v12), after installing new packages for nautilus(14.2.22), it (ceph) got new feature about secure connections, that you can block unsecure connection, and if I allow unsecure connection ceph all works normally, instead of cephfs, if disallow - all down (openstack and k8s inside openstack). Maybe it can affect something for csi-cephfs?

cephcsi will not use the ceph packages from the host not even the unsecure connection. but good to test it. can you exec into the csi-cephfs-provisioner pod (csi-cephfsplugin container) and run the ceph commands manually and check? if we face similar error inside the pod something is wrong.

**Comment by kuhar2007** [comment] 2022-10-18 10:36
@Madhu-1  csi said me that have no permissions:
```
[root@csi-cephfsplugin-provisioner-74f4fdf498-kc4pz /]# ceph fs subvolume create cephfs test-2 csi
2022-10-18T10:32:14.446+0000 7f24e90b1700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2]
2022-10-18T10:32:14.446+0000 7f24e98b2700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2]
[errno 1] RADOS permission error (error connecting to the cluster)
[root@csi-cephfsplugin-provisioner-74f4fdf498-kc4pz /]# ceph fs subvolume ls cephfs         
2022-10-18T10:33:26.958+0000 7f3163fff700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2]
2022-10-18T10:33:27.022+0000 7f316b59e700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2]
[errno 13] RADOS permission denied (error connecting to the cluster)
```

**Comment by Madhu-1** [comment] 2022-10-18 10:43
@kuhar2007 you need to pass `userid,key and monitor` details the above command it looks like below

```ceph fs subvolume create cephfs test-2 csi --m=<mon-ip:6789> --id=<userid> --key=keyring```

**Comment by kuhar2007** [comment] 2022-10-18 11:03
@Madhu-1 It works from container:
```
[root@csi-cephfsplugin-provisioner-74f4fdf498-kc4pz /]# ceph fs subvolume create cephfs test-2 csi --id=<user> --key=<key>
[root@csi-cephfsplugin-provisioner-74f4fdf498-kc4pz /]# ceph fs subvolume ls cephfs csi --id=<user> --key=<key>
[
    {
        "name": "test-k8s-volumes"
    }, 
    {
        "name": "test-2"
    }, 
    {
        "name": "csi-vol-43a2c850-705e-11eb-aea3-3e6c3636dc2d"
    }, 
    {
        "name": "test"
    }
]
```

**Comment by Madhu-1** [comment] 2022-10-18 11:09
now am able to identify what is wrong :D can you please delete all pending pvc's and restart cephfs-provisioner pod and create a new pvc and check it works?

**Comment by kuhar2007** [comment] 2022-10-19 08:02
@Madhu-1 I have few k8s clusters and have the same error. I can't create cephfs volume even at cluster without any volumes. 
Or you mean delete all volumes at each clusters?

**Comment by Madhu-1** [comment] 2022-10-19 09:16
> @Madhu-1 I have few k8s clusters and have the same error. I can't create cephfs volume even at cluster without any volumes. Or you mean delete all volumes at each clusters?

i meant delete only pending pvc not all volumes. try restarting cephfs provisioner and create new pvc and try

**Comment by kuhar2007** [comment] 2022-10-19 09:56
@Madhu-1 I have no pvc with status "pending"

**Comment by Madhu-1** [comment] 2022-10-19 10:02
in that case can you please create a new PVC after restarting csi-cephfs-provisioner pods?

**Comment by kuhar2007** [comment] 2022-10-19 10:05
@Madhu-1 I restarted all pods in namespace ceph-csi and got same problem.
I'll try restart all cluster nodes for test and check it again.

**Comment by kuhar2007** [comment] 2022-10-19 10:26
Full cluster restart didn't help too...

**Comment by Madhu-1** [comment] 2022-10-19 10:32
Am sorry to say not sure what is happening with your cluster, i dont have path forward.

**Comment by kuhar2007** [comment] 2022-10-19 10:54
I'll plan to update containers in openstack for fix warning about unsecure connection, then write about results.

**Comment by kuhar2007** [comment] 2022-10-19 13:20
@Madhu-1 I found solution.
If we look to error: 

`Warning ProvisioningFailed 2s cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-f69755684-gv9kz_8262deb3-dcc7-4463-8a30-b124679da43a failed to provision volume with StorageClass "cephfs": rpc error: code = Internal desc = rados: ret=-2, No such file or directory: "error in open /volumes/_/volumes/kubernetes/test-k8s-volumes:csi-vol-2d993fe4-4a2e-11ed-87cf-62cdbefcaf73.meta`

We see path for metadata:

`/volumes/_/volumes/kubernetes/test-k8s-volumes`

I checked filesystem cephfs and didn't find folder with name "**_**". So I create directory  **/volumes/_/volumes/kubernetes/test-k8s-volumes** and ceph-csi start work.

One more question:
- could configure metadata location dir?
I have simple config for cephfs:
```
[
  {
    "clusterID": "<clusterID>",
    "monitors": [
      "<ip>:6789",
      "<ip>:6789",
      "<ip>:6789"
    ],
    "cephFS": {
      "subvolumeGroup": "/volumes/kubernetes/test-k8s-volumes"
    }
  }
]
```

**Comment by Madhu-1** [comment] 2022-10-19 13:28
you are using `"subvolumeGroup"` option in the configmap, this should be the name of the group like `csi` not the path, cephfs will take carea of creating the path for you. if you still want to use it or just switch to some meaningful name not the path. as its working for you am closing this one. Thank you.

>could configure metadata location dir?
No this is not possible cephcsi will use the metadatapool from the ceph filesystem its not configuration in cephcsi.

**Closed as completed by Madhu-1** 2022-10-19 13:28 UTC
