### ISSUE TITLE
K8S: Cephfs - Error in rename -> PV stuck in Release state - bis

### ISSUE THREAD

**Issue by iMikeG6** [ceph/ceph-csi#3839] opened 2023-05-16 19:23 UTC
# Describe the bug #

Can you re-open the issue #3654 please ?
I'm also having this issue.

```
ceph Invalid cross-device link: "error in rename /volumes/XXX to /volumes/_deleting/AAA
```

Here's the user caps I have set
```
ceph auth caps client.user2 \
 mds 'allow rw path=/volumes/k8s' \
 mgr 'allow rw' \
 mon 'allow r' \
 osd 'allow rw tag cephfs *=*'
```

On the `ceph-csi-config`, I have set the subvolumegroup which has been created with the following `ceph fs subvolumegroup create p-test1 k8s`

```
    "cephFS": {
      "subvolumeGroup": "k8s"
    }
```

The root volume:
```
/volumes/
    ├── _deleting
    ├── k8s
    │   └── csi-vol-b102c847-d935-44ae-b378-b915f3f73370
    │       └── 5266107c-7fe0-40fe-ab90-577c92b4423a
    └── _k8s:csi-vol-b102c847-d935-44ae-b378-b915f3f73370.meta
```

Notice that even if i'm using the admin auth key, this is not working either.
Had to unset the quota on the folder k8s to fully release the volume on Kubernetes.

Interestingly, when I set a quota in the parent folder, which is in my case `/volumes`, delete is working 

# Environment details #

    Image/version of Ceph CSI driver : 3.8.0
    Helm chart version : 3.8.0
    Kernel version : 4.18.0-372.16.1.el8_6.x86_64
    Mounter used for mounting PVC: kernel
    Kubernetes cluster version : v1.25.9
    Ceph cluster version : 17.2.1
   Operating system: RedHat 8.6

# Steps to reproduce #

Create a cephfs, install helm chart ceph-csi-cephfs
Set folder quota on a subvolumegroup
Create a pvc then delete it

# Actual results #

Volume is not release from the kubernetes cluster and not delete on the ceph cluster

# Expected behavior #

Release volume and delete k8s volume that has been provisioned by kubernetes

# Logs #

```
I0516 19:18:06.893680       1 controller.go:1471] delete "pvc-aaa99de5-18fe-4fe8-bf36-eca0642b55b4": started
E0516 19:18:06.912839       1 controller.go:1481] delete "pvc-aaa99de5-18fe-4fe8-bf36-eca0642b55b4": volume deletion failed: rpc error: code = Internal desc = rados: ret=-18, Invalid cross-device link: "error in rename /volumes/k8s/csi-vol-94bf4d8e-6a1c-4749-9ada-1ef3e40228bf to /volumes/_deleting/94fe905c-2d53-4b8b-893d-a893f48d57e4"
W0516 19:18:06.912875       1 controller.go:989] Retrying syncing volume "pvc-aaa99de5-18fe-4fe8-bf36-eca0642b55b4", failure 3
E0516 19:18:06.912894       1 controller.go:1007] error syncing volume "pvc-aaa99de5-18fe-4fe8-bf36-eca0642b55b4": rpc error: code = Internal desc = rados: ret=-18, Invalid cross-device link: "error in rename /volumes/k8s/csi-vol-94bf4d8e-6a1c-4749-9ada-1ef3e40228bf to /volumes/_deleting/94fe905c-2d53-4b8b-893d-a893f48d57e4"
I0516 19:18:06.913060       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolume", Namespace:"", Name:"pvc-aaa99de5-18fe-4fe8-bf36-eca0642b55b4", UID:"c2636312-c234-4f5b-86f0-34452ce1a700", APIVersion:"v1", ResourceVersion:"188678234", FieldPath:""}): type: 'Warning' reason: 'VolumeFailedDelete' rpc error: code = Internal desc = rados: ret=-18, Invalid cross-device link: "error in rename /volumes/k8s/csi-vol-94bf4d8e-6a1c-4749-9ada-1ef3e40228bf to /volumes/_deleting/94fe905c-2d53-4b8b-893d-a893f48d57e
```

# Additional context #

Same issue reported here: #3654

**Comment by Madhu-1** [comment] 2023-05-17 08:16
Instead of deleting let's continue debugging this one.

**Comment by iMikeG6** [comment] 2023-05-18 14:05
Hi, thanks for investigating this issue.

Here's are some results from another cluster I have which is hosted on RedHat 9 and run with ceph 17.2.5 community edition.

When I delete the volumes, in the same Kubernetes cluster that previously failed, which running Redhat 8, the delete is working:

```
I0518 13:25:27.823912       1 controller.go:1471] delete "pvc-43e176d2-2929-4680-a411-64ed8e2d9ed6": started
I0518 13:25:27.856647       1 controller.go:1486] delete "pvc-43e176d2-2929-4680-a411-64ed8e2d9ed6": volume deleted
I0518 13:25:27.884074       1 controller.go:1523] delete "pvc-43e176d2-2929-4680-a411-64ed8e2d9ed6": failed to remove finalizer for persistentvolume: Operation cannot be fulfilled on persistentvolumes "pvc-43e176d2-2929-4680-a411-64ed8e2d9ed6": the object has been modified; please apply your changes to the latest version and try again
W0518 13:25:27.884095       1 controller.go:989] Retrying syncing volume "pvc-43e176d2-2929-4680-a411-64ed8e2d9ed6", failure 0
E0518 13:25:27.884119       1 controller.go:1007] error syncing volume "pvc-43e176d2-2929-4680-a411-64ed8e2d9ed6": Operation cannot be fulfilled on persistentvolumes "pvc-43e176d2-2929-4680-a411-64ed8e2d9ed6": the object has been modified; please apply your changes to the latest version and try again
I0518 13:25:27.884133       1 controller.go:1471] delete "pvc-43e176d2-2929-4680-a411-64ed8e2d9ed6": started
I0518 13:25:27.899702       1 controller.go:1486] delete "pvc-43e176d2-2929-4680-a411-64ed8e2d9ed6": volume deleted
I0518 13:25:27.912078       1 controller.go:1531] delete "pvc-43e176d2-2929-4680-a411-64ed8e2d9ed6": persistentvolume deleted
I0518 13:25:27.912095       1 controller.go:1536] delete "pvc-43e176d2-2929-4680-a411-64ed8e2d9ed6": succeeded
```

Except, the two errors below:

1. Operation cannot be fulfilled on persistentvolumes
2. error syncing volume "pvc-43e176d2-2929-4680-a411-64ed8e2d9ed6"

The volume is release from the Kubernetes cluster and it get deleted on the cephfs volume.

Is this a bug from ceph version 17.2.1 ?
If so, my only worry is, will it be the same with the Redhat paid version ?
Cause, we are considering getting the paid version from Redhat, but I know that they are few version behind the community edition. And if it's the case, that mean that we will not be able to set quota for our Kubernetes as a service clusters.

**Comment by Rakshith-R** [comment] 2023-05-22 05:09
@iMikeG6  
And paste the kernel version of the OS where delete is working ? 
Can you please open a ceph tracker too with all the info?
This error is coming from ceph layer.

@mchangir @kotreshhr can you please help here,
Deletion of subvolumes with quota set using subvolumegroup seems to be failing on lower kernel version.

**Comment by Madhu-1** [comment] 2023-05-22 08:41
@iMikeG6 i tried to reproduce it on `17.2.6` but could not. can you answer below question

* Set folder quota on a subvolumegroup (can you give the exact step/command you are using to set quota)
* What is the quota set on subvolumegroup, and what is the PVC size.

**Comment by iMikeG6** [comment] 2023-05-22 09:14
Thank you guys for your help, really appreciated it.

> And paste the kernel version of the OS where delete is working ?

Yes, sure, let's call it the production cluster, which use kernel: `5.14.0-284.11.1.el9_2.x86_64` and it's a `Redhat 9.2`
The Ceph version is `17.2.6` community edition.

> i tried to reproduce it on `17.2.6` but could not. can you answer below question

The Ceph version that failed to delete subvolumegroupe on K8S was version `17.2.1` and the os is `Redhat 8.6` and the kernel version is: `4.18.0-372.16.1.el8_6.x86_64` Let's call it the test cluster.

> Set folder quota on a subvolumegroup (can you give the exact step/command you are using to set quota)

I went to the gui, to File system -> Directory tab -> unfolded / -> volumes. I then clicked on k8s folder and on the right side selected Max size and Set. Value was `30GB`, but any values produced the same issue.
On cephfs data pool, i set a quota to `100GB`.

As for the PVC size, I tried different values. Tried value that were below and above the subvolumegroup quota.
They've all produced error `Invalid cross-device link: "error in rename`

Since last time, I have updated the test cluster, the one that have giving me the error mentioned, to the latest ceph version, I didn't re-tested it cause it worked on the production cluster `17.2.5` community edition, which is now updated to the latest version.
However, before opening a ceph tracker issue, which I never done by the way, I could try again on the updated ceph test cluster and report back here.

**Comment by Madhu-1** [comment] 2023-05-22 11:51
This looks to be a problem with ceph

```
sh-4.4# mount -t ceph -o mds_namespace=myfs,name=admin,secret=$my_secret $mon_endpoints:/ /tmp/registry
sh-4.4# 
sh-4.4# # See your mounted filesystem
sh-4.4# df -h
Filesystem            Size  Used Avail Use% Mounted on
overlay                28G  6.8G   20G  26% /
tmpfs                 2.0G     0  2.0G   0% /sys/fs/cgroup
devtmpfs              1.8G     0  1.8G   0% /dev
shm                    64M     0   64M   0% /dev/shm
tmpfs                 3.5G  718M  2.8G  21% /usr/lib/modules
/dev/vda1              28G  6.8G   20G  26% /etc/rook
tmpfs                 3.9G  4.0K  3.9G   1% /var/lib/rook-ceph-mon
tmpfs                 3.9G   12K  3.9G   1% /run/secrets/kubernetes.io/serviceaccount
10.101.191.61:6789:/   31G     0   31G   0% /tmp/registry
sh-4.4# 
sh-4.4# cd /tmp/registry/
sh-4.4# ls
sh-4.4# cd ..
sh-4.4# ceph fs subvolumegroup create myfs test
sh-4.4# cd /tmp/registry/
sh-4.4# ls
volumes
sh-4.4# cd volumes/
sh-4.4# ls
test
sh-4.4# setfattr -n ceph.quota.max_bytes -v 10485760000 test/
sh-4.4# 
sh-4.4# getfattr -n ceph.quota.max_bytes test/
# file: test/
ceph.quota.max_bytes="10485760000"

sh-4.4# ceph fs subvolume create myfs test test --size=1024
sh-4.4# ceph fs subvolume rm myfs test test
Error EXDEV: error in rename /volumes/test/test to /volumes/_deleting/f718b112-4f69-4e93-b75b-419a50b4457a
sh-4.4# ceph version
ceph version 17.2.1 (ec95624474b1871a821a912b8c3af68f8f8e7aa1) quincy (stable)
sh-4.4# 
```

ceph fs subvolumegroup does not have the option to set quota/size when creating, its done manually after mounting. I hope this is already fixed in ceph. 

```
sh-4.4# 
sh-4.4# # See your mounted filesystem
sh-4.4# df -h
Filesystem            Size  Used Avail Use% Mounted on
overlay                28G  6.9G   20G  26% /
tmpfs                 2.0G     0  2.0G   0% /sys/fs/cgroup
devtmpfs              1.8G     0  1.8G   0% /dev
shm                    64M     0   64M   0% /dev/shm
/dev/vda1              28G  6.9G   20G  26% /etc/hosts
tmpfs                 3.5G  718M  2.8G  21% /usr/lib/modules
tmpfs                 3.9G  4.0K  3.9G   1% /var/lib/rook-ceph-mon
tmpfs                 3.9G   12K  3.9G   1% /run/secrets/kubernetes.io/serviceaccount
10.99.195.117:6789:/   31G     0   31G   0% /tmp/registry
sh-4.4# 
sh-4.4# ceph fs subvolumegroup create myfs test
sh-4.4# cd /tmp/registry/volumes/
sh-4.4# setfattr -n ceph.quota.max_bytes -v 10485760000 test/
sh-4.4# getfattr -n ceph.quota.max_bytes test/
# file: test/
ceph.quota.max_bytes="10485760000"

sh-4.4#  ceph fs subvolume create myfs test test --size=1024
sh-4.4#  ceph fs subvolume rm myfs test test
sh-4.4# ceph version
ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)
sh-4.4# 
```

It looks like its fixed in ceph already, i dont have any tracker for it.

I am closing this as not a CSI issue.

**Closed as completed by Madhu-1** 2023-05-22 11:51 UTC
Labels: component/cephfs
