### ISSUE TITLE
support  liveness probe configure in kubernetes yaml

### ISSUE THREAD

**Issue by yylt** [ceph/ceph-csi#4482] opened 2024-03-08 08:21 UTC
# Describe the feature you'd like to have #

When the liveness check fails, the container should be restarted. Currently, the failure of the check can only be determined through the /metrics path with csi_liveness as shown below:

```
$ curl 10.46.1.6:8680/metrics|more
# HELP csi_liveness Liveness Probe
# TYPE csi_liveness gauge
csi_liveness 0

```

This is not very friendly for pod probe checks in Kubernetes. A common way to check pods is through the following method:

```
livenessProbe:
  httpGet:
    host: 127.0.0.1
    path: /healthz
    port: 8080
    scheme: HTTP
  failureThreshold: 8
  initialDelaySeconds: 15
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 15
```

Could you provide an endpoint for liveness to facilitate probe checks?

# What is the value to the end user? (why is it a priority?) #

When a health check fails, the container can be restarted instead of showing as running but not being able to do anything.

# How will we know we have a good solution? (acceptance criteria) #

- [ ] add new healthz endpoint, like /healthz

**Comment by Madhu-1** [comment] 2024-03-12 11:48
@yylt is this duplicate of https://github.com/ceph/ceph-csi/issues/1096?

**Comment by yylt** [comment] 2024-03-13 02:28
Yes, it is indeed repetitive, there is no PR of [#1096](https://github.com/ceph/ceph-csi/issues/1096). 

Additionally, could consider using the https://github.com/kubernetes-csi/livenessprobe project replace?

**Comment by Madhu-1** [comment] 2024-03-13 10:57
Yes i have mentioned different options in #1096, considering it am closing this as duplicate, Thank you

**Closed as not planned by Madhu-1** 2024-03-13 10:57 UTC
