### ISSUE TITLE
Release v1.1.0 of Ceph-CSI driver

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#353] opened 2019-05-03 10:57 UTC
- [x] Define release process
  - Release doc would be a good start
- [x] Define release deadlines
  - Code Freeze : 25-May-2019
  - RC : 04-May -2019
  - GA : 14- Jun-2019 
- [x] Define/list roadmap for v1.1.0
  - Proposed contents for v1.1.0 release
  -- Provision cephfs volumes using Ceph manager
  -- E2E CI
  -- Kubernetes 1.14 base.
  -- CSI spec 1.1.0 
  -- Stateless implementation ( RBD, CephFS)
  -- Update sidecar containers to latest available
  - The release issues/PRs are labelled with `release-1.1.0`.

List of PRs labelled with release-1.1.0
https://github.com/ceph/ceph-csi/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3Arelease-1.1.0+

- [x] Document features and announce the release.
- [x] Release team:
  -- @humblec 
  -- @Madhu-1

**Comment by humblec** [comment] 2019-05-03 11:00
@rootfs @gman0 @j-griffith @leseb @Madhu-1 @ShyamsundarR Can you share your thoughts or add input ?

**Comment by Madhu-1** [comment] 2019-05-07 07:49
we need to make master as the default branch for this one.
@humblec assigning this to you as I see you already working on this one.

**Comment by humblec** [comment] 2019-05-07 08:04
> we need to make master as the default branch for this one.
> @humblec assigning this to you as I see you are already working on this one.

Yep, lets make `master` as the default branch. 

Before we make `master` as the default branch, I think we have to do or make `csiv1.0` and `master` in parity.

**Comment by humblec** [comment] 2019-05-07 10:47
> > we need to make master as the default branch for this one.
> > @humblec assigning this to you as I see you are already working on this one.
> 
> Yep, lets make `master` as the default branch.
> 
> Before we make `master` as the default branch, we have to do or make `csiv1.0` and `master` in parity.

https://github.com/ceph/ceph-csi/pull/363 is to bring `master` and `csi v1.0` in parity.

**Comment by humblec** [comment] 2019-05-07 11:17
Once above PR is merged, @Madhu-1 would you be changing the default branch to `master`?

**Comment by Madhu-1** [comment] 2019-05-07 11:20
yeah, am planning to make master as the default branch. I will wait till EOD if anyone has any suggestions.

**Comment by humblec** [comment] 2019-05-13 06:04
What has been achieved so far:
[x] Master is the default branch now.
[x] Master branch has been filled with missed PRs from CSI v1.0 branch

**Comment by humblec** [comment] 2019-05-28 10:21
Progress:

- [x] E2E prereq PRs are merged.
- [x] Stateless RBD is merged, cephfs is pending/WIP
- [x] Ceph Mgr based Volume provisioning is pending/WIP

**Comment by sandromodarelli** [comment] 2019-05-29 13:48
rbd volume resizing will be included in v1.1?

**Comment by humblec** [comment] 2019-05-29 13:50
> rbd volume resizing will be included in v1.1?

There is a PR in progress and I would like to get this in next minor release.

**Comment by humblec** [comment] 2019-06-04 08:51
[Status update]:

- [x] E2E is now available in this Repo!! Its been enabled for all the PRs landing here.
- [x] stateless PRs are merged.
- [x] updated kube dependency to 1.14.2.
- [x] updated all sidecar containers to latest available.

Pending
- [x] Ceph Mgr based volume provisioning https://github.com/ceph/ceph-csi/pull/400

**Comment by humblec** [comment] 2019-06-04 08:52
@sandromodarelli here is the release planning of https://github.com/ceph/ceph-csi/issues/393. If you wish to see any features or bug fixes, please feel free to mention it there.

**Comment by humblec** [comment] 2019-06-04 08:56
https://github.com/ceph/ceph-csi/pulls?q=is%3Apr+is%3Aclosed+label%3Arelease-1.1.0

**Comment by humblec** [comment] 2019-06-07 04:37
[status update]

Last item to sort out for the release!

https://github.com/ceph/ceph-csi/pull/400

**Comment by humblec** [comment] 2019-06-13 06:04
> [status update]
> 
> Last item to sort out for the release!
> 
> #400
> 
> The cephfs container image need to be updated with the minor fixes we require to support cephfs volume provisioning via ceph mgr by ceph-csi. Even though the fixes are available, this image is yet to be updated . We are postponing the release to `12-Jun-2019` to finish this task.

We are still waiting for the upstream ceph container image update to roll out this release. Delay of couple of weeks is expected, however working on other methods to address it, if possible

**Comment by ktdreyer** [comment] 2019-06-13 16:18
While we wait for Ceph upstream to cut a v14.2.2 release, I see many other open tickets in the ceph-csi project that have a "release-1.1.0" label. Can we resolve these in the meantime?

**Comment by humblec** [comment] 2019-06-18 13:36
@ktdreyer Its other way around :), while we wait, we are getting maximum in. :)

**Comment by tiwalter** [comment] 2019-06-25 11:21
@humblec does this mean, that you generally need the CEPH version 14.2.2 for running v1.1.0?

**Comment by humblec** [comment] 2019-06-25 11:28
>@humblec does this mean, that you generally need the CEPH version 14.2.2 for running v1.1.0?
>

@tiwalter yeah! or (latest) nautilus version which support ceph manager based cephfs volume provisioning. The reason being the ceph manager based volume provisioning has to be supported in the cluster and thats what we are trying achive with PR#400 . We are also figuring out if we can get `14.2.1` latest build with required patches in. Any specific queries on this ?

**Comment by tiwalter** [comment] 2019-06-25 12:00
@humblec thanks ! ;)

The problem is, that i have CEPH v12.2.10 and need the feature "Resize Ceph FS volumes" (https://github.com/ceph/ceph-csi/pull/412), that will be available with the newest v1.1.0.

Is there any opportunity to use this feature without the newest CEPH version?
Or is it possible to release for example version 1.0.1 with the new features (like resizing) except the used features of the new CEPH nautilus version?

**Comment by humblec** [comment] 2019-06-25 13:10
> @humblec thanks ! ;)

YW :)

> 
> The problem is, that i have CEPH v12.2.10 and need the feature "Resize Ceph FS volumes" (#412), that will be available with the newest v1.1.0.
>

I see :).  Valid ask.

 
> 
> Is there any opportunity to use this feature without the newest CEPH version?

The version `1.0` plugin use a different mechanism which use "subdirs".  Ideally if we add resize support for that branch (`1.0`) it should work too. However the 'resize' sidecar..etc have to be added/qualified too. Let me think some more before confirming. 

> Or is it possible to release for example version 1.0.1 with the new features (like resizing) except the used features of the new CEPH nautilus version?
>

We had a thought about it. It duplicate good amount of work between branches. The main reason for `1.1.0` is to  have a base with couple of breaking changes like `CephManger based volume provisioning, Stateless implementation..etc` . Because thats the way forward or base for future versions and we have to guarentee we will not break in any upcoming releases or future versions.  

The existing branches should continue working without disturbance but with available features and not really with new features. Also we have very limited hands here :).. If you could contribute features to `1.0` branch like resize, please feel free. We could get that in or review.  Its maintained, just that we dont have capacity to add or duplicate features. :)

**Comment by tiwalter** [comment] 2019-06-25 15:28
> We had a thought about it. It duplicate good amount of work between branches. The main reason for 1.1.0 is to have a base with couple of breaking changes like CephManger based volume provisioning, Stateless implementation..etc . Because thats the way forward or base for future versions and we have to guarentee we will not break in any upcoming releases or future versions.

Yes, i'm absolutely with you ;)

> The existing branches should continue working without disturbance but with available features and not really with new features. Also we have very limited hands here :).. If you could contribute features to 1.0 branch like resize, please feel free. We could get that in or review. Its maintained, just that we dont have capacity to add or duplicate features. :)

I also understand this point of view. 

Nevertheless, it also impossible to release a new Version "1.0.1" with the resizing functionality (and maybe more features) even if we implement this feature and open a PR for it?
I think, that a lot of people have not the newest CEPH version and an update on a productive system generates a big administrative overhead. 

I think it would be creat, if we provide a matrix, which version of the plugin works with which CEPH version. 
For example: 
- csi plugin v1.10.xx for CEPH > v14.2.2
- cs plugin v1.0.xx for CEPH >= v12.x and < v14.2.2
Maybe we can set up a CI-Pipeline for CEPH Luminous, Mimic and Nautilus.

I know it will cause duplicated features, but you have now the compatibility with old CEPH versions. But if you define, that all the features for old branches should be developed by the community, it's a win win situation ;) You only have to review and release the versions.

**Comment by humblec** [comment] 2019-07-03 07:07
> > We had a thought about it. It duplicate good amount of work between branches. The main reason for 1.1.0 is to have a base with couple of breaking changes like CephManger based volume provisioning, Stateless implementation..etc . Because thats the way forward or base for future versions and we have to guarentee we will not break in any upcoming releases or future versions.
> 
> Yes, i'm absolutely with you ;)

Thanks!

> 
> > The existing branches should continue working without disturbance but with available features and not really with new features. Also we have very limited hands here :).. If you could contribute features to 1.0 branch like resize, please feel free. We could get that in or review. Its maintained, just that we dont have capacity to add or duplicate features. :)
> 
> I also understand this point of view.
> 
> Nevertheless, it also impossible to release a new version "1.0.1" with the resizing functionality (and maybe more features) even if we implement this feature and open a PR for it?
> I think, that a lot of people don't have the newest CEPH version and an updating a productive system generates a big administrative overhead.
> 
Yeah, true, but we are taking help from "Rook" to simplify this process.


> I think it would be creat, if we provide a matrix, which version of the plugin works with which CEPH version.
> For example:
> 
>     * csi plugin v1.10.xx for CEPH >= v14.2.2
> 
>     * cs plugin v1.0.xx for CEPH >= v12.x and < v14.2.2

Completely agree and this matrix will be available with 1.1 release.

> 
> 
> Maybe we can set up a CI-Pipeline for CEPH Luminous, Mimic and Nautilus.
> 
> I know it will cause duplicated features, but then you have the compatibility with old CEPH versions. And if you define, that all the features for old branches should be developed by the community, it's a win win situation ;) You only have to review and release the versions.

Sure, that make better deal, but please note that, there are huge number of bug fixes or enhancements went to "master" branch which are missing in `1.0` branch.

**Comment by humblec** [comment] 2019-07-03 07:11
[status update] 

Apologies for the delay on rolling out this release, but we have a good news that, an upstream ceph container is available now with a tag `latest-nautlius-devel`which is very very close to `Ceph Nautlius 14.2.2` . It is helpful to unblock our Ceph Manager based PRs or work. We expect the release to be made available soon :

ETA :  08- Jul - 2019

**Comment by humblec** [comment] 2019-07-08 11:36
[Status update]

The Rook Master has been updated to use `latest-nautlius-devel` tagged containers and  #400 is ready to go. We are on track for the release!!

**Comment by humblec** [comment] 2019-07-13 09:41
Finally, the release is OUT !!! 

Details @ https://github.com/ceph/ceph-csi/releases/tag/v1.1.0 

Thanks all for the contribution and making this big release out ! 

@rootfs @gman0   @Madhu-1 @poornimag @ShyamsundarR @j-griffith @travisn  @leseb @tiwalter @ajarr @batrick @dillaman ...etc!!

**Closed** 2019-07-13 09:41 UTC
Labels: release-1.1.0
