### ISSUE TITLE
How is cephfs's quota set in ceph-csi?

### ISSUE THREAD

**Issue by gaoguangze111** [ceph/ceph-csi#831] opened 2020-02-16 14:38 UTC
# Describe the bug #

In ceph-csi\pkg\cephfs\volume.go, there is the function 'createVolume' which is used to expand cephfs volume:

```
func createVolume(ctx context.Context, volOptions *volumeOptions, cr *util.Credentials, volID volumeID, bytesQuota int64) error {
	//TODO: When we support multiple fs, need to hande subvolume group create for all fs's
	if !cephfsInit {
		err := execCommandErr(
			ctx,
			"ceph",
			"fs",
			"subvolumegroup",
			"create",
			volOptions.FsName,
			csiSubvolumeGroup,
			"-m", volOptions.Monitors,
			"-c", util.CephConfigPath,
			"-n", cephEntityClientPrefix+cr.ID,
			"--keyfile="+cr.KeyFile)
		if err != nil {
			klog.Errorf(util.Log(ctx, "failed to create subvolume group csi, for the vol %s(%s)"), string(volID), err)
			return err
		}
		klog.V(4).Infof(util.Log(ctx, "cephfs: created subvolume group csi"))
		cephfsInit = true
	}

	args := []string{
		"fs",
		"subvolume",
		"create",
		volOptions.FsName,
		string(volID),
		strconv.FormatInt(bytesQuota, 10),
		"--group_name",
		csiSubvolumeGroup,
		"--mode", "777",
		"-m", volOptions.Monitors,
		"-c", util.CephConfigPath,
		"-n", cephEntityClientPrefix + cr.ID,
		"--keyfile=" + cr.KeyFile,
	}

	if volOptions.Pool != "" {
		args = append(args, "--pool_layout", volOptions.Pool)
	}

	err := execCommandErr(
		ctx,
		"ceph",
		args[:]...)
	if err != nil {
		klog.Errorf(util.Log(ctx, "failed to create subvolume %s(%s) in fs %s"), string(volID), err, volOptions.FsName)
		return err
	}

	return nil
}
```

It uses 'ceph fs subvolume' to expand volume, but in cephfs doc it uses the following command to expand quota (link: http://docs.ceph.org.cn/cephfs/quota/):
```
setfattr -n ceph.quota.max_bytes -v 100000000 /some/dir
```

Is this a bug?
# Environment details #

```
Ceph latest version
```

**Comment by joscollin** [comment] 2020-02-18 02:23
@gaoguangze111 It's not a bug. This is the correct doc for the subvolume create: https://docs.ceph.com/docs/nautilus/cephfs/fs-volumes/#fs-subvolumes. The doubt comes because `ceph-csi\pkg\cephfs\volume.go` uses an old mgr/volume interface (fs subvolume create) for setting/unsetting the quota.

**Comment by Madhu-1** [comment] 2020-02-25 05:38
am closing this one as not a bug since we are using ceph fs subvolume commands. please feel free to reopen if there is a bug in code

**Closed by Madhu-1** 2020-02-25 05:38 UTC
Labels: cephfs
